### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by DutchPete** [Yaozhuwa/easy-typing-obsidian#1]
I download the zip file, unzipped it to `.obsidian/plugins` folder.
Tried to enable it in the Obsidian setting, but got a message "Failed to load".
[May-11-2021 18-39-26.gif.zip](https://github.com/Yaozhuwa/easy-typing-obsidian/files/6460387/May-11-2021.18-39-26.gif.zip)

**Comment by Yaozhuwa** [comment]
I develope the plugin on Windows10, and only test it in ubuntu18 and windows10. 

I guess you only put the source code to your folder. You need to download the newest **release (not source code!)** and Copy over `main.js`, `manifest.json` to your vault VaultFolder/.obsidian/plugins/your-plugin-id/. Then reload your obsidian.

![image](https://user-images.githubusercontent.com/28787183/117862508-4ae8bc00-b2c5-11eb-87e9-b4c4664ecc58.png)

**Comment by DutchPete** [comment]
Yep, now it loads. Thank you.
