### ISSUE TITLE
输入……（shift+6）转换为^

### ISSUE THREAD

**Issue by Benature** [Yaozhuwa/easy-typing-obsidian#10]
在使用块引用的时候需要键入`^`，但是中文输入时`shift+6`对应的是`……`，个人目前没有`……`的使用场景（不清楚其他人可能会用到），因此可否新增一个功能，自动把输入`……`转换为`^`，可以在配置区选择是否启用此功能。

**Comment by Yaozhuwa** [comment]
3.2.2版本加了这个功能了

**Comment by Benature** [comment]
升级后可以了！感谢！
