### ISSUE TITLE
[Bug] v5.1.0 版本自动格式化失效。 Autoformat not work in 5.1.0

### ISSUE THREAD

**Issue by xu-99hh** [Yaozhuwa/easy-typing-obsidian#105]
无法在编辑状态下自动格式化，如无法自动在数字、英文和中文之间空格。

**Comment by zen010101** [comment]
刚升级了5.1.0，也遇到了此问题。目前只能通过 Ctrl-Shift-S 来激活全文格式化功能。

**Comment by xu-99hh** [comment]
刚开始以为是插件冲突，后来使用另外一个库也会出现同样的问题，无法实时格式化。

**Comment by Yaozhuwa** [comment]
我在ubuntu 和 Mac上测试都没有问题，又找了台windows的电脑，出现问题了。

我今天晚点看看紧急修复一下。

**Comment by xu-99hh** [comment]
我的是m1的macbook air，ob是最新版的v1.0.3。

**Comment by xu-99hh** [comment]
把插件卸载了重装，还是会出现问题。

**Comment by Yaozhuwa** [comment]
非常抱歉给大家带来麻烦

目前 5.1.1 版本应该修复了这个问题，更新后重启插件或者Ob 即可解决~

**Comment by Yaozhuwa** [comment]
非常抱歉给大家带来麻烦

目前 5.1.1 版本应该修复了这个问题，更新后重启插件或者Ob 即可解决~

**Comment by xu-99hh** [comment]
已解决，感谢开发者

**Comment by Lulullia** [comment]
I also had this issue in 5.1.0 and it's now solved in 5.1.1. Thanks for the quick fix!
