### ISSUE TITLE
輸入符號或英數再輸入中文字，再按Enter中文會出現第二次

### ISSUE THREAD

**Issue by kin30528** [Yaozhuwa/easy-typing-obsidian#106]
例如.我>. 我我
y我>y 我我
2我>2 我我

使用的是繁體中文，不知道有沒有關係，請問如何解決問題？

**Comment by Yaozhuwa** [comment]
无法复现，可能我误解了你的意思，能提供相关录屏GIF吗？
![iShot_2022-12-20_23 52 08](https://user-images.githubusercontent.com/28787183/208709325-b2cd1509-4a76-4b0d-939d-2d50aad3df54.gif)

**Comment by kin30528** [comment]
[https://imgur.com/a/m585s6k](url)
謝謝協助檢查
OB版本v1.1.8 (win10)
輸入法：微軟注音（大部分台灣人都用這個）

**Comment by Yaozhuwa** [comment]
这个很可能是输入法的问题，可能换个输入法就好了。

你可以在插件设置中打开最底下的Debug开关，Ctrl+Shift+I打开控制台，然后在编辑界面复现这个问题，将控制台的输出发我看一下，我也许能找到问题并解决它。

**Comment by kin30528** [comment]
K我

ViewUpdate Catch Change-> Type: input.type.compose,  0 0  0 1 K
plugin:easy-typing-obsidian:1567 ViewUpdate Catch Change-> Type: input.type.compose,  1 1  1 2 ㄨ
plugin:easy-typing-obsidian:1567 ViewUpdate Catch Change-> Type: input.type.compose,  2 2  2 3 ㄛ
plugin:easy-typing-obsidian:1567 ViewUpdate Catch Change-> Type: input.type.compose,  1 3 ㄨㄛ 1 2 我
plugin:easy-typing-obsidian:1567 ViewUpdate Catch Change-> Type: EasyTyping.change,  0 2 K我 0 3 K 我

**Comment by Yaozhuwa** [comment]
从输出上看本插件的流程没有问题： Type: input.type.compose 是输入法对文本的改动，Type: EasyTyping.change 是本插件做文本的改动，最后是把 `K我 变成了 `K 我` 。

**Comment by kin30528** [comment]
好的，謝謝您

**Comment by Gavin-jy** [comment]
我也遇见了同样的这个问题。
微软拼音输入法，obsidian版本1.1.9。
触发的条件同样是自动调整空格的功能，例如输入“这是一个A方案”会被自动调整成“这是一个 A 方案方案”，调整空格之后还输入了一次多的“方案”。
附上控制台的输出：
![image](https://user-images.githubusercontent.com/59945254/209586907-38a5652f-481f-444f-80f1-b0c0b0fc4ed5.png)
可以看到最后插件又打印了一次“方案”这个词

**Comment by Yaozhuwa** [comment]
> 我也遇见了同样的这个问题。 微软拼音输入法，obsidian版本1.1.9。 触发的条件同样是自动调整空格的功能，例如输入“这是一个A方案”会被自动调整成“这是一个 A 方案方案”，调整空格之后还输入了一次多的“方案”。 附上控制台的输出： ![image](https://user-images.githubusercontent.com/59945254/209586907-38a5652f-481f-444f-80f1-b0c0b0fc4ed5.png) 可以看到最后插件又打印了一次“方案”这个词

这里的调试信息显示插件将`A方案`替换成了`A 方案`，然后输入法又添加了方案两个字吗，导致了重复。这种情况和输入法有关系，我也不知道如何解决。目前只能建议换别的输入法试试。

**Comment by lisasuosuo** [comment]
这个问题我也遇到了，通过关掉微软拼音的智能纠错和模糊输入，解决了这个问题。

**Comment by lwl20001017** [comment]
![image](https://user-images.githubusercontent.com/60725142/217989836-449f2dac-d633-46c1-9b38-76845feb26c6.png)
关闭微软拼音中的【兼容性】，问题得到解决

**Comment by IronShannon** [comment]
> 关闭微软拼音中的【兼容性】

感谢~确实有效

**Comment by liuke101** [comment]
我也遇到了这个问题，确定是旧版本微软输入法的问题

**Comment by Yaozhuwa** [comment]
v5.2.0 版本支持了微软输入法，建议更新尝试~

**Comment by kin30528** [comment]
> v5.2.0 版本支援了微軟輸入法，建議更新嘗試~
@Yaozhuwa 謝謝你的開發與更新，微軟注音也可以使用了，真的很方便，喜歡這個插件，感激~
