### ISSUE TITLE
时分秒中间用于分隔的冒号后会自动插入空格

### ISSUE THREAD

**Issue by jqk** [Yaozhuwa/easy-typing-obsidian#107]
`12:34:56` 变成 `12:34 : 56`，`1:30` 变成 `1: 30`。前者插入了两个空格，后者只在冒号后插入了一个空格。
中英文模式下输入好象效果一样。尤其是时间之后写标点或其它文字时。

神奇的是，和时间内容有些相关：
`12:34 分`正常，但`1: 30 分`冒号之间就多了空格。

另外，`12:34 ，`标点与34之前有空格。其它标点也是这样。

想正确，必须将时间套在``之间。

非常棒的插件！这些bug虽小，难度不大但很麻烦。非常感谢！

**Comment by Yaozhuwa** [comment]
收到，下一个版本修复~

**Comment by Yaozhuwa** [comment]
5.1.2 已修复

**Comment by jqk** [comment]
感谢感谢！

对于 `1:30` 这类单时双分的，都没问题了。但仍有 bug 如下：

1. 对于 `12:34` 这类双时双分的，后面加标点，仍添加空格：`12:34 ，`
2. 无论小时是 1 位还是 2 位，只要有秒，输入时即错误，例如 `12:34:56`，在 `34` 与后面的冒号间添加了空格：`12:34 : 56`。

我添加了正则 `\d{1,2}:\d{2}(:\d{2})?|==` 也没起啥作用。只是 `12:34 : 56` 变 `12:34 :56` 了，但标点前又有空格了。

我在想，编程，尤其是日志中，经常用于毫秒，经常写成类似 `12:34:56.789` 的形式，不知能否正确处理。

先搞定第一步吧！还指望这插件完善后，移植到 VSCode 中呢！

多谢！

**Comment by Yaozhuwa** [comment]
是我在上传release版本的时候传错了，我今天晚点重新更新下

> 还指望这插件完善后，移植到 VSCode 中呢！

暂时没有计划

**Comment by Yaozhuwa** [comment]
> 感谢感谢！
> 
> 对于 `1:30` 这类单时双分的，都没问题了。但仍有 bug 如下：
> 
> 1. 对于 `12:34` 这类双时双分的，后面加标点，仍添加空格：`12:34 ，`
> 2. 无论小时是 1 位还是 2 位，只要有秒，输入时即错误，例如 `12:34:56`，在 `34` 与后面的冒号间添加了空格：`12:34 : 56`。
> 
> 我添加了正则 `\d{1,2}:\d{2}(:\d{2})?|==` 也没起啥作用。只是 `12:34 : 56` 变 `12:34 :56` 了，但标点前又有空格了。
> 
> 我在想，编程，尤其是日志中，经常用于毫秒，经常写成类似 `12:34:56.789` 的形式，不知能否正确处理。
> 
> 先搞定第一步吧！还指望这插件完善后，移植到 VSCode 中呢！
> 
> 多谢！

内置的时间戳识别的优先级要小于用户自定义正则，所以你要先删除自定义正则区域的相关规则。如果没有问题的话还请反馈一下，谢谢~

**Comment by jqk** [comment]
# 关于 easy typing 的小问题

创建了一个新库，只安装了 easy typing，使用默认设置。

## 场景一：使用冒号分隔时间

### 1.1 使用 `万能五笔` 输入法

- 测试 1：1:34 全面通过
- 测试 2：1:34:56，第二个冒号使用英文半角通过
- 测试 3：1:34 : 56，第二个冒号使用全角时，转换半角成功，但加入了两个空格
- 测试 4：1:34:56.789，半角通过
- 测试 5：12:34:56.789，半角通过

### 1.2 使用 `微软五笔` 输入法

- 测试 1：1：34，全角未转换为半角冒号
- 测试 2：1:34:56，半角通过。
- 测试 3：1：34：56，全角未转换为半角冒号
- 测试 4：1:34:56.789，半角通过
- 测试 5：12:34:56.789，半角通过

### 1.3 使用 `微软拼音` 输入法

- 测试 1：1：34，全角未转换为半角冒号
- 测试 2：1:34:56，半角通过。
- 测试 3：1：34：56，全角未转换为半角冒号
- 测试 4：1:34:56.789，半角通过
- 测试 5：12:34:56.789，半角通过

### 1.4 总结

使用英文半角输入冒号都没有问题。
使用全角中文输入都有问题。微软输入法的问题相同，都是没将全角冒号转为半角；万能五笔都转了，但第二个前后插入了空格。

所以，如果不好改，就记得只用半角输入即可。

## 场景二：复制引用地址

将类似 `[百度一下，你就知道](https://www.baidu.com/)` 地址引用复制到书名号内，与无书名号效果不同。

先准备好`《》`：

- 书名号引用《 [百度一下，你就知道](https://www.baidu.com/) 》，书名号两边各有一个空格。粘贴完后直接按 `ctrl+z` 回退，前后的空格就会消失。
- 无书名号引用[百度一下，你就知道](https://www.baidu.com/)，不会插入空格。

但如果复制的不是地址引用，就没有问题。

- 书名号引用《复制引用地址》，不会出现空格。
- 无书名号引用复制引用地址，不会出现空格。

## 场景三：向<>中插入地址

先准备好 `<>`：
- 测试 1：粘贴地址，得到< https://www.baidu.com> ，两个问题：1）`<` 之后多了一个空格；2）`>` 后多了一个空格。
- 测试 2：不是地址，得到<Abcdefg>，没有以上问题。

一点点来吧。多谢了！

**Comment by Yaozhuwa** [comment]
v5.1.3 最新版本，场景1和场景2应该已经解决了。

对于场景三，在插件设置中第一行（越在前面的正则优先级越高），添加正则规则`<.*?>|--`，应该能解决你的问题。本质原因就是正则规则中的链接识别生效了。

**Comment by jqk** [comment]
非常感谢！

在我这里使用万能五笔都可以了。但微软两个输入法的全角冒号还是不转半角。但这个没关系。
已经很好了！
