### ISSUE TITLE
链接/超链与文本的空格策略

### ISSUE THREAD

**Issue by MinamiyamaHokuto** [Yaozhuwa/easy-typing-obsidian#108]
在 Obsidian 中书写 markdown，有时会遇到超链接嵌入文字的情况。该插件提供了一些解决方案，分别可以选择“呆/智能”与“无/软/严格”的组合。相关的六种组合如下：

- 第一次[[fabric 开发]] 内容。（dummy+no，前不空后空）
- 第二次 [[fabric 开发]]内容。（smart+no，前空后不空）
- 第三次[[fabric 开发]] 内容。（dummy+soft，前不空后空）
- 第四次 [[fabric 开发]]内容。（smart+soft，前空后不空）
- 第五次 [[fabric 开发]] 内容。（dummy+strict，前后均一空）
- 第六次  [[fabric 开发]] 内容。（smart+strict，前两空后一空）

有一篇很著名的排版规范和习惯说明 [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-Hans.md) 指出了一种“略带个人色彩”但确实存在的空格策略，即链接的左右为与正文区分都加上空格。在这样的规则下，上述第五次测试的结果是符合这种习惯的。

然而，这种”符合“在遇到全角符号的时候就失效了，像这样：

- 关于 [[fabric 开发]] 。（dummy+strict，全角句号前也有空）

能否考虑添加一种功能，通过把链接也考虑作一种特殊的西文或其他方式，不考虑其构成为CJK字符还是拉丁字母，统一在左右加上空格？也就是这样的效果：

- 关于 [[开发]]。（文本在非链接的场合下不该有空格。但”链接“**与非符号文本两端都有且仅有一个空格**，链接**与全角符号间没有空格**）

**Comment by Yaozhuwa** [comment]
这个可能是个bug。dummy+soft策略应该就是你所说的效果~下个版本修复它

**Comment by Yaozhuwa** [comment]
5.1.2 已修复~

**Comment by MinamiyamaHokuto** [comment]
> 5.1.2 已修复~

已更新了！效率真的好高，感谢🙏
