### ISSUE TITLE
连续全角转半角后不能触发自定义编辑转换

### ISSUE THREAD

**Issue by Lynx3x** [Yaozhuwa/easy-typing-obsidian#109]
因为看到插件有这个自定义编辑转换的功能，所以想了个快捷输入 `→` 的方法。

自定义转换：
"->|" auto convert to " →| "

但由于我输入`>`是通过`》》`的方式，导致这个规则触发不了，加了一条
"-》》|" auto convert to " →| "
也不行。

以前是有在其他地方看到过 `->` 可以自动转换成 `→` 的，但是不知道是怎么实现的，可能是通过样式？还是挺喜欢箭头的，但主要是没有什么便捷输入的方法所以其实一般打的也只是 `→`，不知道有没有什么好的解决方案参考？

**Comment by Yaozhuwa** [comment]
你可以试试规则"-》|" auto convert to " →| "

**Comment by Yaozhuwa** [comment]
转换规则是有优先级的，而且为了防止死循环，目前不会连续触发规则。

**Comment by Lynx3x** [comment]
> 你可以试试规则"-》|" auto convert to " →| "

原来如此，成功了，感谢指导！
