### ISSUE TITLE
输入tag时的几点建议

### ISSUE THREAD

**Issue by Benature** [Yaozhuwa/easy-typing-obsidian#11]
~~emmm是的又是我提issue了（有点刷屏了）~~

1. feature request: 在井号`#`之前还有一个空格才会被识别为tag，但是在中文标点后面输入#的时候因为中文标点本身后面留的空白比较多，有时候分不清那里是否已经有空格了，而且中文输入（个人）习惯一般不会敲空格。
  所以希望在输入#的时候也支持在中文之间加入空格。
2. bug: 开启中英空格功能后，输入的tag文本如`#中文Chinese/test`会被自动假如的空格拆开成`#中文 Chinese/test`
```diff
- #中文 Chinese/test
+ #中文Chinese/test
```
![image](https://user-images.githubusercontent.com/35028647/121800813-8977ea80-cc66-11eb-8cc7-a2e2ed9c6184.png)

感谢作者的高效开发

**Comment by Yaozhuwa** [comment]
>feature request: 在井号#之前还有一个空格才会被识别为tag，但是在中文标点后面输入#的时候因为中文标点本身后面留的空白比较多，有时候分不清那里是否已经有空格了，而且中文输入（个人）习惯一般不会敲空格。
所以希望在输入#的时候也支持在中文之间加入空格。

第一个问题好解决，之后我会加上这个功能。

**Comment by Yaozhuwa** [comment]
>bug: 开启中英空格功能后，输入的tag文本如#中文Chinese/test会被自动假如的空格拆开成#中文 Chinese/test

对于第二个问题，其实不算bug。更新到v3.2.2版本后，你只需要加一个正则表达式，`#[A-Za-z0-9\u4e00-\u9fa5\/]+`就行。

支持自定义正则表达式后，其实很多问题都可以用户自己添加正则来解决了。

![image](https://user-images.githubusercontent.com/28787183/122105645-9c97df80-ce4b-11eb-9f25-ddc8ee735304.png)

**Comment by Yaozhuwa** [comment]
>感谢作者的高效开发

我也非常欢迎你来提issue 啊，这样才能把插件做得更好啊，哈哈哈。

**Comment by Benature** [comment]
>支持自定义正则表达式后，其实很多问题都可以用户自己添加正则来解决了。

确实。这里我又想到一个建议了，可能有些用户不是很熟悉正则，这些常用的（且不是default的）可以考虑在readme列出来？如果有人想要相关功能搜一下很快就能知道怎么改了，也不用自己再去学正则🤔

**Comment by Benature** [comment]
> 我也非常感谢和欢迎你常来提 issue 啊，这样才能把插件做得更好啊，哈哈哈。

互帮互助哈哈😺  另外也要早点休息鸭
