### ISSUE TITLE
About adding Spaces automatically to headings

### ISSUE THREAD

**Issue by cubxxw** [Yaozhuwa/easy-typing-obsidian#110]
## The problem
When inserting the title, the Chinese and English Spaces are also automatically inserted, which I don't want

**Comment by Yaozhuwa** [comment]
You can turn off autoformat using shortcut `Ctrl+tab` when you are editing the title.

**Comment by cubxxw** [comment]
@Yaozhuwa Are there plans to incorporate this into the setup?

**Comment by Yaozhuwa** [comment]
I don't have plan to add this feature yet.

**Comment by cubxxw** [comment]
yep, i see 🎈
