### ISSUE TITLE
关于自动去除空白行会去除代码块与图片之间空行的问题

### ISSUE THREAD

**Issue by yulate** [Yaozhuwa/easy-typing-obsidian#111]
会出现这种代码块和图片黏在一块的问题，非常不美观，请问是否有办法可以解决这个问题
![image](https://user-images.githubusercontent.com/53947823/210428189-ca4d280d-c719-40df-bc0f-1db97ceb98eb.png)

**Comment by Yaozhuwa** [comment]
```
img:not([class*="emoji"]) {
  display: block;
  margin-top: 3px !important; 
  margin-bottom: 3px !important;
}
```
