### ISSUE TITLE
光标符号

### ISSUE THREAD

**Issue by kingwingfly** [Yaozhuwa/easy-typing-obsidian#113]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/38573173/212816430-7181a28e-1d93-4aab-89af-f0d180ce9048.png">

如图，想将两个中文`｜`转化成英文`|`。

实际体验中，总是认为第一个`|`是光标，导致输入两次中文`｜`后，光标在转化成的英文`|`之前，还需要移动光标到正确的位置，比较不方便。

我也猜着试了一下光标是否有转义功能，结果应该是没有的。
……
所以有啥办法处理一下吗 (^з^)-☆

**Comment by Yaozhuwa** [comment]
目前还不支持 | 的自定义规则~

**Comment by kingwingfly** [comment]
在MacOS上，文件名可以出现`/`。在python中，如果要输入这个文件的路径，`/`会被当作路径分隔处理导致无法处理该文件。python的做法是用`:`来代表路径中的`/`。所以是否可以设置一串特殊的字符来表示光标位置呢？😏

**Comment by Yaozhuwa** [comment]
这样做是可以的，我正想参考 Latex Suite 插件的做法。而且目前的自定义规则功能还有很多欠缺，如支持正则表达式匹配识别，还有设置多光标Tab 跳转，规则配置的导入导出等~ 

但是需要一段时间来实现

**Comment by Jed-Z** [comment]
同样有这个需求。在 macOS 中文输入法下，按 Shift + \ 会打出全角竖线（`｜`），但在 Obsidian 中，半角竖线常用于和链接组合使用（如指定链接显示文本、指定图片大小等），需要经常切换中英文。希望 Easy Typing 可以支持光标符号 `|` 的转义。

**Comment by kingwingfly** [comment]
#145

**Comment by Yaozhuwa** [comment]
v5.1.11版本对连续全角转半角的功能：增加了连续输入两个全角竖线转半角竖线的规则 ~
