### ISSUE TITLE
关于五笔输入时会出现的问题

### ISSUE THREAD

**Issue by huangjch0** [Yaozhuwa/easy-typing-obsidian#114]
easy typing感觉对于五笔用户巨不友好，比如：

我现在点击字母 ggtt (会生成“五笔”中文)，然后我再点击其他字母如 aaaa(原本应该生成“五笔工”)，它就会变成“五笔 a 五笔 a 五笔 a 五笔工”，很怪​

但是如果你在点击字母 ggtt，然后再点击空格，或者它自己会自动上屏，此时再点击其他字母则不会出现如此问题。

**Comment by Yaozhuwa** [comment]
我不懂五笔，你可以提供录屏演示一下问题吗？

此外，请在插件设置中打开最底下的debug开关，然后用快捷键ctrl+shift+i（windows），cmd+option+i （mac）打开控制台，然后在编辑器复现你的问题，把控制台输出发我一下，我可能能找到问题。

**Comment by Yaozhuwa** [comment]
> 此外，请在插件设置中打开最底下的debug开关，然后用快捷键ctrl+shift+i（windows）打开控制台，然后在编辑器复现你的问题，把控制台输出发我一下，我可能能找到问题。

**Comment by Yaozhuwa** [comment]
[main.txt](https://github.com/Yaozhuwa/easy-typing-obsidian/files/10443930/main.txt)

我初步尝试修复一下这个问题，你看下有没有效果。

你下载一下这个文件，然后将其改名为 main.js ，将其放到本插件目录下（库目录/.obsidian/plugins/easy-typing-obsidian/），替换原来的 main.js ，然后重启obsidian。

测试后还请反馈下有没有效果。

**Comment by Yaozhuwa** [comment]
好的，那我下一个版本就更新修复这个问题~
