### ISSUE TITLE
输入文件扩展名的问题

### ISSUE THREAD

**Issue by jqk** [Yaozhuwa/easy-typing-obsidian#115]
你好！

现在有一个问题，输入文件扩展名，如 `.doc` 之类的，或者 `.net framework`，这个 `.` 与之后的内容为出现一个空格。
对于推测 `.` 是英文一句话的结尾，加空格是正确的。但英文一句结束的话， `.` 之前正常是英文或数字之类的。

但如果 `.` 之前有空格，或者其之前是中文的标点，其后加空格就存在问题了。至少输入文件扩展名就有了前述的问题。

感谢回应及时，希望软件能越做越好。

**Comment by Yaozhuwa** [comment]
> 现在有一个问题，输入文件扩展名，如 `.doc` 之类的，或者 `.net framework`，这个 `.` 与之后的内容为出现一个空格。 对于推测 `.` 是英文一句话的结尾，加空格是正确的。但英文一句结束的话， `.` 之前正常是英文或数字之类的。
> 
> 但如果 `.` 之前有空格，或者其之前是中文的标点，其后加空格就存在问题了。至少输入文件扩展名就有了前述的问题。

感谢你的想法，很有道理，我可以设置只有英文、数字或者中文后的`.`才识别为标点，应该能解决问题。下个版本会加上~

**Comment by Yaozhuwa** [comment]
> 只有英文、数字或者中文后的.才识别为标点

V5.1.4 版本应该可以了

**Comment by jqk** [comment]
写扩展名的功能可以了。但出了个 bug：

中文之后，输入了中文句号。此时，按一下 `.`，中文句号被删除替换为 `.`，再按一下 `.`，出现中文句号，再按，中文句号被替换，如此往复。全是在中文输入状态进行，我这里三种输入法效果相同：

按1下：`。`
按2下：`.`
按3下：`.。`
按4下：`..`
按5下：`..。`
按6下：`...`

**Comment by Yaozhuwa** [comment]
这不是 Bug，请查看插件功能说明，这是连续全角转半角的功能开启了。

**Comment by jqk** [comment]
还真是！
