### ISSUE TITLE
如果把命令翻译成中文就更好了

### ISSUE THREAD

**Issue by huangzeweihhh** [Yaozhuwa/easy-typing-obsidian#116]
去除空行的命令是挺好滴，因为说明书里没有说，我过了好几个月我才发现那么方便的功能，或者若把命令译成中文、日语、韩语使用就更方便了，毕竟英语国家几乎是用不到这个插件。：）

**Comment by Yaozhuwa** [comment]
可以的，下次更新会有中文。

**Comment by Yaozhuwa** [comment]
新版本已有中文

**Comment by huangzeweihhh** [comment]
我试用了中文输入命令，效果非常好，我感觉用双拼来输入中文搜索出命令的速度比输英文要快，自从有了这个插件，我没有再出现打字前必须瞟一眼输入法是中文还是英文，也没有再代码里面输了一个外观不明显的中文符号造成bug。

我每天都会琢磨怎么增加自定义符号会比较方便。我不太懂编程，所以有很多疑问，或许会另开一个issue

**Comment by Yaozhuwa** [comment]
v5.1.6 的命令 正式支持了多语言。命令的显示语言会随着软件设置变化而改变，设置-关于-语言。

目前支持 简体中文-繁体中文-英语。
