### ISSUE TITLE
分别控制 数字 与 英文 是否空格

### ISSUE THREAD

**Issue by Ton-yi** [Yaozhuwa/easy-typing-obsidian#117]
![image](https://user-images.githubusercontent.com/73752817/213307027-42911fcc-39a6-4a66-97d3-1026c7980261.png)

我比较想要英文左右有空格，但数字直接连着中文就好

**Comment by Yaozhuwa** [comment]
之后我会添加这个功能

**Comment by Yaozhuwa** [comment]
v5.1.6 版本已增加了该功能设置
