### ISSUE TITLE
这数字也分得太开了，如何解决呢？

### ISSUE THREAD

**Issue by zhl111** [Yaozhuwa/easy-typing-obsidian#12]
按说数字间加标点符号不应该有空格，但这就会自动填充空格![image](https://user-images.githubusercontent.com/29135984/122409437-b8b79000-cfb5-11eb-847e-08474a526a4c.png)

**Comment by Yaozhuwa** [comment]
最新版本应该不会把数字和 `.` 号用空格分开，你更新一下插件吧

**Comment by zhl111** [comment]
是最新版的，是要把这个关闭吧？![image](https://user-images.githubusercontent.com/29135984/122503472-10dca980-d02b-11eb-99a6-7e6483c1ba02.png)

**Comment by Yaozhuwa** [comment]
不用关这个选项也不会把数字和 `.` 分开的。但是会把数字和其他英文标点分开。

**Comment by zhl111** [comment]
难道还有别的影响吗？我试了还是会分开![动画](https://user-images.githubusercontent.com/29135984/122561100-009cec80-d074-11eb-9cdf-a3990c037b66.gif)

**Comment by Yaozhuwa** [comment]
请问你是obsidian的版本还有平台是Mac吗。我自己在ubuntu和windows下测试都是没问题的。
或者有可能是其他插件的影响，你可以试下打开obsidian 的 help vault，然后只安装这个插件试试。

**Comment by zhl111** [comment]
我只有windows10的平台。我试着关闭了所有的插件，只保留easytyping，发现这现象还是存在，很有趣
![动画](https://user-images.githubusercontent.com/29135984/122626421-17c3f480-d0dd-11eb-9fa6-10103e28b98b.gif)
但是，我把所有的插件拷贝到新的vault，保持和之前的vault设置一样，就不会出现插入空格现象

**Comment by Yaozhuwa** [comment]
这有点奇怪，我暂时也搞不清楚是什么问题。。
