### ISSUE TITLE
输入书名号《》存在的问题

### ISSUE THREAD

**Issue by beforesun** [Yaozhuwa/easy-typing-obsidian#120]
当输入“《”的时候，
我期待的结果是“《|》”（“|”表示光标），
而实际的结果是“|《》”。
请教一下怎么调整才能实现我期待的结果

**Comment by Yaozhuwa** [comment]
我这边无法复现这个问题。

你可以在插件设置中打开最底下的Debug开关，Ctrl+Shift+I打开控制台，然后在编辑界面复现这个问题，将控制台的输出发我看一下，我也许能找到问题并解决它。

**Comment by beforesun** [comment]
1. 此为未打开debug开关复现情况![书名号问题-未打开debug](https://user-images.githubusercontent.com/45909516/215635938-87160b03-0435-4ee3-a76b-bf66b09498ee.gif)
2.此为打开debug开关后的情况![书名号问题-打开debug](https://user-images.githubusercontent.com/45909516/215635962-e825cd51-bd85-4a3b-931c-a756f664397a.gif)
3.此为打开开关后的截图![2023-01-31](https://user-images.githubusercontent.com/45909516/215636009-c4f6facf-7cf0-4ff7-a3ef-a2f06762b834.png)

我使用的是[RIME | 中州韻輸入法引擎](https://rime.im/)，Obisidian版本为1.1.9，Easy-typing版本为5.1.5。

辛苦你了。

**Comment by Yaozhuwa** [comment]
这个图片不对，控制台那边要选择console才能看到调试信息。发自我的 iPhone在 2023年1月31日，09:34，孙斌锋 ***@***.***> 写道：﻿

此为未打开debug开关复现情况
2.此为打开debug开关后的情况
3.此为打开开关后的截图

我使用的是RIME | 中州韻輸入法引擎，Obisidian版本为1.1.9，Easy-typing版本为5.1.5。
辛苦你了。

**Comment by beforesun** [comment]
![2023-01-31 (1)](https://user-images.githubusercontent.com/45909516/215686843-8249465f-f288-41f1-aee9-83408538a085.png)
这张呢？

**Comment by beforesun** [comment]
我换了个系统自带的输入法后再输入“《”，得到了我想要的结果。
估计是RIME输入法的缘故。
