### ISSUE TITLE
对于使用逗号分隔的数字，不应在数字和逗号之间加入空格

### ISSUE THREAD

**Issue by WOo0W** [Yaozhuwa/easy-typing-obsidian#121]
在英语中使用逗号分隔数字的规则：
[When should I use a comma to separate numbers? - The Grammar Guide (prowritingaid.com)](https://prowritingaid.com/grammar/1008091/When-should-I-use-a-comma-to-separate-numbers#:~:text=In%20English%2C%20we%20use%20commas,people%20turned%20up%20to%20protest.)

个人解决方案：
在设置中的格式化正则中加入 `(\d+,?)+\.?\d*|+-` 来排除如 `123,456.7890` 这样格式的数字。

**Comment by Yaozhuwa** [comment]
感谢你的启发，我想我应该设置数字间的`,`和`.`后面不添加空格。
