### ISSUE TITLE
iOS端Obsidian中开启本插件会导致重复粘贴

### ISSUE THREAD

**Issue by AmCzzZ** [Yaozhuwa/easy-typing-obsidian#124]
如题，在iOS的Obsidian中粘贴内容会自动粘贴两次，比如粘贴“下班啦！” 会得到 “下班啦！下班啦！”。
停用插件后问题解决。
我在macOS的Obsidian中没有遇到这个问题，但Obsidian好像不支持在mobile端单独关闭插件，所以还是希望您帮忙排查一下是哪里的问题。

**Comment by Yaozhuwa** [comment]
收到！

**Comment by Yaozhuwa** [comment]
v5.1.6 应该没问题了，我将 ios 端的粘贴自动格式化去掉就好了。
