### ISSUE TITLE
中文输入法下 Shift/Enter 输入英文时不会触发自动格式化

### ISSUE THREAD

**Issue by ghost** [Yaozhuwa/easy-typing-obsidian#125]
中文输入法下, 通过 `Shift` 切换为英文状态, 或通过 `Enter` 回车上屏输入的英文不会触发自动格式化

期望结果:
中文, eng
eng, eng
123, eng

实际结果:
中文,eng
eng,eng
123,eng

**Comment by Yaozhuwa** [comment]
这的确是个问题，目前没有找到好的方法来判断是英文输入上屏了。

**Comment by Fs-DXMY** [comment]
我注意到如果中英文之间没有空格, 换行时会自动添加上, 不知道这种情况是不是可以也这么处理

**Comment by Yaozhuwa** [comment]
> 我注意到如果中英文之间没有空格, 换行时会自动添加上, 不知道这种情况是不是可以也这么处理

换行时自动格式化的处理方法不能用于这里。

但是我找到了别的方法，但由于输入法的特性无法处理 Shift 的情况，在我的电脑上是可以处理 Enter 的情况（不同的输入法也可能导致不同的结果），不过我可以尝试作为实验性功能放到下一个更新里面~

**Comment by Yaozhuwa** [comment]
在 5.1.7版本中，我增加了一个实验性功能来解决回车输入英文的情况，你可以试试有没有问题：（需要去插件设置打开开关，默认是关闭状态）
<img width="647" alt="image" src="https://user-images.githubusercontent.com/28787183/217788154-657ba1ec-14a3-4a9d-8438-d4c338ac0ed1.png">

**Comment by hopebird** [comment]
还发现一个问题，关闭“英文和数字间加空格”后发现没有效果，还是自动加空格，不得已把自动格式化关闭才行。

**Comment by Yaozhuwa** [comment]
> 还发现一个问题，关闭“英文和数字间加空格”后发现没有效果，还是自动加空格，不得已把自动格式化关闭才行。

抱歉。。。上次更新把设置面板的这个变量写错了。。马上修复

**Comment by Yaozhuwa** [comment]
> 还发现一个问题，关闭“英文和数字间加空格”后发现没有效果，还是自动加空格，不得已把自动格式化关闭才行。

5.1.8 已修复

**Comment by Yaozhuwa** [comment]
> 问题依然存在, 我使用的是 Win11 自带的微软拼音输入法

我看了下，不同的输入法会有不同的按键响应和处理，而且在windows、mac、linux上也会有差异。这个适配起来太繁琐了，很可能别人的别的输入法又有问题，这样问题无止尽了，我就先不做处理了。你可以试试搜狗输入法。

**Comment by Yaozhuwa** [comment]
v5.2.0 版本支持了该功能，建议更新尝试~

**Comment by Yaozhuwa** [comment]
需要在本插件设置中打开实验性功能的相关按钮
