### ISSUE TITLE
是否考虑将双击 "、" 替换为输出字符 "\" 而不是 "/"

### ISSUE THREAD

**Issue by mkdir700** [Yaozhuwa/easy-typing-obsidian#127]
在中文模式下，双击 `、` 键将输出 `/`，我不太清楚这个映射关系是否符合中文键盘的映射关系，我见过的大多数键盘是将 `、` 与 `\` 绑定在一个键位上的，在中文模式下输出 `、`，英文模式下输出 `\`。

而 `/` 符号，即便是在中文模式下，本身只需要按一个键，并不需要专门去切换输入法。

所以，我理解的双击 `、` 理应输出 `\` 而不是 `/`。

改动点：

https://github.com/Yaozhuwa/easy-typing-obsidian/blob/e77da9d09a01f048a8cd607d07d348ed2fc45465/src/main.ts#L49

**Comment by Yaozhuwa** [comment]
可能和输入法有关，我的键盘的反斜杠中文模式下都是顿号~ 

我正在考虑把这个功能从基础编辑增强里面去掉，让用户通过自定义规则来自己定义，就不会有问题了。

**Comment by MinamiyamaHokuto** [comment]
我们是双击顿号会出现“/”而非“\”，正如题主提出的`['、、|', '/|']`这条替换策略的小错误

**Comment by Ploter4815** [comment]
同样想提这个issue，easytyping双击顿号`、`之后转换的是斜杠`/`而不是反斜杠`\` @Yaozhuwa

**Comment by Yaozhuwa** [comment]
这段时间比较忙，没空更新。

今天更新了 v5.1.9，将连续顿号转`/`的设定从默认的连续全角转半角功能中删除了。可以通过自定义规则来实现连续顿号转反斜杠。

**Comment by mkdir700** [comment]
> 这段时间比较忙，没空更新。
> 
> 今天更新了 v5.1.9，将连续顿号转`/`的设定从默认的连续全角转半角功能中删除了。可以通过自定义规则来实现连续顿号转反斜杠。

<img width="828" alt="image" src="https://user-images.githubusercontent.com/56359329/220800844-2a582627-c5e1-4eb4-b3e7-c72522d2621d.png">

Nice!!!
