### ISSUE TITLE
选中文本时的编辑增强是否能支持 Vim 的 Visual 模式

### ISSUE THREAD

**Issue by Xiang929** [Yaozhuwa/easy-typing-obsidian#128]
如题, 目前 vim 模式下 v 选中的文本目前不能使用编辑增强, 想问下这个是否能支持

**Comment by mkdir700** [comment]
假设在 visual 状态下，使用 `$`，期望为所选的文本前后增加 `$` 字符。但对于 vim 而言，`$` 操作的原意是将光标移动至行尾。

对于 vim 来说，`$` 操作还是比较常见和重要的，所以我不太清楚如何解决这个问题。

**Comment by mkdir700** [comment]
推荐使用 https://github.com/esm7/obsidian-vimrc-support#surround-text-with-surround 这个插件模拟 vim-surround 的操作。

**Comment by Xiang929** [comment]
> 

好的, 谢谢 我去看一下这个插件

**Comment by Xiang929** [comment]
> 推荐使用 https://github.com/esm7/obsidian-vimrc-support#surround-text-with-surround 这个插件模拟 vim-surround 的操作。
> 
> 以下是我的配置，供参考：
> 
> ```
> " semicolon as colon
> nmap ; :
> " Have j and k navigate visual lines rather than logical ones
> nmap j gj
> nmap k gk
> " I like using H and L for beginning/end of line
> map H ^
> map L $
> " Yank to system clipboard
> set clipboard=unnamed
> 
> " Go back and forward with Ctrl+O and Ctrl+I
> " (make sure to remove default Obsidian shortcuts for these to work)
> exmap back obcommand app:go-back
> nmap <C-o> :back
> exmap forward obcommand app:go-forward
> nmap <C-i> :forward
> 
> exmap surround_wiki surround [[ ]]
> exmap surround_double_quotes surround " "
> exmap surround_single_quotes surround ' '
> exmap surround_brackets surround ( )
> exmap surround_square_brackets surround [ ]
> exmap surround_curly_brackets surround { }
> exmap surround_code surround ` `
> exmap surround_latex surround $ $
> 
> " NOTE: must use 'map' and not 'nmap'
> map [[ :surround_wiki
> nunmap s
> vunmap s
> map s" :surround_double_quotes
> map s' :surround_single_quotes
> map sb :surround_brackets
> map s( :surround_brackets
> map s) :surround_brackets
> map s[ :surround_square_brackets
> map s[ :surround_square_brackets
> map s{ :surround_curly_brackets
> map s} :surround_curly_brackets
> map sc :surround_code
> map sl :surround_latex
> ```
> 
> 使用方法：
> 
> * 先按 v 进入 visual 模式，选中目标文本
> * 按 s 后接需要配对的字符，比如添加双引号就是：`s"`

好的 谢谢 我去看看这个插件
