### ISSUE TITLE
输入邮箱时自动产生空格，改正后还是会自动恢复

### ISSUE THREAD

**Issue by zhl111** [Yaozhuwa/easy-typing-obsidian#129]
请教如何避免这种情况？正则表达如何写？

**Comment by mkdir700** [comment]
是不是开启了 ”英文与数字之间添加空格“ 的选项

**Comment by Yaozhuwa** [comment]
需要根据邮箱的形式添加正则表达式来忽略邮箱输入的格式化发自我的 iPhone在 2023年2月16日，16:05，mkdir700 ***@***.***> 写道：﻿
是不是开启了 ”英文与数字之间添加空格“ 的选项

**Comment by Yaozhuwa** [comment]
默认的正则区块里面包含了
```
[a-zA-Z0-9_\-.]+@[a-zA-Z0-9_\-.]+|++
```
可以忽略一般的邮箱，可能你的邮箱地址不符合这个正则，你需要自己修改下

**Comment by Yaozhuwa** [comment]
都可以

**Comment by Yaozhuwa** [comment]
目前不行，你还是手动添加正则规则吧发自我的 iPhone在 2023年2月21日，10:23，阿哈吉 ***@***.***> 写道：﻿
那我以前增加了很多配置有没有可能在重新安装后保存或重新置入呢？
