### ISSUE TITLE
Remove/Add toggle for capitalization after ";"

### ISSUE THREAD

**Issue by Lulullia** [Yaozhuwa/easy-typing-obsidian#13]
I'd like to disable capitalization after the ";" punctuation.
Eg `not me; you` instead of `not me; You`.

It can be tiring to always hit Ctrl+Z, I'd be nice to have a toggle for this if you do not wish to remove it completely.

Thanks!

**Comment by Yaozhuwa** [comment]
Sorry, I think I had midsunderstood the use of ";" in English before. It's solved in new version: v3.3.3
