### ISSUE TITLE
在Linux端安装了插件之后，刚安装完之后测试是可以正常显示的，但是今天再次使用的时候就无法正确的显示出来，并尝试重新安装后也无法正确显示

### ISSUE THREAD

**Issue by qichenxiaoni** [Yaozhuwa/easy-typing-obsidian#130]

**Comment by qichenxiaoni** [comment]
这分别是我在Linux端和windows端的截图
![Linux](https://user-images.githubusercontent.com/111137928/220125940-6872e0af-af51-4c2a-a60f-72786bf78468.PNG)
![Windows](https://user-images.githubusercontent.com/111137928/220126124-a1ec1221-52af-40aa-96f5-2cf65c970e28.PNG)
![Windows端](https://user-images.githubusercontent.com/111137928/220126238-d3aa2163-1614-476c-8bf8-5af53ec2bfcd.PNG)
![Linux端](https://user-images.githubusercontent.com/111137928/220126348-3874354d-fbed-45ae-8f22-b884aac60b6e.PNG)

**Comment by Yaozhuwa** [comment]
我还是不明白你说的不能正常显示是什么意思，意思是插件无法加载？

**Comment by qichenxiaoni** [comment]
不是的，是插件安装之后按理来说在页面顶部会出现菜单栏，但是在我的Linux端中并没有这个菜单栏，但插件的部分功能又是生效的，例如当我输入两个￥￥的时候可以变成两个$$。

**Comment by Yaozhuwa** [comment]
顶部菜单栏不是本插件的功能，那个是 editing toolbar插件

**Comment by qichenxiaoni** [comment]
> 顶部菜单栏不是本插件的功能，那个是 edit toolbar插件
真的很抱歉，由于我一直认为菜单栏的功能也是您的插件的效果，所以闹出了这一乌龙事件，真的非常的对不起，耽误了您的时间，同时也很感谢您最后为我指明了插件，真的十分感谢。

**Comment by qichenxiaoni** [comment]
最后祝您生活愉快！
