### ISSUE TITLE
书名号《》的问题

### ISSUE THREAD

**Issue by queyuewutong** [Yaozhuwa/easy-typing-obsidian#131]
您好，我在obsidian用rime输入法的时候，遇到了以下问题，当我输入《》的时候，智能匹配以后，总会在《》中间多一个空格，而且光标不会跳到中间，请问您遇到过这种问题吗

**Comment by Yaozhuwa** [comment]
我没有用过这个输入法。但是你可以尝试关闭输入法自身的符号配对等会影响输入的功能试一下。一般来说，输入法只要是直接输入《能上屏的，都不会有问题。 

此外，rime 输入法的确会有一些问题，也有别人提过bug，但是从插件调试信息里面看不出问题。之后我有空会下载这个输入法试试，主要这个输入法配置有点麻烦，给我劝退了。。

**Comment by queyuewutong** [comment]
> 我没有用过这个输入法。但是你可以尝试关闭输入法自身的符号配对等会影响输入的功能试一下。一般来说，输入法只要是直接输入《能上屏的，都不会有问题。
> 
> 此外，rime 输入法的确会有一些问题，也有别人提过bug，但是从插件调试信息里面看不出问题。之后我有空会下载这个输入法试试，主要这个输入法配置有点麻烦，给我劝退了。。



> 我没有用过这个输入法。但是你可以尝试关闭输入法自身的符号配对等会影响输入的功能试一下。一般来说，输入法只要是直接输入《能上屏的，都不会有问题。
> 
> 此外，rime 输入法的确会有一些问题，也有别人提过bug，但是从插件调试信息里面看不出问题。之后我有空会下载这个输入法试试，主要这个输入法配置有点麻烦，给我劝退了。。

谢谢您的回复

**Comment by Yaozhuwa** [comment]
我目前在MAC上野使用了RIME输入法，还是没法复现你的问题~

PS: 我使用的配置是 https://github.com/iDvel/rime-ice
