### ISSUE TITLE
在中文输入法时选中文本按¥无法自动添加$$

### ISSUE THREAD

**Issue by PenguinDang** [Yaozhuwa/easy-typing-obsidian#134]
Editing enhancements when text is selected模式中，在中文输入法时选中文本按¥（shift+4）无法自动在文本两侧添加$$，而是直接用¥替换掉了选中的文本；但是使用英文输入法时就可以在两侧添加$$

**Comment by Yaozhuwa** [comment]
这个和输入法有关，换个输入法或者设置可能就好了。
