### ISSUE TITLE
请问如何设定一些中英文的固定名词而不加空格

### ISSUE THREAD

**Issue by iczrac** [Yaozhuwa/easy-typing-obsidian#139]
如“K线”，“MA13”，“2B法则”等

**Comment by doit132** [comment]
> 如 “K 线”，“MA13”，“2B 法则” 等

直接在正则里面添加
2B法则|--
K线|--
MA13|--

**Comment by xiaofeiwa** [comment]
> 
尝试这个方法没有用，手动输入2B法则，只会分笔匹配到2 B 法则，并自动加入空格

**Comment by Yaozhuwa** [comment]
> 如“K线”，“MA13”，“2B法则”等

见 https://github.com/Yaozhuwa/easy-typing-obsidian/issues/140#issuecomment-1675757503
