### ISSUE TITLE
Better support with espanso expander and Dataview inline fields

### ISSUE THREAD

**Issue by wenlzhang** [Yaozhuwa/easy-typing-obsidian#14]
When inserting texts with espanso, e.g., `:dz` should be expanded to `202108191440`. However, when this plugin is enabled, the text would be expanded into `: 202108191440`, with an extra `:` and space.

For Dataview inline fields, they can be defined as something like `Rating:: 5`. However, with this plugin enabled, the field would become `Rating :: 5`, with an extra space.

Would it be possible to improve these two use cases?

**Comment by Yaozhuwa** [comment]
>When inserting texts with espanso, e.g., :dz should be expanded to 202108191440. However, when this plugin is enabled, the text would be expanded into : 202108191440, with an extra : and space.

You can add a regular expression to solve it. Open the plugin setting pane and add `:\w+` as below.
![image](https://user-images.githubusercontent.com/28787183/135264224-9e55c92c-a885-4260-902b-ca35f64c681d.png)

>For Dataview inline fields, they can be defined as something like Rating:: 5. However, with this plugin enabled, the field would become Rating :: 5, with an extra space.

![image](https://user-images.githubusercontent.com/28787183/135263840-a2f8844c-04eb-4fc0-9ec2-da8989da5faa.png)
