### ISSUE TITLE
蹲一个ignore功能

### ISSUE THREAD

**Issue by PupupupuTong** [Yaozhuwa/easy-typing-obsidian#141]
作者你好~非常感谢您开发了这么好的插件，贪心不足的人这里小小得寸进尺一下：请问有没有可能加入一个ignore项？因为我把一些账号信息存在了ob里，这类文字输入时easytyping反倒是个阻碍而非助力，每次都逐字修改或者开关一次插件有点点麻烦。再次感谢！（B站那个也是我，如果这边看到就不用回了）

**Comment by Yaozhuwa** [comment]
设置里面有啊，可以忽略文件夹
