### ISSUE TITLE
自定义编辑转换规则，如何定义中文｜，为英文|

### ISSUE THREAD

**Issue by xietiancn** [Yaozhuwa/easy-typing-obsidian#145]
自己的平板只适配谷歌拼音输入法，奈何这个输入法中文状态下输入的所有符号都是中文的，其它的都可以定义就是｜无法定义，因为英文|是代表光标，我按照规则，将''｜|''定义为''||''，会变成输出|，但是光标在|的前面。如果将''｜|''定义为''|''，就是什么都没有输出，请问如何操作呢？
以及，现有的自定义编辑规则是全局生效的，是否考虑，增加一个规则，就是只在$$中编辑生效，这样输入数学公式时，才会生效规则，正常输入文本时不生效。

**Comment by doit132** [comment]
> 自己的平板只适配谷歌拼音输入法，奈何这个输入法中文状态下输入的所有符号都是中文的，其它的都可以定义就是｜无法定义，因为英文 | 是代表光标，我按照规则，将 ''｜|'' 定义为 ''||''，会变成输出 |，但是光标在 | 的前面。如果将 ''｜|'' 定义为 ''|''，就是什么都没有输出，请问如何操作呢？ 以及，现有的自定义编辑规则是全局生效的，是否考虑，增加一个规则，就是只在 $$ 中编辑生效，这样输入数学公式时，才会生效规则，正常输入文本时不生效。

另一个插件 linter 可以实现你想要的功能

**Comment by kingwingfly** [comment]
#133

**Comment by Yaozhuwa** [comment]
v5.1.11版本对连续全角转半角的功能：增加了连续输入两个全角竖线转半角竖线的规则 ~
