### ISSUE TITLE
FR: 针对特定文件，不开启自动格式化

### ISSUE THREAD

**Issue by lifesign** [Yaozhuwa/easy-typing-obsidian#149]
ob 中有一些插件的配置文件，可能有特定的格式要求
希望可以增加类似 ignore 的能力，可以让特定的文件不进行自动格式化

**Comment by Yaozhuwa** [comment]
> 希望可以增加类似 ignore 的能力，可以让特定的文件不进行自动格式化

见插件设置 <img width="946" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/638924eb-607d-4898-9f4e-9f9b84f08316">

**Comment by lifesign** [comment]
awesome~
