### ISSUE TITLE
\转义符号对#不生效，自动识别为标签

### ISSUE THREAD

**Issue by Lin-Youth** [Yaozhuwa/easy-typing-obsidian#150]
发现开启EasyTyping插件后，Obsidian里的转义符号`\` 对`#`不生效，依然识别为标签，如下图：

<img width="100" alt="image" src="https://user-images.githubusercontent.com/26051323/236610275-78717e7b-f8fb-4391-ae41-3ebe467aaaf6.png">

更新：目前自己的解决方法是，在插件设置的“自定义正则区块”，去掉最后一行`(?<!#)#[\u4e00-\u9fa5\w\/]+|++`

**Comment by Yaozhuwa** [comment]
正解
