### ISSUE TITLE
引用块内的代码块无法被识别，从而导致错误地格式化代码块的内容

### ISSUE THREAD

**Issue by varg1714** [Yaozhuwa/easy-typing-obsidian#151]
我在callout标注块内插入了代码块，代码块以```包裹，但是代码块中的内容会被自动格式化。即使我尝试使用正则表达式过滤也不行，因为代码块是多行的！
以下是我使用的正则表达式：```[.\s\S\t\w\r]*?```|--

**Comment by Yaozhuwa** [comment]
的确，我调用的语法解析器对于在引用块中的代码块不能正确地识别。

多行正则的实现更为复杂，目前我没有想到好的实现方式。

**Comment by HoBeedzc** [comment]
可否通过设置状态变量的方式在语法解析器中判断是否处于代码块内，从而决定是否进行忽略。

我自己开发的 obsidian 插件在近期也遇到了类似的问题 HoBeedzc/obsidian-header-enhancer-plugin#16 ，目前通过上述方式可以解决（pr HoBeedzc/obsidian-header-enhancer-plugin#17），希望可以为这个 bug 的解决提供新思路。如果这个想法可行的话，我可以修复此 bug 并提交 pr。

**Comment by Yaozhuwa** [comment]
> 可否通过设置状态变量的方式在语法解析器中判断是否处于代码块内，从而决定是否进行忽略。
> 我自己开发的 obsidian 插件在近期也遇到了类似的问题 https://github.com/HoBeedzc/obsidian-header-enhancer-plugin/issues/16 ，目前通过上述方式可以解决（pr https://github.com/HoBeedzc/obsidian-header-enhancer-plugin/pull/17），希望可以为这个 bug 的解决提供新思路。如果这个想法可行的话，我可以修复此 bug 并提交 pr。

感谢您的思路，我在 v5.1.12 中修复了这个问题
