### ISSUE TITLE
自动格式化排除复制粘贴

### ISSUE THREAD

**Issue by Freddd13** [Yaozhuwa/easy-typing-obsidian#155]
感谢作者的付出，插件十分好用。在使用过程中，我注意到AutoFormatting部分，如英文首字母大写等格式化，可以选择仅在输入时生效。但有的时候我会粘贴代码或是一些密钥之类的东西，ctrl+V进去一样会格式化。能否像增加设置paste可以不生效。顺便希望有手动立即执行autoformatting的功能。（类似vscode里面format）

**Comment by Yaozhuwa** [comment]
> ctrl+V进去一样会格式化。能否像增加设置paste可以不生效。 

这个可以有，之后会添加一个开关
> 顺便希望有手动立即执行autoformatting的功能。（类似vscode里面format）

插件带的命令有手动执行的功能，你找一下就知道了

**Comment by Yaozhuwa** [comment]
新版本v5.1.10 增加了命令：无格式化粘贴，默认快捷键 Ctrl(CMD)+Shift+V，在粘贴的时候不会触发自动格式化文本。

**Comment by Freddd13** [comment]
感谢作者！ 昨天使用又有个想法，能不能像word那样，有一个触发自动格式化（修正）后，按退格再输入就不会再格式化的机制？比如我写日记时打了三个句号。。。发现输入变成了.

**Comment by Yaozhuwa** [comment]
Ctrl+Z 可以撤销
