### ISSUE TITLE
[bug] 在canvas卡片里面粘贴双链,会出现重复的情况

### ISSUE THREAD

**Issue by doit132** [Yaozhuwa/easy-typing-obsidian#157]
# 动画演示

![动画-tuya](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/117004316/4b40f11d-1ebe-452d-b719-d1164141bdd6)

# 演示环境

- obsidian 沙盒库
- v1.3.5

# 注意

- 演示动画中使用了鼠标手势, 实际使用ctrl+v也会造成相同的结果

**Comment by Yaozhuwa** [comment]
可以把你粘贴的内容发上来我试一下吗

**Comment by doit132** [comment]
> 可以把你粘贴的内容发上来我试一下吗

和粘贴内容没什么关系, 复制下图左边卡片里面的文档, 然后到右边粘贴也会出现

![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/117004316/f0cc7058-620a-4ca7-a1e7-e0da89398ab8)

# 动画演示

![动画-tuya](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/117004316/a1a61a9e-dc1c-47b5-8ae1-a437e561e44f)

**Comment by Yaozhuwa** [comment]
可以提供下系统、ob版本及插件版本信息吗，我在Mac上无法复现

**Comment by doit132** [comment]
> 可以提供下系统、ob 版本及插件版本信息吗，我在 Mac 上无法复现

- obsidian版本v1.3.5
- 插件版本v5.1.9
- windows11-22H2

**Comment by Yaozhuwa** [comment]
OK，可以复现~

**Comment by Yaozhuwa** [comment]
新版本v5.1.10 已修复该问题~
