### ISSUE TITLE
如何将现有的title（不带Markdown###标题格式的） 转换成带###的

### ISSUE THREAD

**Issue by MrJo621** [Yaozhuwa/easy-typing-obsidian#158]
例如：
第 5 章 Kafka 监控
5.1 Kafka Eagle
5.1.1 修改 kafka 启动命令

转换成
# 第 5 章 Kafka 监控
### 5.1.1 修改 kafka 启动命令

**Comment by doit132** [comment]
可以通过正则替换, 我并没有使用这个插件来完成这个功能, 你可以考虑使用 linter 插件, 它有一个正则替换的功能

**Comment by lanx214** [comment]
可以用 https://github.com/obsidian-canzi/Enhanced-editing 这个插件，ctrl+数字键n 快捷变为n级标题。
