### ISSUE TITLE
[Feature Request] Ignore Urls for automatic Capitalizing first Letter

### ISSUE THREAD

**Issue by Obadiahcruz** [Yaozhuwa/easy-typing-obsidian#16]
Amazing Plugin! i just have the issue of the urls being automatically capitalized. Do you have a way to fix this?

For example: www.google.com

Becomes: Www.Google.Com

**Comment by Yaozhuwa** [comment]
It can be solved by using the Regular Expressions. Open the setting pane of this plugin, add a regexp as below:
![image](https://user-images.githubusercontent.com/28787183/135207584-ca4b01af-b049-4b1f-b9e6-5033bde8ed56.png)
```
www\.\S+\.com
```

**Comment by Yaozhuwa** [comment]
It should be solved in the new release of 3.3.4.

**Comment by Obadiahcruz** [comment]
THANK YOU!!

**Comment by Obadiahcruz** [comment]
i found another issue with the same problem.
this happens if it is the first word in a sentence. i tend to put urls at the bottom as the first word. any fix? 

<img width="190" alt="Screen Shot 2021-09-29 at 12 48 11 PM" src="https://user-images.githubusercontent.com/22825246/135338350-d6356ce8-f065-4e9f-9c73-f375dd750dd2.png">

**Comment by Obadiahcruz** [comment]
thank you so much!

**Comment by Yaozhuwa** [comment]
@Obadiahcruz  EasyTyping 5.0 the auto captalize can be undone, it may solve your problem.
