### ISSUE TITLE
自定义规则生效异常五个字母的大小写替换

### ISSUE THREAD

**Issue by latexstudio** [Yaozhuwa/easy-typing-obsidian#160]
我自己定义了一个规则 latex| 转换为 LaTeX|，但是转换之后 后面的字符都是对的，第一个字母l没有转换为大写字母，这个序列是特殊名称。不知道是我定义的问题嘛？三个字母是正常的，五个字母的就不行了。
![5973aee1-20d4-49c4-a825-b99d5f1c7b5f](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/2612876/b781d118-1ec5-4127-8dce-4af28f62f860)

**Comment by Yaozhuwa** [comment]
自定义规则是由优先级的，你的 `tex|` → `Tex|`规则在 `latex|`→`Latex`规则前，会先生效，然后后续的规则就无法触发了。你可以先删掉`tex|` → `Tex|`规则，再添加，就没有问题了
