### ISSUE TITLE
自定义 字母数字组合 专有名词不添加空格

### ISSUE THREAD

**Issue by xiaofeiwa** [Yaozhuwa/easy-typing-obsidian#161]
请问如何设置 CYP开头的专有名词中不添加空格？  如CYP2C19 ，CYP3A4 ，CYP1A2。

**Comment by ZeekoZhu** [comment]
添加这条自定义规则即可 `CYP[a-zA-Z0-9]+|++`

**Comment by xiaofeiwa** [comment]
非常感谢，亲测有效。

> 添加这条自定义规则即可 `CYP[a-zA-Z0-9]+|++`

**Comment by ZeekoZhu** [comment]
其实可以把自定义规则的说明跟内置的样例发送给 GPT，然后跟 GPT 描述自己的自定义需求，GPT 就可以写出正确规则

**Comment by Yaozhuwa** [comment]
> 添加这条自定义规则即可 `CYP[a-zA-Z0-9]+|++`

正解 👍  ，自定义正则最初设计就是用来解决这种问题的
