### ISSUE TITLE
自定义正则无法忽略对"$\qquad$"的前后空格的格式化

### ISSUE THREAD

**Issue by kdqiu** [Yaozhuwa/easy-typing-obsidian#162]
easytyping插件对我帮助太大了，谢谢。我最近想利用自定义正则来匹配行内公式，以此消除特定表达式前后的空格，比如$\qquad$，但我发现无法成功实现，想请问是什么原因呢？

**Comment by Yaozhuwa** [comment]
行内公式空格设置的优先级高于用户自定义正则表达式
<img width="768" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/3ae42038-1ee8-4663-8023-e49b55f0ad7e">

**Comment by Yaozhuwa** [comment]
v5.1.16 解决了这个问题~
