### ISSUE TITLE
在中文和英文之间空格功能，导致自动输入输入法第一个字符

### ISSUE THREAD

**Issue by GraceZhuuu** [Yaozhuwa/easy-typing-obsidian#163]
操作系统：Ubuntu 20 LTS
在我输入英文后，利用输入法继续输入中文，在按下第二个字母时，第一个字母的候选字已经被输出到了屏幕上。
比如我先输入“apple”，再输入“苹果”，导致的结果就是这样
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/124070462/6e7e665b-5ccd-4bb6-ace7-9e8968b22e91)
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/124070462/f2bf698d-320d-4bf5-ae04-9faa2e2a519a)

![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/124070462/4810b294-4559-40d2-8264-840e5eb91a53)

**Comment by dj-universe** [comment]
我也遇见了类似的问题，（win10）英文输入转中文输入后，自动插入空格，会将输入的中文内容输入两遍
例如：
输入“Quickadd 插件”
会变成：“Quickadd 插件插件”
我自己加上空格就不会出现这种情况了

**Comment by Yaozhuwa** [comment]
v5.2.0 版本支持了微软输入法，建议更新尝试~

**Comment by GraceZhuuu** [comment]
> v5.2.0 版本支持了微软输入法，建议更新尝试~

更新后 ubuntu 直接不能输入中文了（苦笑

**Comment by Yaozhuwa** [comment]
> > v5.2.0 版本支持了微软输入法，建议更新尝试~
> 
> 更新后 ubuntu 直接不能输入中文了（苦笑

哈哈哈，这也太搞了，由于不同平台不同输入法的特性不同，要全部适配不是一次性能做到的。

你可以重新下载上一个版本的，然后打开插件设置中的debug开关，打开 ctrl +shift +i  obsidian 控制台，然后在obsidian编辑页面输入复现你的问题，把控制台的输出发我看一下，可能能找到问题并解决。 参考 #196 ，通过用户反馈我这边才能解决这个微软输入法的问题~

**Comment by Yaozhuwa** [comment]
v5.2.1 版本为支持旧版微软输入法的功能添加了开关，默认为关闭。更新能解决无法输入中文的问题。

但是没有调试信息的话，我也无法帮助你解决 Ubuntu 下的默认输入法的问题.

**Comment by Yaozhuwa** [comment]
V5.3.0 版本可能能解决这个，可以下载尝试下~
