### ISSUE TITLE
无法实现对定义了文本样式的自动格式化

### ISSUE THREAD

**Issue by LDzzZ-1** [Yaozhuwa/easy-typing-obsidian#168]
例如我想对定义了文本样式的前后软空格
`<font color="#4bacc6">ABC</font>`
`<span style="background:rgba(240, 200, 0, 0.2)">内容</span>`
`<span style="background:rgba(240, 200, 0, 0.2)"><font color="#f79646">内容</font></span>`
我添加了(<font.*\>).*(<\/font>)|==
但因为`<.*?>|-- 是用来识别双尖括号块的`并没有生效
我该如何实现

**Comment by jiyee** [comment]
你这个正则不对吧，或者具体描述一下你的问题。

**Comment by LDzzZ-1** [comment]
> 你这个正则不对吧，或者具体描述一下你的问题。
文本样式前后自动添加一个空格
如下图
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/127015671/e0e78c08-7f21-4db9-8ca1-4431ae726442)

**Comment by Yaozhuwa** [comment]
> > 你这个正则不对吧，或者具体描述一下你的问题。
> > 文本样式前后自动添加一个空格
> > 如下图
> > ![image](https://private-user-images.githubusercontent.com/127015671/295160932-e0e78c08-7f21-4db9-8ca1-4431ae726442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMDE2MDksIm5iZiI6MTcxMDAwMTMwOSwicGF0aCI6Ii8xMjcwMTU2NzEvMjk1MTYwOTMyLWUwZTc4YzA4LTdmMjEtNGRiOS04Y2ExLTQ0MzFhZTcyNjQ0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQxNjIxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzZkM2M0M2MyYjJmNWUxNzgxNDgwMzM2MDZhYzgxNDk4ZDQxNDNiMzlkYjYzNTg0YjM4ZTViODg3OWQyZTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GLeZNKlNpiJONhE84yzc8N06Ua0-480brDH2Us-3x-c)

我举个例子，对于 `<span style="background:rgba(240, 200, 0, 0.2)">内容</span>` 这样的，可以用如下正则（可以自己问chatGPT）
```
<span style="background:rgba\(240, 200, 0, 0\.2\)">(.*?)<\/span>|==
```
此外，如果正则表达式的匹配是有优先级的，按条目顺序来，如果你觉得`<.*?>|-- ` 会干扰你的正则，只需要把你自己的正则放到其之前即可~
