### ISSUE TITLE
有两个规则不生效，单引号中文转成英文的，还有中文下按三下分号变成三个中文分号

### ISSUE THREAD

**Issue by calmwaves111** [Yaozhuwa/easy-typing-obsidian#169]
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/56907077/d8da6c65-58df-4b05-a810-98ad9eec9154)
以前是生效的，从某一天开始突然不生效了

**Comment by Yaozhuwa** [comment]
可以详细点吗，请描述本插件的设置情况，然后输入如何，输出如何？

**Comment by calmwaves111** [comment]
单引号从全角转半角，这个应该是默认功能，中文输入法下，我按一下引号键（就L键右边的右边的那个键），会输入一对中文单引号，`‘’`，光标在引号中间，然后我再按一下引号键，它没有变成英文的一对单引号；但是我如果中文输入法下按下两次【shift +引号键】（也就是输入双引号），它会自动转英文的一对双引号，并且光标在中间

第二个问题，关于自定义的转换规则，我自定义了一个规则，`;；|`转为`；；；|`
我希望实现的效果是：我按下第一次分号键（也就是L右边的那个键），会输入一个中文分号，再按一次，会变成英文分号，再按下一次，会变成三个中文分号，但是这个第三次按下并没有变成`；；；`，还是`;；`
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/56907077/dcfb6f83-5ec6-46c0-900e-028169559eab)

而我以类似的办法配置了感叹号，它就能正确转换，`!！|`转为`！！！|`
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/56907077/9f9c877e-6b6c-420f-b323-2e1817d49d87)

**Comment by Yaozhuwa** [comment]
> 单引号从全角转半角，这个应该是默认功能，中文输入法下，我按一下引号键（就L键右边的右边的那个键），会输入一对中文单引号，‘’，光标在引号中间，然后我再按一下引号键，它没有变成英文的一对单引号；但是我如果中文输入法下按下两次【shift +引号键】（也就是输入双引号），它会自动转英文的一对双引号，并且光标在中间

单引号的全角转半角的确没有用，我已经找到问题
> 第二个问题，关于自定义的转换规则，我自定义了一个规则，;；|转为；；；|
我希望实现的效果是：我按下第一次分号键（也就是L右边的那个键），会输入一个中文分号，再按一次，会变成英文分号，再按下一次，会变成三个中文分号，但是这个第三次按下并没有变成；；；，还是;；

对于这个问题，我这边规则是可以正常工作的，无法复现你的问题，尝试复现如下：
![iShot_2023-12-02_18 13 38](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/37da0a43-5739-4f78-b050-d4cb6b2bdf7c)

如果你的插件已更新最新版本并且还是有这样的问题，可以打开本插件设置中的debug开关，然后 ctrl+shift+i (CMD+Option+I)  调出obsidian的控制台，然后在Obsidian编辑器中复现你的问题，截图或者拷贝此时控制台的输出（录屏也可），我也许能找到问题所在~

**Comment by calmwaves111** [comment]
感谢大大的修复，现在这两个问题已经解决了
另外再次感谢您开发此插件，对于广大中文使用者是极大的福音，也是我一直推荐的必装插件
