### ISSUE TITLE
feature request 中文¥转为公式标记$，》转为引用标记>

### ISSUE THREAD

**Issue by lethefrost** [Yaozhuwa/easy-typing-obsidian#17]
是不是能把`¥`自动转为`$`，而且选中一段文本时输入`¥`，也能像已经实现的功能，比如

- `【【`变成`[[]]`
- `·`变成\`

一样，变成`$`把文本包围住呢？

再次感谢，这个插件真的帮到了我很多，在每天的日常使用中存在感超高。

**Comment by lethefrost** [comment]
> > 是不是能把¥自动转为$，而且选中一段文本时输入¥，也能像已经实现的功能
> 
> 这个功能是已经有的呀。

啊，谢谢……可是它不起作用诶😳是不是出什么问题了？您那边`¥`和`》`现在还可以正常自动转换吗？
参考版本：easy typing 3.3.4，Obsidian 0.12.17，macOS 11.6

**Comment by Yaozhuwa** [comment]
￥`￥`, `¥`

**Comment by Yaozhuwa** [comment]
我发现，可能是￥在windows和MacOS上打出来的是两个不同的字符，我打出来的是`￥`, 而你这里打出来的是`¥`，我已经更新了release 3.3.5，尝试解决这个问题，你可以更新看看问题还在不在。

**Comment by lethefrost** [comment]
> > 》转为引用标记>
> 
> 该功能在新的release v3.4.0中更新了。[easy-typing 3.4.0](https://github.com/Yaozhuwa/easy-typing-obsidian/releases/tag/3.4.0)

真不错！感谢❤️
