### ISSUE TITLE
编辑增强在苹果移动端上失效

### ISSUE THREAD

**Issue by Saturnus001** [Yaozhuwa/easy-typing-obsidian#172]
iPad OS 16上使用默认输入法无法正常使用编辑增强功能，如¥¥无法变为$$，更换为Gboard和微信输入法后也不行，使用苹果的妙控键盘该功能也无法生效。在iphone上尝试也未成功

**Comment by Yaozhuwa** [comment]
v5.1.11版本应该修复该问题了~
