### ISSUE TITLE
希望自定义正则表达式支持注释，另外匹配标签的表达式有遗漏

### ISSUE THREAD

**Issue by XDcedar** [Yaozhuwa/easy-typing-obsidian#173]
正则表达式本身很难辨认含义，希望可以支持注释功能，不然时间一长自己都忘了自己写的是什么了。

另外默认匹配标签的正则表达式漏了匹配`-`
原表达式：`(?<!#)#[\u4e00-\u9fa5\w\/]+|++`
修改之后：`(?<!#)#[\u4e00-\u9fa5\w\/-]+|++`

**Comment by Yaozhuwa** [comment]
v5.5.0 版本自定义正则以 `//` 开头的行会被视作注释~
