### ISSUE TITLE
数字后面输入中文句号会自动变为英文句号

### ISSUE THREAD

**Issue by sjhsbhqf** [Yaozhuwa/easy-typing-obsidian#174]
数字后面输入中文句号会自动变为英文句号。

能提供一个撤销这种自动格式的选项吗

**Comment by Yaozhuwa** [comment]
这是你输入法自带的吧

**Comment by sjhsbhqf** [comment]
并不是，我在github评论的编辑器。

首先输入一个123，然后再再123后面打句号，可以连续打句号。

比如123。。。。。。。。。。。点几次就是几个句号

**Comment by Yaozhuwa** [comment]
<img width="781" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/8bfffa34-83fd-4824-bc97-8142495becdf">
你可能开启了这个连续全角转半角的功能，会导致连续的两个。转化为一个.

**Comment by Yaozhuwa** [comment]
时隔这么久还是无法复现你的问题，关闭了
