### ISSUE TITLE
formatArticle method fail because of hooking viewUpdate

### ISSUE THREAD

**Issue by eventlOwOp** [Yaozhuwa/easy-typing-obsidian#175]
when putting cursor anywhere except end of the file, formatting the article using hotkey "ctrl-shift-s" will call `formatArticle` method.
then after `editor.setValue` is called in `formatArticle`, the `viewUpdate` event will be triggered, resulting in `RangeError: Invalid position -1 in document of length 196`.
we can fix it by adding a property in the class to tell the `viewUpdatePlugin` whether the event is triggered by `formatArticle`, and set the property to true before calling `editor.setValue` and to false after calling `editor.setCursor`

**Comment by eventlOwOp** [comment]
草，忘了是中国人写的了，一看issue区全是中文。
就是光标在非文章末尾的时候用ctrl-shift-s来格式化全文，会出现`RangeError: Invalid position -1 in document of length 196.`
因为在格式化全文时调用了异步方法`editor.setValue`，然后在这obsidian不把事件监听的调用放在下一个microtask/macrotask，直接调用，所以导致调用viewUpdatePlugin的时候出错。
解决方案就是在`editor.setValue`前把`this.onFormatArticle`设置成`true`，然后在`editor.setCursor`后把`this.onFormatArticle`设置成`false`（我试了下确实能用，这俩函数不是异步的）在`viewUpdatePlugin`判断它的值，是`1`就返回

**Comment by Yaozhuwa** [comment]
感谢帮忙解决bug~已合并
