### ISSUE TITLE
重复输入的问题

### ISSUE THREAD

**Issue by hyang2508** [Yaozhuwa/easy-typing-obsidian#177]
我有两台笔记本电脑，其中一台功能一切正常，另一台型号是华为matebook。在打字的时候，例如，输入：abcdef测试；屏幕上显示的是：abcdef 测试测试。也就是说在英文和中文中间增加空格的同时，后面跟着的中文会重复出现2次，不太清楚这个bug是什么原因呢？

**Comment by Benn314** [comment]
我也有这个错误，但在设置没有找到相应的配置

**Comment by ILOT-code** [comment]
对，当我输入了标点，然后使用输入法输入一个词语的时候，这个词语会被重复。但输入的如果是单个字，就不会发生这种错误。

**Comment by Benn314** [comment]
发现是win10自带输入法不兼容的问题，后面我换了百度输入法便不会了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: EnweiTong ***@***.***&gt;
发送时间: 2023年10月24日 21:40
收件人: Yaozhuwa/easy-typing-obsidian ***@***.***&gt;
抄送: Ben ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Yaozhuwa/easy-typing-obsidian] 重复输入的问题 (Issue #177)

**Comment by SongLier** [comment]
我也遇到了这个问题，同样是用微软的输入法导致的，如果是新版的微软输入法就没有这个问题，在微软输入法的常规-最下方的兼容性关闭即可，不知道是不是空格输入太快之类导致的，如果可以的话希望能从插件方面解决吧

**Comment by Benn314** [comment]
Ben已收到您的邮件，我会尽快处理，谢谢，祝您生活愉快

**Comment by Benn314** [comment]
Ben已收到您的邮件，我会尽快处理，谢谢，祝您生活愉快
