### ISSUE TITLE
Markdown Link 的图片路径有英文括号时被格式化

### ISSUE THREAD

**Issue by SadSock** [Yaozhuwa/easy-typing-obsidian#178]
<img width="828" alt="图片" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/7643216/9825e5ee-e59e-4ea1-a8d6-75fbdff19b3b">

如何保证不被格式化？

**Comment by Yaozhuwa** [comment]
无法复现，请详细描述你的问题~

最好能附上文字版本的出问题的地方

**Comment by jiyee** [comment]
不是有中文的问题，而是 link 里有 ()，mdlink 的正则匹配里 `\!{0,2}\[[^\[\]]*?\]\([^\s\)\(\[\]\{\}']*\)` 不支持这种格式，看起来是 bug。

**Comment by yaoyhu** [comment]
深受此苦～
这里有个可直接复现的：
```
[Mt. Gox Hack](https://en.wikipedia.org/wiki/Mt._Gox#Withdrawal_suspension_and_fallout_(February_2014))
```

https://github.com/user-attachments/assets/98252bdb-0710-4b67-a0e0-29ad835800c5

**Comment by SnowParaselene** [comment]
同。这个问题导致我obsidian里的##插入标签没法流畅使用了。
做笔记的时候有的标题是有括号的，比如`getchar()`。自动格式化虽然能撤销，但是通过快捷键格式化全文的时候会把这类链接也格式化了，还要手动改，非常麻烦。
![image](https://github.com/user-attachments/assets/1c01b2eb-72e3-4ef2-8791-ce224529f8cd)
![image](https://github.com/user-attachments/assets/6487e703-e143-4e45-8b27-b4aa7a7e41b3)

**Comment by Yaozhuwa** [comment]
5.5.10 版本修复了这个问题
