### ISSUE TITLE
反馈一个英文和数字间的空格的问题

### ISSUE THREAD

**Issue by abcvav** [Yaozhuwa/easy-typing-obsidian#180]
关闭这个选项过后
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/47599849/f5a8f6f0-7fab-4887-b843-de4a7f411f12)

输入 `字母` `半角符号` `数字` 是没问题的，但是输入 `数字` `半角符号` `字母` 的时候，`数字`和`半角符号`中间就会被插入一个空格。
比如输入 `a.1.b`，`a.1` 中间没有空格，是正常的，但 `1.b` 的 `1` 和 `.b` 之间会被插入一个空格

**Comment by Yaozhuwa** [comment]
这里的情况和这个英文和数字间空格选项无关，而和文本和标点间空格选项有关。

如果你需要输入1.b这种类型且不希望空格，可以在自定义正则中添加
```
\d\.\w|--
```
