### ISSUE TITLE
更新后个人的一些规则用不了

### ISSUE THREAD

**Issue by SongLier** [Yaozhuwa/easy-typing-obsidian#181]
![展示](https://songlier-pic.oss-cn-wuhan-lr.aliyuncs.com/202312021543659.png)

**Comment by Yaozhuwa** [comment]
嗯，收到，这个是因为我在新版本增加了一条内置规则 
```
['``|', '`|`']
```
考虑到你有这样的需求，我会在下个版本去掉。你暂时可以使用以下的 main.js 文件替换本插件的 main.js （放到 `库目录/.obsidian/plugins/easy-typing-obsidian/` 文件夹下）来修复这个问题

https://musetransfer.com/s/wm1isweth 请点击链接获取《Easy-Typing 插件临时修复》, 有效期至12月9日

**Comment by SongLier** [comment]
好的，非常感谢！
可能这也只是我的个人需要，您添加的这条内置规则也很有道理，谢谢~
