### ISSUE TITLE
输入数学公式时输入法自动切换到英文

### ISSUE THREAD

**Issue by ivxoxvi** [Yaozhuwa/easy-typing-obsidian#182]
在需要频繁大量的输入数学公式时，每次打出$ $或$$ $$后都要切换为英文输入法才能够继续输入数学公式。

如果能够提供提供一个开关选项，开启后，在光标位于$ $或$$ $$中时会自动将输入法切换为英文输入法，光标移出时自动将输入法复原，将能节省大量的时间。

**Comment by Yaozhuwa** [comment]
与 #70 重复~
