### ISSUE TITLE
[bug]有时会出现多行字符

### ISSUE THREAD

**Issue by hhhllll888** [Yaozhuwa/easy-typing-obsidian#188]
![bug](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/64844802/229ca992-1e9b-466e-b919-d05327b4edd3)
看gif
我使用的是微软拼音输入法，使用的是双拼输入

**Comment by Yaozhuwa** [comment]
这个问题，很多人反馈了，都是用的微软输入法，我尝试过没法解决，要不还是换个输入法吧...

**Comment by hhhllll888** [comment]
> 这个问题，很多人反馈了，都是用的微软输入法，我尝试过没法解决，要不还是换个输入法吧...

已经换手心输入法了，主要是微软输入法加词库太难了，之后打算直接学小鹤音形就不打算用微软输入法了
