### ISSUE TITLE
新版表格编辑

### ISSUE THREAD

**Issue by Gavin-jy** [Yaozhuwa/easy-typing-obsidian#189]
在新版表格编辑的过程中出现了一些问题，例如中文，小写英文字母，大写英文字母同时需要输入的情况会直接退出表格编辑。

**Comment by fankun576678634** [comment]
我也遇到了，在obsidian v1.5.3 版本的新版表格中，输入中文后再输入大写英文或者数字，就会失去光标，而且后面会多出来一个字母

**Comment by YIRU69** [comment]
同样的问题

**Comment by Jokerchu** [comment]
俺也一样

**Comment by Yaozhuwa** [comment]
更新到v5.1.15，应该修复了（在MAC上开发测试的）
