### ISSUE TITLE
在使用拼音输入时出现的误空格的情况

### ISSUE THREAD

**Issue by BrutalOrianna** [Yaozhuwa/easy-typing-obsidian#19]
比如我想输入“宏观经济”
我在拼音中打出“hong'guan'jing'ji”
然后选中宏观
这就变成了“宏观jing'ji"
这一步的时候我一个词没打完，它已经识别出需要空格了：“宏观 jing'ji”
这个时候我再选中经济
就变成了”宏观 经济“
中间出现了一个空格
这是一个致命的问题...

**Comment by Yaozhuwa** [comment]
这个我在 windows和ubuntu下都没有这个问题。其实在之前我是有过这个问题，但是不知道是输入法改了还是软件改了，这个问题消失了。我当时为了解决这个问题对windows专门改代码适配了，还添加了一个中文间去空格的设置，现在还有。

对于苹果电脑，我没测试过，可能会有问题。方便的话你可以打开插件设置最后的debug，然后`ctrl+shift+I`打开控制台。

![image](https://user-images.githubusercontent.com/28787183/141921849-47511d8b-d667-4e69-9ed6-9198ca248e17.png)

然后在软件中输入出现问题的情况的文字，比如“宏观jing'ji"，然后将控制台的输出截图给我看下，我试试能不能解决
