### ISSUE TITLE
tag的格式化问题

### ISSUE THREAD

**Issue by YandLiu** [Yaozhuwa/easy-typing-obsidian#192]
比如`#GLP-1`总会变成`#GLP -1`
本来该是![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/26127104/4cde344f-fad2-4969-b5c3-5b88aa4fe50c)
却变成![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/26127104/880c6834-9cd4-46da-a187-eaf5bde73f26)
以下为我的设置，就算把最上面两个给关掉也还是有这个问题
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/26127104/1ffb2fb8-aca7-47f7-a0ad-26528b7893cd)

**Comment by Yaozhuwa** [comment]
<img width="789" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/e8317fe9-e6f2-4e49-b699-af9a3f00590a">
把图片上的那一行删掉就行
