### ISSUE TITLE
obsidian 文档引用也会被 format 导致引用失效

### ISSUE THREAD

**Issue by LuckyCurve** [Yaozhuwa/easy-typing-obsidian#194]
当想要引用文档当中的段落时候，会标注当前段落如 ^abc123，默认是不带空格的，但此时格式化会破坏这个内置的引用规则成 ^abc 123，在英文和数字中会出现空格，导致引用失效

**Comment by Yaozhuwa** [comment]
可以添加自定义正则:
```
\^[\d\w]+|==
```
