### ISSUE TITLE
单元格内，换行符右侧若为行内代码块，会存在空格

### ISSUE THREAD

**Issue by Charles47-wc** [Yaozhuwa/easy-typing-obsidian#195]
新版表格编辑模式下，若换行符 `<br>` 两侧均为行内代码块，则会在两侧自动添加空格，使得单元格内第2行首存在空格。
经测试，核心是右侧为代码块首部与 `<br>` 之间会自动生成空格。
![bug](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/72661596/3dad5cf6-1797-4c6a-a09c-afa16a2a9cf6)

**Comment by Yaozhuwa** [comment]
插件设置中添加一行自定义正则：
```
<br>|--
```
如图：
<img width="786" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/40a0501b-4d47-409d-888b-e3c19fbf5dac">

**Comment by Charles47-wc** [comment]
已尝试此解决方案，问题并未解决。（Obsidian 整体重启过，仍未起效）
![bug2](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/72661596/5cd0aaac-6517-4815-bffd-b603810bb14f)

**Comment by Yaozhuwa** [comment]
我知道了，这是我的问题，我尽快更新下个版本修复这个问题~

**Comment by Yaozhuwa** [comment]
v5.1.16 应该解决了这个问题，上面添加的正则也可以删掉了~

**Comment by Charles47-wc** [comment]
经测试，升级后问题已解决。
