### ISSUE TITLE
关于匹配优先级的问题

### ISSUE THREAD

**Issue by Moyf** [Yaozhuwa/easy-typing-obsidian#199]
假设我现在同时定义了 `a+` 和 `ca+` 的两个替换规则，
目前会优先响应 `a+`，后者就无效了。

有办法指定优先级或者匹配顺序，在满足 `ca+` 的情况下优先匹配它吗？

**Comment by Yaozhuwa** [comment]
先设置的优先级高，你可以先删除 `a+`， 将其再设置一次

**Comment by Moyf** [comment]
> 先设置的优先级高，你可以先删除 `a+`， 将其再设置一次

明白了，感谢！
