### ISSUE TITLE
中文输入法下输入【【能否实现在英文输入法下的效果，即[[cursor]]？

### ISSUE THREAD

**Issue by zzdcgg** [Yaozhuwa/easy-typing-obsidian#2]
如题。感谢！

**Comment by Benature** [comment]
先做了一个不尚理想的尝试，至少不会被`【`覆盖掉选中文本 #3

**Comment by zzdcgg** [comment]
感谢！

**Comment by Yaozhuwa** [comment]
可以，这个效果我今天晚点给加上去。

**Comment by zzdcgg** [comment]
感谢！

**Comment by Yaozhuwa** [comment]
女朋友昨晚出车祸了，这两天暂时没时间弄了。。

**Comment by zzdcgg** [comment]
这个不着急啦。先处理好自己的事要紧。

**Comment by zzdcgg** [comment]
刚试了下，还有个小问题：在中文模式下在选定文本上输入【【，会变成“[测试]【”，而非“[[测试]]”（截图如下）。能否调整下？感谢！

![image](https://user-images.githubusercontent.com/70086177/121278926-328cb100-c906-11eb-88e8-651723f0f636.png)

**Comment by Yaozhuwa** [comment]
我在自己电脑上测试是没问题的。关于这个问题能提供更详细的信息吗。

**Comment by Benature** [comment]
我升级后测试正常，没有问题

**Comment by zzdcgg** [comment]
已经升级到最新版本，重启之后再试了一下，还是一样的问题。我是用Mac试的，Obsidian用的是最新的v0.12.5（内部测试版），不知道还有哪方面的信息有用？

**Comment by Yaozhuwa** [comment]
你可以发一下你用的测试文本吗，然后说明一下如何复现这个问题。

下面是我测试的gif，可以看到输入法是中文的。
![testBug](https://user-images.githubusercontent.com/28787183/121283541-e5144200-c90d-11eb-9c25-b0359e0511bb.gif)

**Comment by zzdcgg** [comment]
Mac自带的中文输入法，试了几次都是这样。测试的MD请见附件。谢谢！

[测试.md](https://github.com/Yaozhuwa/easy-typing-obsidian/files/6620721/default.md)

**Comment by Yaozhuwa** [comment]
> Mac自带的中文输入法，试了几次都是这样。测试的MD请见附件。谢谢！
> 
> [测试.md](https://github.com/Yaozhuwa/easy-typing-obsidian/files/6620721/default.md)

我现在在外面，晚点试试你的文档。

我写的逻辑是这样的，在选中文本的情况下，按一次中文【，会变成`[选中的文本]`，之前选中的文本依然保持选中。
看你的描述应该是按一次中文【后，变成`[选中的文本]`，文本没有保持选中，光标定位到了最后。

我没有mac可以测试。方便的话，你可以打开本插件设置最后的debug开关,然后Ctrl+shift+i，打开obsidian的控制台，在右边找到console面板，然后再进行一次复现bug的操作。把控制台输出的内容发截个图看看，可能能找到问题。

**Comment by zzdcgg** [comment]
好的 我回到家发给你 感谢！

**Comment by zzdcgg** [comment]
控制台输出内容截图如下：
![1623220620808](https://user-images.githubusercontent.com/70086177/121305520-43521c80-c930-11eb-95f5-ef84030a21ad.jpg)

**Comment by Yaozhuwa** [comment]
我知道了，这个问题好解决的。我等下就更新一下

**Comment by zzdcgg** [comment]
辛苦啦！

**Comment by Yaozhuwa** [comment]
v3.1.9 尝试修复了下，你看看有没有效果

**Comment by zzdcgg** [comment]
没问题了，感谢！
