### ISSUE TITLE
编辑转换规则不生效

### ISSUE THREAD

**Issue by 363045841** [Yaozhuwa/easy-typing-obsidian#200]
！【】|   转换为  ![]|
输入时不会自动转换
![image.png](https://s2.loli.net/2024/02/28/9aSZAoKmqrRle4g.png)

**Comment by Yaozhuwa** [comment]
这是在目前插件其他规则生效产生的输入变化的时候，不会触发转换规则。

在你的情境下就是你输入时产生的触发的是【 符号的自动配对，所以此时并不能触发转换规则了。

这个问题我再考虑下，之后可能会进行修复~

**Comment by 363045841** [comment]
谢谢老板！

**Comment by Yaozhuwa** [comment]
经过考虑，还是决定维持目前的策略：其他规则生效产生的输入变化的时候，不会触发转换规则。 这样可以避免规则套娃递归调用导致的死循环最终导致 Obsidian 卡死。
