### ISSUE TITLE
Chinese Typing Fail and cannot display

### ISSUE THREAD

**Issue by ckdanny** [Yaozhuwa/easy-typing-obsidian#202]
Version 5.2.0
Mac 14.3.1 (23D60)

Once the plugins are turned off, it resumes normal.

![2024-03-03 15 04 14](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/11786201/04f6fc04-3b37-4857-b868-4dd5046db6d2)

**Comment by MasterSuen** [comment]
在安卓墨水屏平板上使用该插件，只要手写输入中文就输入不了，跟上面反馈的视频一样。手写输入英文没问题，键盘输入中英文也都没有问题。关掉插件就一切正常。

**Comment by luckyfatpig** [comment]
一样的问题

**Comment by HorizonRy** [comment]
Ubuntu22.04系统也有相同问题，输入法正常输入，但在编辑器中无预览显示，空格确认输出后也无中文字符，输入回车后正常显示英文字符

**Comment by Yaozhuwa** [comment]
抱歉哈，这应该是v5.2.0版本为了支持微软输入法而导致对其他输入法产生了冲突。如遇到类似问题，可以暂时可以使用5.1版本的。

我今天更新一下，为支持微软输入法的设置一个开关就好。

**Comment by Yaozhuwa** [comment]
由于支持旧版输入法可能会导致其他输入法冲突，故 v5.2.1 版本为支持旧版输入法的功能添加了开关，默认为关闭。更新后应该能解决问题

**Comment by HorizonRy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    谢谢您的回复！感谢开发！
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Ruiyang Zhang
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        03/10/2024 00:07
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [Yaozhuwa/easy-typing-obsidian] Chinese Typing Fail and cannot display (Issue #202)
        
      
    
  
  
由于支持旧版输入法可能会导致其他输入法冲突，故 v5.2.1 版本为支持旧版输入法的功能添加了开关，默认为关闭。更新后应该能解决问题

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
