### ISSUE TITLE
编写标签是添加`-`号会自动空格

### ISSUE THREAD

**Issue by Laels** [Yaozhuwa/easy-typing-obsidian#203]
能否改成输入标签的时候自动空格失效
![无标题视频——使用Clipchamp制作](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/105426329/4237a6ce-4d37-47d8-bb5e-e1949c98589a)

**Comment by Yaozhuwa** [comment]
在插件设置的自定义正则中，删除如下条目即可：
```
(?<!#)#[\u4e00-\u9fa5\w\/]+|++
```
