### ISSUE TITLE
关于英文字母I（i）的大小写问题

### ISSUE THREAD

**Issue by Mochasu123** [Yaozhuwa/easy-typing-obsidian#204]
能否增加当字母i单独出现时永远是大写的功能？

**Comment by Yaozhuwa** [comment]
这个可以通过设置自定义转换规则实现

**Comment by Yaozhuwa** [comment]
<img width="550" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/cda0b04a-73bb-4a2a-a1e2-bdbd6788c820">
