### ISSUE TITLE
希望仅在行首输入"TODO "时进行编辑转换，其他地方保持不变

### ISSUE THREAD

**Issue by HatsuneMK00** [Yaozhuwa/easy-typing-obsidian#205]
想实现一个Logseq里在行首输入TODO的时候，自动将整行内容转换为Task的功能；目前使用自定义编辑转换的功能，设置的规则为"TODO |" -> "- [ ] #task". 但是这样在行中也会进行编辑转换

期望是仅在行首输入"TODO |"才进行编辑转换，尝试了一下"^TODO |"但是似乎不行，想问下规则里是否支持正则表达式？
在预设的规则里有行首的"》"替换为">"的规则，所以我觉得应该可以实现，但是不知道怎么做

**Comment by Yaozhuwa** [comment]
TODO前加回车即可，不过这样目前不会在文档第一行生效，也差不多能用吧
<img width="559" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/97aaf65a-b65e-4dad-9109-b27ab13c12a7">

**Comment by menghuu** [comment]
不建议使用这个插件来使用，你如果按照 @Yaozhuwa 的方法来做，是可以完成这个工作的。

但是会有一个问题，比如你确实希望在行首直接写TODO这个字符串，那这就需要很奇怪的手法来绕过这个字符串替换

Obsidian 本身就有个快捷键 `Ctrl + l`（小写的L) 来触发 checkbox

如果你真的希望用 obsidian 来做 task 管理，可以使用更加专业的插件

- https://github.com/thingnotok/obsidian-toggle-list
- https://github.com/wenlzhang/obsidian-task-marker
- https://github.com/ebullient/obsidian-task-collector
- https://github.com/delashum/obsidian-checklist-plugin

这是我自己搜索到的，我还没有详细的去尝试，但是应该有点用

**Comment by Yaozhuwa** [comment]
> 不建议使用这个插件来完成这个操作，你如果按照 @Yaozhuwa 的方法来做，是可以完成这个工作的。
> 
> 但是会有一个问题，比如你确实希望在行首直接写TODO这个字符串，那这就需要很奇怪的手法来绕过这个字符串替换
> 
> Obsidian 本身就有个快捷键 `Ctrl + l`（小写的L) 来触发 checkbox
> 
> 如果你真的希望用 obsidian 来做 task 管理，可以使用更加专业的插件
> 
> * https://github.com/thingnotok/obsidian-toggle-list
> * https://github.com/wenlzhang/obsidian-task-marker
> * https://github.com/ebullient/obsidian-task-collector
> * https://github.com/delashum/obsidian-checklist-plugin
> 
> 这是我自己搜索到的，我还没有详细的去尝试，但是应该有点用

说的很对
