### ISSUE TITLE
指定文件不格式化好像不生效

### ISSUE THREAD

**Issue by TMDW** [Yaozhuwa/easy-typing-obsidian#206]
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/74757345/a1625182-1776-4d79-9e1b-4f45897b2d60)
指定文件不自动格式化设置后好像无法生效
ob版本：1.5.3
easy typing 版本：5.1.14

**Comment by Yaozhuwa** [comment]
你的文件在Obsidian中的完整路径截图看下，还有就是不格式化的输入框行尾不要加空格。

**Comment by TMDW** [comment]
仓库名称：工作

 



 

输入框行尾没有空格，依旧不生效

发件人: ***@***.*** ***@***.***> 代表 叶耀祖
发送时间: 2024年3月16日 9:08
收件人: Yaozhuwa/easy-typing-obsidian ***@***.***>
抄送: TMDW ***@***.***>; Author ***@***.***>
主题: Re: [Yaozhuwa/easy-typing-obsidian] 指定文件不格式化好像不生效 (Issue #206)

 

你的文件在Obsidian中的完整路径截图看下，还有就是不格式化的输入框行尾不要加空格。

**Comment by AnandSinha2** [comment]
把仓库名去掉就好了，应为
```
/药品索引.md
```

**Comment by TMDW** [comment]
是这样的，直接“ 药品索引.md ”就行了，前面的斜杠也可以省掉
谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Anand Sinha ***@***.***&gt;
发送时间: 2024年3月23日 21:57
收件人: Yaozhuwa/easy-typing-obsidian ***@***.***&gt;
抄送: TMDW ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Yaozhuwa/easy-typing-obsidian] 指定文件不格式化好像不生效 (Issue #206)





 
把仓库名去掉就好了，应为
 /药品索引.md
