### ISSUE TITLE
建议给希腊字母两边加空格

### ISSUE THREAD

**Issue by YandLiu** [Yaozhuwa/easy-typing-obsidian#207]
全球α核药
↓
全球 α 核药

另外问下，我加了很多到`自定义转换规则`这里，为啥输入α后没有给自动加上一个空格呢？
规则都是 "α|" 变为 "空格α空格|"这样的
![图片](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/26127104/34e1538f-4f29-4bd7-8702-bb5b47569e19)

**Comment by menghuu** [comment]
在正则那里添加
```
α|++
```

或者使用下面的方式整体添加
```
[\uxxxx-\uyyyy]|++
```

其中的 xxxx 和 yyyy 是这些拉丁字母的 unicode 码

**Comment by YandLiu** [comment]
该如何实现中文和希腊字母之间加空格的同时，保持英文跟希腊字母不必要求有空格？
类似于这样：
`全球 α 核药`
`与 SIRPα 的融合蛋白`
