### ISSUE TITLE
MacOS自动删除[[]]内的中文

### ISSUE THREAD

**Issue by BetterWorld-Liuser** [Yaozhuwa/easy-typing-obsidian#208]
![](http://oss.babelgo.cn/img/202403172156395.gif)

Obsidian insider版本：1.5.11
之前版本也会出现这个问题。

每次输入法完成后，准备重新输入的时候就会自动清空前面的内容。

**Comment by Yaozhuwa** [comment]
<img width="816" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/ff293bb2-c560-4b9a-9650-91a87c40babc">

**Comment by Yaozhuwa** [comment]
已复现，我找时间看看~

**Comment by Yaozhuwa** [comment]
我测试发现，这个不是本插件的问题，而是 Obsidian 的 Bug，在 沙箱库中能够复现

**Comment by Yaozhuwa** [comment]
已报告官方论坛 https://forum.obsidian.md/t/when-you-input-chinese-continuously-in-it-will-overwrite-the-previous-input/78832
