### ISSUE TITLE
自动转换无法在yaml属性中生效

### ISSUE THREAD

**Issue by chiusuan** [Yaozhuwa/easy-typing-obsidian#209]
我设置了一条自动转换规则，规则如下
【【→[[]]
由于该规则无法在属性中生效，导致我必须每次都手动输入[[]]

**Comment by Yaozhuwa** [comment]
本插件的原理是检测文档变化信息，然后根据变化信息来做出一些反应。而 Obsidian 的可视化属性编辑在编辑过程并不产生文档变化，而是编辑完成后按回车，obsidian才将其内容同步到文档中。所以可视化编辑属性时本插件并不能做出反应。而在源码模式下本插件依旧生效。

该问题目前无法解决。就像 `Ctrl+F` 的搜索框中，本插件无法生效一样
