### ISSUE TITLE
更新5.2.2版本后中英文之间只会在英文后插入空格

### ISSUE THREAD

**Issue by lanx214** [Yaozhuwa/easy-typing-obsidian#211]
系统：win11
主程序版本：v1.5.8
插件版本：5.2.2
使用输入法：微软输入法（打开和关闭“适配旧版微软输入法”选项都尝试了）

应该是更新5.2.2后出现的问题，如尝试输入“测试test测试”，理想的情况应该是“测试 test 测试”，但结果只自动转换为了“测试test 测试”（此时如果再手动格式化本行是可以正确转换的）。

相关控制台输出如附件。
[obsidian.md-1710988024501.log](https://github.com/Yaozhuwa/easy-typing-obsidian/files/14681058/obsidian.md-1710988024501.log)

**Comment by odd256** [comment]
遇到了同样的问题，请问有解决方案吗？

**Comment by Yaozhuwa** [comment]
以下开关打开有用吗
<img width="590" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/bf57b626-083a-4b2e-8098-8b9a275f7f2b">

**Comment by odd256** [comment]
> 以下开关打开有用吗 <img alt="image" width="590" src="https://private-user-images.githubusercontent.com/28787183/315059051-bf57b626-083a-4b2e-8098-8b9a275f7f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDExNzIsIm5iZiI6MTcxMTAwMDg3MiwicGF0aCI6Ii8yODc4NzE4My8zMTUwNTkwNTEtYmY1N2I2MjYtMDgzYS00YjJlLTgwOTgtOGI5YTI3NWY3ZjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA2MDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMGZmN2M2ZGQyMzk1ZTMxNGIwODZjNzcwNjNiM2Q4NzJkYjMzNmUwOTEzMDU4OWEyZTIzZGQ5ZjM3NDg3ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vmvSe2JSNGgq2ouhyCAhm6XdDrrAEuxha5SCNN2UnBI">

感谢，在打开开关后，空格插入恢复正常了

**Comment by Yaozhuwa** [comment]
@lanx214

**Comment by lanx214** [comment]
> 以下开关打开有用吗 <img alt="image" width="590" src="https://private-user-images.githubusercontent.com/28787183/315059051-bf57b626-083a-4b2e-8098-8b9a275f7f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDcwMTksIm5iZiI6MTcxMTAwNjcxOSwicGF0aCI6Ii8yODc4NzE4My8zMTUwNTkwNTEtYmY1N2I2MjYtMDgzYS00YjJlLTgwOTgtOGI5YTI3NWY3ZjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA3MzgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiODIwZmM1ODdhODBkOGEyNzc0ODYzY2NhOWU2ZjNjY2Y1ZmUwYmIwODBhYjg5ZDU2NzJkNWNkYzFhMDBiMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PGsEAXkFz9V-9DO-CP6A-jZY_U-uztg-vBxbMkeyFQc">

啊这个选项是有效的，没想到是要打开这个开关 ，我以为是微软输入法的问题，和输入法及适配选项狠狠搏斗了一番。非常感谢~
