### ISSUE TITLE
中英文间自动空格错误

### ISSUE THREAD

**Issue by Forgoys** [Yaozhuwa/easy-typing-obsidian#214]
Obsidian：Version 1.5.11
Easy Typing：5.2.2
MacOS：14.4

中英文间自动空格只空英文后面与汉字之间，英文前面和汉字之间不空，具体类似于，输入“x和y和z和”，格式自动转换为“x 和y 和z 和”，而不是“x 和 y 和 z 和”。
创建了一个空库，只安装Easy Typing插件，设置选项均为默认，问题可复现：
![iShot_2024-03-27_15 23 03](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/47031885/e9c34691-6166-41e5-83a5-3b01326a4ead)
下面是控制台输出信息：
<img width="519" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/47031885/4543a2e7-6661-4022-93e0-4a981e246f5a">
麻烦您看下是什么原因，非常感谢！

**Comment by Yaozhuwa** [comment]
https://github.com/Yaozhuwa/easy-typing-obsidian/issues/211#issuecomment-2011274404

插件设置中打开实验性功能中的第二项开关

**Comment by Forgoys** [comment]
感谢，已解决。
