### ISSUE TITLE
粘贴为纯文本后，光标会跳到粘贴的文本开头

### ISSUE THREAD

**Issue by userkira** [Yaozhuwa/easy-typing-obsidian#218]
您好！
Ctrl+Shift+V，无格式粘贴文本后，光标自动跳到该文本的最开头，关闭插件后或只用Ctrl+V是正常的，即光标会在粘贴文本的末尾。请问是否可以设置，在无格式粘贴文本后让光标在末尾？
谢谢！

**Comment by Yaozhuwa** [comment]
V5.3.0 修复了该问题
