### ISSUE TITLE
输入网址，“.”后域名出现自动大写，自动空格问题，求正则表达式

### ISSUE THREAD

**Issue by zhaozhiliao** [Yaozhuwa/easy-typing-obsidian#22]
![image](https://user-images.githubusercontent.com/51565169/145556950-7cec3ee9-bbe1-48b2-a278-21cab3b27b6e.png)
非常感谢

**Comment by Yaozhuwa** [comment]
直接粘贴网址应该没问题。输入的话这个判断逻辑做不了，没有办法。

也可以在插件设置中关闭英文与标点自动空格以及自动首字母大写的功能。
