### ISSUE TITLE
请求加入多光标

### ISSUE THREAD

**Issue by MechCrafter** [Yaozhuwa/easy-typing-obsidian#220]
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/130667961/433e9fdd-408d-4110-91ed-28e43503b5c7)

请求在 自定义编辑转换规则 中加入多光标模式，类似 vscode 的 snippets 的 $1、$2，按 tab 键就可以跳转光标

**Comment by Yaozhuwa** [comment]
我早有此意，有时间会添加的

**Comment by Yaozhuwa** [comment]
V5.5.0 版本自定义规则支持了多光标跳转，详见更新日志

**Comment by MechCrafter** [comment]
Awesome
