### ISSUE TITLE
自定义编辑转换规则无法转换

### ISSUE THREAD

**Issue by MechCrafter** [Yaozhuwa/easy-typing-obsidian#221]
我发现一个不知道是不是 bug 的 bug，我自定义编辑转换规则：`todo| -> - [ ] |`，我希望在输入 `todo` 时，转换为一个待办小空格，可是我发现如果在中文输入法下输入 `todo` 时，它不会转换为待办小空格，只有在英文输入法下输入 `todo` 它才能转换为待办小空格，同样的我自定义了一个编辑转换规则：`blue| -> <font color=blue>|</font>`，我只能在英文输入法下输入 `blue` 才能转换为 `<font color=blue></font>`

![output](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/130667961/dcd283d8-89ed-4fe3-a777-3121d684ba36)

**Comment by Yaozhuwa** [comment]
这是bug，下个版本会修复~

**Comment by Yaozhuwa** [comment]
v5.3.1 已经修复，去试试吧

**Comment by MechCrafter** [comment]
解决了，感谢感谢
