### ISSUE TITLE
代码块里连续输入 、、转为注释

### ISSUE THREAD

**Issue by quanru** [Yaozhuwa/easy-typing-obsidian#222]
插件很棒，提个小需求，目前代码块里连续输入 、、时，如下所示
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/11739753/f7861f86-71e1-4ffd-9195-18ea6f282e6d)

希望能自动转为 //

**Comment by Yaozhuwa** [comment]
这个想法很好，但是作为开发者我考虑的要更通用。

首先，对于不同的编程语言，注释的符号也不同，如对于 JavaScript 是 `//` 而对于 Python 注释符号则为 `#`。

此外，Obsidian（包括其他编辑器如VSCode） 对于注释有内置的快捷键 `CMD/Ctrl+/`，不过 Obsidian 统一处理为markdown的注释了。我后续打算做一个代码块内`CMD/Ctrl+/` 注释 当前行/或者选中的多行 的功能，会根据代码块语言变化而变化。

**Comment by quanru** [comment]
即使不同的语言注释不同，但是 、、转为 // 也是稳妥的，与 python 的 # 注释不冲突

**Comment by Yaozhuwa** [comment]
计划的实现效果如下：
<img width="650" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/dbd4adf2-956e-40af-a30f-733a887900e3">

**Comment by Yaozhuwa** [comment]
V5.5.2 版本可以通过快捷键切换注释代码块
