### ISSUE TITLE
关于时间自动加空格功能无法关闭的问题

### ISSUE THREAD

**Issue by Immortal-Sty** [Yaozhuwa/easy-typing-obsidian#223]
插件 Dataview 有个叫 Inline Fields 的东西，可以在正文中，用 `key :: value` 语法给当前文章添加属性，Obsidian 属性中，日期时间的格式为 `YYYY-MM-ddTHH:mm`，安装 Easy Typing 后，我输入 `time :: 2024-05-02T19:14`，然而 Easy Typing 总是会在 19:14 的前面加上空格，导致日期时间语法失效。

**Comment by Yaozhuwa** [comment]
试试新版本~

**Comment by Immortal-Sty** [comment]
感谢！已经没有问题了💕
