### ISSUE TITLE
输入法输入中文双引号问题

### ISSUE THREAD

**Issue by YandLiu** [Yaozhuwa/easy-typing-obsidian#224]
# 百度输入法
开启输入法设置里的中文符号自动配对+插件里的`Symbol auto pair and delete with pair`后，输入法中文模式下`Shift+’`出来的是配对的英文双引号，需要关掉输入法自动配对或插件自动配对之一才能正确出来中文双引号
![图片](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/26127104/8b8987a9-e4f6-4daf-9c14-76a6a83e38ab)

# 搜狗输入法
无论是否开启输入法的自动配对，无论是否开启插件的自动配对，打出来的都是英文双引号

**Comment by Yaozhuwa** [comment]
插件的原理是检测输入的内容来实现转化，应该你输入法设置的就是配对的导致插件认为你输入了两次，触发了连续全角转半角的功能，最终得到半角的配对符号 ~ 你可以关闭 `连续全角转半角`的功能 试试
