### ISSUE TITLE
在自定义转换规则中支持转义字符

### ISSUE THREAD

**Issue by BigCoke233** [Yaozhuwa/easy-typing-obsidian#225]
希望通过转换规则快速生成代码片段，例如 `!side` 转换为：

```markdown
> [!note|aside-r]
> |
```

理想情况下，第二行在 `>` 的 `|` 才应该被当作光标，而 `[!note|aside-r]` 中的 `|` 不应该被当作光标。

尝试将第一个 `|` 写作 `\|`，发现并不起作用，所以希望作者加入对转义字符的支持，输入 `\|` 时不会被当作光标，转换后也只输出 `|` 的结果

**Comment by TANGLi83-star** [comment]
我也有这个需求，希望能实现

**Comment by Yaozhuwa** [comment]
可以的，下个版本会增加转移符号的支持~

**Comment by Yaozhuwa** [comment]
V5.3.4 版本自定义 删除/转换 规则 已支持转义字符，欢迎尝试与反馈 @BigCoke233 @TANGLi83-star
