### ISSUE TITLE
VS代码粘贴到代码块中缩进消失

### ISSUE THREAD

**Issue by muzhenghua** [Yaozhuwa/easy-typing-obsidian#229]
![Uploading 屏幕截图 2024-05-28 231018.png…]()

**Comment by Yaozhuwa** [comment]
截图看不到

**Comment by muzhenghua** [comment]
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/32711088/a43f27e2-6591-4cfe-95e8-3a8a1c585823)

**Comment by muzhenghua** [comment]
拷贝进代码块里面才会有这个问题，直接拷贝到正文中不会出现这个问题。

**Comment by Yaozhuwa** [comment]
> ![image](https://private-user-images.githubusercontent.com/32711088/343228686-a43f27e2-6591-4cfe-95e8-3a8a1c585823.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MDQwNDAsIm5iZiI6MTcxOTcwMzc0MCwicGF0aCI6Ii8zMjcxMTA4OC8zNDMyMjg2ODYtYTQzZjI3ZTItNjU5MS00Y2ZlLTk1ZTgtM2E4YTFjNTg1ODIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDIzMjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjQzNDE1MzAxMzRhMmZhMTg3NTVjOTdhZTE1ODQ0OTkyNTMyZThjODNjNDQyYzY0Yjk1YjA0MzAxMmZkODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H91T1aqWAnr4BSO4RxoH1Y8FaynVggx9mkNP-7zu2Po)

是这样的，本插件对粘贴代码的情况做了特殊处理（代码块粘贴智能缩进），在大部分情况下会比较好用。但对于你的情况，你应该是拷贝的7-17行的内容，这时候粘贴的话，本插件的代码块粘贴时智能缩进的功能反而导致你的缩进错误。

但是如果你代码第17行的 `}` 本身缩进是正确的情况（在最左边，无空格），本插件不会导致你缩进错误。或者你拷贝的是6-17行，也没问题。

总之，在大部分情况下，如果拷贝的代码本身缩进是没问题的，本插件基本不会出错。

如果你不喜欢这个功能，也可以在设置中关闭。

<img width="587" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/b2fa33e9-51af-4764-8330-35f981225810">

**Comment by Yaozhuwa** [comment]
抱歉，我在沙箱库测试后发现的确有这个问题，我会尽快修复~

**Comment by Yaozhuwa** [comment]
我更新了 5.4.1 版本，看下是否还有问题~
