### ISSUE TITLE
升级到 v0.13.14 之后失效

### ISSUE THREAD

**Issue by chenyukang** [Yaozhuwa/easy-typing-obsidian#23]
打开Live Preview之后，插件不起作用。

**Comment by Yaozhuwa** [comment]
是的，这是由于live preview下旧的API不起作用。目前我看live preview能用的事件就是 'editor-change'事件，而本插件是基于按键响应做的，后续支持可能要等官方开放按键事件的API，或者我能换成只依赖 'editor-change'事件的实现（会有一些功能无法实现）。

**Comment by Yaozhuwa** [comment]
今天看了下文档，CodeMirror 5 到 6 的变化还是挺大的，不再有事件响应机制了，之后我需要学习一下，然后想办法重新用新的API实现一下。

**Comment by CrazyMouse** [comment]
貌似新版本后中文和英文之间加入空格的功能就不能用了

**Comment by zhaozhiliao** [comment]
> 今天看了下文档，CodeMirror 5 到 6 的变化还是挺大的，不再有事件响应机制了，之后我需要学习一下，然后想办法重新用新的API实现一下。

辛苦辛苦，抽空支持下新版本。插件很好用呀

**Comment by CoachHe** [comment]
插件真的非常棒，我都依赖上这个插件了，但是live proview下不能用了，真的希望能更新一下~

**Comment by Yaozhuwa** [comment]
最新版本v4.0.0 已支持新版编辑器了。

**Comment by chenyukang** [comment]
> 最新版本v4.0.0 已支持新版编辑器了。

感谢，赶紧试试。

**Comment by chenyukang** [comment]
问题看起来没解决
输入法输入拼音的时候，第一个字母会变成英文字母........

**Comment by chenyukang** [comment]
![error2](https://user-images.githubusercontent.com/230646/153356946-5930a145-8b43-4cb7-b5d8-79c71ea1fec1.gif)

**Comment by Yaozhuwa** [comment]
> ![error2](https://user-images.githubusercontent.com/230646/153356946-5930a145-8b43-4cb7-b5d8-79c71ea1fec1.gif)

你好，这个问题我已经在README中有说明问题及解决办法：https://github.com/Yaozhuwa/easy-typing-obsidian#%E7%8E%B0%E5%AD%98%E9%97%AE%E9%A2%98-known-issue

**Comment by chenyukang** [comment]
> > ![error2](https://user-images.githubusercontent.com/230646/153356946-5930a145-8b43-4cb7-b5d8-79c71ea1fec1.gif)
> 
> 你好，这个问题我已经在README中有说明问题及解决办法：https://github.com/Yaozhuwa/easy-typing-obsidian#%E7%8E%B0%E5%AD%98%E9%97%AE%E9%A2%98-known-issue

我觉得这不是 Obsidian 的bug，因为我在Preview mode下，关闭 easy-typing-obsidian就没有这个问题，
打开easy-typing-obisidian就会有这个问题。

**Comment by chenyukang** [comment]
我也不是很确定，可能你使用了codemirror的api，或者是调用了obsidian的api，这个api会有问题？
