### ISSUE TITLE
开启 Tabout 后，代码块无法多次使用 tab 来缩进

### ISSUE THREAD

**Issue by GuiLuan** [Yaozhuwa/easy-typing-obsidian#230]
![GIF 2024-6-13 22-37-34](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/100982603/d5f6ca43-74ff-4259-930d-82cfe0ba7963)

如上，开启 Tabout 功能后，tab功能在较深的缩进下无法产生缩进效果。

**Comment by GuiLuan** [comment]
![Uploading GIF 2024-6-13 22-37-34.gif…]()

**Comment by GuiLuan** [comment]
![GIF 2024-6-13 22-37-34](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/100982603/2eee598f-55f9-45f7-aab4-62c44d93fd7c)

**Comment by Yaozhuwa** [comment]
我这边没法复现，你能否在沙箱库中测试下~

**Comment by GuiLuan** [comment]
> 我这边没法复现，你能否在沙箱库中测试下~

我在沙箱库测试过，确实是由 tabout 引起的。
![GIF 2024-6-30 10-46-44](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/100982603/1bcdf12e-7794-4a4a-83bb-7de6d17b5a33)

如果这是开启 tabout 的特性或者不可避免的副作用的话，希望能够在文档中标注一下。

**Comment by Yaozhuwa** [comment]
> > 我这边没法复现，你能否在沙箱库中测试下~
> 
> 我在沙箱库测试过，确实是由 tabout 引起的。 ![GIF 2024-6-30 10-46-44](https://private-user-images.githubusercontent.com/100982603/344440644-1bcdf12e-7794-4a4a-83bb-7de6d17b5a33.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTczMTIsIm5iZiI6MTcxOTcxNzAxMiwicGF0aCI6Ii8xMDA5ODI2MDMvMzQ0NDQwNjQ0LTFiY2RmMTJlLTc3OTQtNGE0YS04M2JiLTdkZTZkMTdiNWEzMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwMzEwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTJhZTc1ZTkyZWE1ODExOGExNmU0OWVkY2RkY2ZhY2E1ODE0MjAyYzAzN2YyMWU0OTZmNjNjMjY0MDRkMTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YhikhuP9Ka4JB0WYCgZ_gXvpUZmZgboeJESdpHAve8E) [ ![GIF 2024-6-30 10-46-44](https://private-user-images.githubusercontent.com/100982603/344440644-1bcdf12e-7794-4a4a-83bb-7de6d17b5a33.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTczMTIsIm5iZiI6MTcxOTcxNzAxMiwicGF0aCI6Ii8xMDA5ODI2MDMvMzQ0NDQwNjQ0LTFiY2RmMTJlLTc3OTQtNGE0YS04M2JiLTdkZTZkMTdiNWEzMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwMzEwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTJhZTc1ZTkyZWE1ODExOGExNmU0OWVkY2RkY2ZhY2E1ODE0MjAyYzAzN2YyMWU0OTZmNjNjMjY0MDRkMTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YhikhuP9Ka4JB0WYCgZ_gXvpUZmZgboeJESdpHAve8E) ](https://private-user-images.githubusercontent.com/100982603/344440644-1bcdf12e-7794-4a4a-83bb-7de6d17b5a33.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTczMTIsIm5iZiI6MTcxOTcxNzAxMiwicGF0aCI6Ii8xMDA5ODI2MDMvMzQ0NDQwNjQ0LTFiY2RmMTJlLTc3OTQtNGE0YS04M2JiLTdkZTZkMTdiNWEzMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwMzEwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTJhZTc1ZTkyZWE1ODExOGExNmU0OWVkY2RkY2ZhY2E1ODE0MjAyYzAzN2YyMWU0OTZmNjNjMjY0MDRkMTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YhikhuP9Ka4JB0WYCgZ_gXvpUZmZgboeJESdpHAve8E) [ ](https://private-user-images.githubusercontent.com/100982603/344440644-1bcdf12e-7794-4a4a-83bb-7de6d17b5a33.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTczMTIsIm5iZiI6MTcxOTcxNzAxMiwicGF0aCI6Ii8xMDA5ODI2MDMvMzQ0NDQwNjQ0LTFiY2RmMTJlLTc3OTQtNGE0YS04M2JiLTdkZTZkMTdiNWEzMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwMzEwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTJhZTc1ZTkyZWE1ODExOGExNmU0OWVkY2RkY2ZhY2E1ODE0MjAyYzAzN2YyMWU0OTZmNjNjMjY0MDRkMTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YhikhuP9Ka4JB0WYCgZ_gXvpUZmZgboeJESdpHAve8E)
> 
> 如果这是开启 tabout 的特性或者不可避免的副作用的话，希望能够在文档中标注一下。

Tabout 本身没有这样的特性

我本地开发环境是 MAC，可能和 Windows 平台有关，我晚点试下Windows上能否复现

**Comment by Yaozhuwa** [comment]
> > 我这边没法复现，你能否在沙箱库中测试下~
> 
> 我在沙箱库测试过，确实是由 tabout 引起的。 ![GIF 2024-6-30 10-46-44](https://private-user-images.githubusercontent.com/100982603/344440644-1bcdf12e-7794-4a4a-83bb-7de6d17b5a33.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTc0NDEsIm5iZiI6MTcxOTcxNzE0MSwicGF0aCI6Ii8xMDA5ODI2MDMvMzQ0NDQwNjQ0LTFiY2RmMTJlLTc3OTQtNGE0YS04M2JiLTdkZTZkMTdiNWEzMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwMzEyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjVjMDFhZWRkODA4OGViMWJjOTI1OGY5MjQxZjUyYjBmNzdkYTdiZTI0N2IyODVkZGRhZDQyYzBiYTMyNTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C50ZkPPDAnpdUn-uN2oZJyh6ip2sSWS5oUnGd18o9D0) [ ![GIF 2024-6-30 10-46-44](https://private-user-images.githubusercontent.com/100982603/344440644-1bcdf12e-7794-4a4a-83bb-7de6d17b5a33.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTc0NDEsIm5iZiI6MTcxOTcxNzE0MSwicGF0aCI6Ii8xMDA5ODI2MDMvMzQ0NDQwNjQ0LTFiY2RmMTJlLTc3OTQtNGE0YS04M2JiLTdkZTZkMTdiNWEzMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwMzEyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjVjMDFhZWRkODA4OGViMWJjOTI1OGY5MjQxZjUyYjBmNzdkYTdiZTI0N2IyODVkZGRhZDQyYzBiYTMyNTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C50ZkPPDAnpdUn-uN2oZJyh6ip2sSWS5oUnGd18o9D0) ](https://private-user-images.githubusercontent.com/100982603/344440644-1bcdf12e-7794-4a4a-83bb-7de6d17b5a33.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTc0NDEsIm5iZiI6MTcxOTcxNzE0MSwicGF0aCI6Ii8xMDA5ODI2MDMvMzQ0NDQwNjQ0LTFiY2RmMTJlLTc3OTQtNGE0YS04M2JiLTdkZTZkMTdiNWEzMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwMzEyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjVjMDFhZWRkODA4OGViMWJjOTI1OGY5MjQxZjUyYjBmNzdkYTdiZTI0N2IyODVkZGRhZDQyYzBiYTMyNTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C50ZkPPDAnpdUn-uN2oZJyh6ip2sSWS5oUnGd18o9D0) [ ](https://private-user-images.githubusercontent.com/100982603/344440644-1bcdf12e-7794-4a4a-83bb-7de6d17b5a33.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTc0NDEsIm5iZiI6MTcxOTcxNzE0MSwicGF0aCI6Ii8xMDA5ODI2MDMvMzQ0NDQwNjQ0LTFiY2RmMTJlLTc3OTQtNGE0YS04M2JiLTdkZTZkMTdiNWEzMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwMzEyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjVjMDFhZWRkODA4OGViMWJjOTI1OGY5MjQxZjUyYjBmNzdkYTdiZTI0N2IyODVkZGRhZDQyYzBiYTMyNTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C50ZkPPDAnpdUn-uN2oZJyh6ip2sSWS5oUnGd18o9D0)
> 
> 如果这是开启 tabout 的特性或者不可避免的副作用的话，希望能够在文档中标注一下。

非常抱歉，是我的问题~ 

由于我本地仓库无法复现你的问题，所以一开始我怀疑是你的其他插件的影响。但是我现在在沙箱库测试的确有这个问题。

我会尽快解决~

**Comment by Yaozhuwa** [comment]
我更新了 5.4.1 版本，看下是否还有问题~

**Comment by GuiLuan** [comment]
目前没有问题了
