### ISSUE TITLE
最新版插件shift + ctrl +V失灵

### ISSUE THREAD

**Issue by jingmengzhiyue** [Yaozhuwa/easy-typing-obsidian#231]
安装Easy Typing插件之后导致 shift + ctrl +V(粘贴为纯文本)快捷键失灵(通过逐个禁用插件排查之后发现是由Easy Typing导致，禁用Easy Typing插件可以正常使用shift + ctrl +V)。补充一下，主要是同时复制多行会在使用 shift + ctrl +V粘贴时失效，尤其是在复制段代码时出现此问题。
![image](https://github.com/Yaozhuwa/easy-typing-obsidian/assets/32026598/c2dfa7ff-69dd-4358-a7c4-a4ef40765a30)
如图中选中复制大段代码在obsidian中的代码（```c ... ```）中无法使用shift + ctrl +V快捷键，只能使用右键菜单->粘贴为纯文本。

obsidian版本：1.6.3

Easy Typing版本：5.4.0

**Comment by Yaozhuwa** [comment]
<img width="640" alt="image" src="https://github.com/Yaozhuwa/easy-typing-obsidian/assets/28787183/ec0adeb9-bbcd-4eb5-a696-08e32a5bd0e6">

首先，我这边无法复现你的情况。

本插件为了一些功能，自己实现了一个无格式化粘贴的功能，默认快捷键就是 shift + ctrl +V，你看把这个快捷键设置取消会不会有用。

**Comment by abcdlsj** [comment]
遇到了同样的问题，取消 `shift + ctrl +V` 快捷键设置没有用，关闭 easy typing 插件后就正常

**Comment by Yaozhuwa** [comment]
> 遇到了同样的问题，取消 `shift + ctrl +V` 快捷键设置没有用，关闭 easy typing 插件后就正常

如果将 easy-typing 的无格式化粘贴的命令 设置快捷键 为 `Shift+Ctrl+V` 能否解决问题呢

**Comment by abcdlsj** [comment]
> > 遇到了同样的问题，取消 `shift + ctrl +V` 快捷键设置没有用，关闭 easy typing 插件后就正常
> 
> 如果将 easy-typing 的无格式化粘贴的命令 设置快捷键 为 `Shift+Ctrl+V` 能否解决问题呢

没有用，安装 easy typing 后 `无格式化粘贴` 默认的设置就是 `Shift+Ctrl+V`，去掉快捷键设置和将其设置为其它快捷键，都不行，使用 `Shift+Ctrl+V` 都会影响代码段多行的粘贴格式，格式会错乱为无缩进

比如这样
```
func search(nums []int, target int) int {
le, ri := 0, len(nums)-1

for le <= ri {
mid := le + (ri-le)/2

if target == nums[mid] {
return mid
}
...
```

**Comment by Yaozhuwa** [comment]
> > > 遇到了同样的问题，取消 `shift + ctrl +V` 快捷键设置没有用，关闭 easy typing 插件后就正常
> > 
> > 
> > 如果将 easy-typing 的无格式化粘贴的命令 设置快捷键 为 `Shift+Ctrl+V` 能否解决问题呢
> 
> 没有用，安装 easy typing 后 `无格式化粘贴` 默认的设置就是 `Shift+Ctrl+V`，去掉快捷键设置和将其设置为其它快捷键，都不行，使用 `Shift+Ctrl+V` 都会影响代码段多行的粘贴格式，格式会错乱为无缩进
> 
> 比如这样
> 
> ```
> func search(nums []int, target int) int {
> le, ri := 0, len(nums)-1
> 
> for le <= ri {
> mid := le + (ri-le)/2
> 
> if target == nums[mid] {
> return mid
> }
> ...
> ```

是这样的，目前插件在代码块中粘贴的功能是有问题的，见 #229 

所以是不是你们遇到的问题是代码块中无格式粘贴失效（实际上是 #229），而不是真的无格式粘贴失灵呢~

**Comment by abcdlsj** [comment]
> > > > 遇到了同样的问题，取消 `shift + ctrl +V` 快捷键设置没有用，关闭 easy typing 插件后就正常
> > > 
> > > 
> > > 如果将 easy-typing 的无格式化粘贴的命令 设置快捷键 为 `Shift+Ctrl+V` 能否解决问题呢
> > 
> > 
> > 没有用，安装 easy typing 后 `无格式化粘贴` 默认的设置就是 `Shift+Ctrl+V`，去掉快捷键设置和将其设置为其它快捷键，都不行，使用 `Shift+Ctrl+V` 都会影响代码段多行的粘贴格式，格式会错乱为无缩进
> > 比如这样
> > ```
> > func search(nums []int, target int) int {
> > le, ri := 0, len(nums)-1
> > 
> > for le <= ri {
> > mid := le + (ri-le)/2
> > 
> > if target == nums[mid] {
> > return mid
> > }
> > ...
> > ```
> 
> 是这样的，目前插件在代码块中粘贴的功能是有问题的，见 #229
> 
> 所以是不是你们遇到的问题是代码块中无格式粘贴失效（实际上是 #229），而不是真的无格式粘贴失灵呢~

是的，其实就是 #229 的情况

**Comment by Yaozhuwa** [comment]
我更新了 5.4.1 版本，你们看下是否还有问题~

**Comment by abcdlsj** [comment]
> 我更新了 5.4.1 版本，你们看下是否还有问题~

复制到代码块正常了，thx

**Comment by jingmengzhiyue** [comment]
> 我更新了 5.4.1 版本，你们看下是否还有问题~

刚刚测试使用了，代码块使用 `Shift+Ctrl+V`复制已经正常了，感谢作者大大。

**Comment by LXP-Never** [comment]
现在这个问题又出现了，当前版本5.5.15
