### ISSUE TITLE
编辑转换：是否有可能添加对vim的支持

### ISSUE THREAD

**Issue by wyyea** [Yaozhuwa/easy-typing-obsidian#237]
vim下visual模式下选中后点击`无法在选中部分两边都添加``，该功能好像只支持鼠标选中，如果能添加对vim下visual模式的支持就太好了

**Comment by Yaozhuwa** [comment]
对于VIM模式下，目前本插件只在插入模式下生效。

Visual 模式VIM自带的就是拷贝、剪切、粘贴这些操作吧。

对于你的需求，我目前还不知道要如何实现。

**Comment by yaoyhu** [comment]
> vim下visual模式下选中后点击`无法在选中部分两边都添加``，该功能好像只支持鼠标选中，如果能添加对vim下visual模式的支持就太好了

这个功能插件 obsidian-vimrc-support 已经实现了：[Surround Text with surround](https://github.com/esm7/obsidian-vimrc-support#surround-text-with-surround)

**Comment by Yaozhuwa** [comment]
这个功能有专门的插件做了，我就关闭这个 issue 了
