### ISSUE TITLE
在中文字符串中间插入英文，只会在第一个连接处添加空格，第二个连接处未添加空格

### ISSUE THREAD

**Issue by wyyea** [Yaozhuwa/easy-typing-obsidian#238]
如将“你好”改为“你hello好”，只会格式化为"你 hello好“，而不是"你 hello 好”

**Comment by Yaozhuwa** [comment]
本插件的自动格式化只会为光标前的部分添加空格，光标后需要手动添加。

以你的例子，在 你好 中间输入英文 hello 时，如果光标后也自动空格的话，会变成
```
你 hello| 好
```
`|` 代表光标位置，此时并没有什么问题。但是如果此时你在hello后面继续输入中文 测试，就会变成：
```
你 hello 测试| 好
```
这时候，`测试`和`好`之间的空格是我们不期望的。

综上，为了泛用性，插件的自动格式化只会为光标前的部分添加空格，光标后需要手动添加。
