### ISSUE TITLE
功能增强：在自定义编辑转换规则中增加对正则表达式的支持

### ISSUE THREAD

**Issue by ZeaseTech** [Yaozhuwa/easy-typing-obsidian#239]
作者，你好，你这个插件很强大，我已经离不开它了。但是目前我觉得它可以更加强大。
我已经增加了很多的自定义转换规则，但是有很多转换规则是相似的，需要设置超级多遍，借助正则表达式就可以极大地简化自定义编辑转换任务。
希望作者大大可以增加这个功能，谢谢！

**Comment by Yaozhuwa** [comment]
正则表达式在v5.4.0就支持了，见更新日志 https://github.com/Yaozhuwa/easy-typing-obsidian/blob/master/changelog.md
