### ISSUE TITLE
#建议 增加中文竖线增强用于输入表格

### ISSUE THREAD

**Issue by Bavoch** [Yaozhuwa/easy-typing-obsidian#24]
感谢作者大大开发了一个这么棒的markdown插件，敬礼！

最新版本中好像插件无法使用了，另外希望能增加竖线符号哈，适用于输入表格

**Comment by Yaozhuwa** [comment]
>另外希望能增加竖线符号哈，适用于输入表格

抱歉我不太懂你的意思。竖线符号在中英文中输入不都是一样的吗

**Comment by Yaozhuwa** [comment]
本插件v4.0.0版本已支持新版编辑器

**Comment by Bavoch** [comment]
不一样呢，中文竖线占两个字符，无法输入markdown表格

**Comment by Yaozhuwa** [comment]
> 不一样呢，中文竖线占两个字符，无法输入markdown表格

@Bavoch 我自己windows上用微软输入法和Sogou输入法测试中文竖线输入表格，都是没有问题。
不管怎样，我可以尝试帮你解决这个问题。你需要把你在 obsidian 中打出的中文竖线字符 复制粘贴到你的回复里。

**Comment by Bavoch** [comment]
> > 不一样呢，中文竖线占两个字符，无法输入markdown表格
> 
> @Bavoch 我自己windows上用微软输入法和Sogou输入法测试中文竖线输入表格，都是没有问题。 不管怎样，我可以尝试帮你解决这个问题。你需要把你在 obsidian 中打出的中文竖线字符 复制粘贴到你的回复里。

非常感谢你的帮助，下面是我在obsidian中输入的中英文竖线：
中文竖线：｜
英文竖线：|

**Comment by Bavoch** [comment]
> > 不一样呢，中文竖线占两个字符，无法输入markdown表格
> 
> @Bavoch 我自己windows上用微软输入法和Sogou输入法测试中文竖线输入表格，都是没有问题。 不管怎样，我可以尝试帮你解决这个问题。你需要把你在 obsidian 中打出的中文竖线字符 复制粘贴到你的回复里。

补充一下，我现在用的是mac系统哦

**Comment by Yaozhuwa** [comment]
v4.0.1尝试解决你的问题，连续输入两次中文竖线应该会变成一个英文竖线。你看更新后能不能用。
