### ISSUE TITLE
自定义删除/转换规则 中的转义符无法转义

### ISSUE THREAD

**Issue by Thatonewall** [Yaozhuwa/easy-typing-obsidian#240]
在V5.3.4 2024-06-04更新中

>     可以在自定义删除/转换规则中使用转义字符 \，如 \n 是换行符。（支持\n \r \t）
>     输入 \| 时不会被当作光标，转换后也只输出 | 的结果

问题是：
如果我就想输出`\r`，不能使用`\`来转义`\r`，`\\r`输出出来就是一个换行，不是期望的`\r`

**Comment by Thatonewall** [comment]
*打错了，不能使用`//r`来输出`/r`

**Comment by Yaozhuwa** [comment]
可以复现问题，下个版本修复~

**Comment by Yaozhuwa** [comment]
v5.5.0 版本已修复
