### ISSUE TITLE
特殊正则表达式不生效

### ISSUE THREAD

**Issue by caamaha** [Yaozhuwa/easy-typing-obsidian#241]
我在用户定义的正则表达式加上了规则，用于匹配所有括号内的内容：
\((.*?)\)|--

但是在某些特殊文本里面这个表达式似乎匹配不上，导致我把如下的文本从一个地方复制粘贴到另一个地方的时候，会自动给我加上空格：
(0乔治Y.)
会变为
(0 乔治Y.)

**Comment by Yaozhuwa** [comment]
你的正则规则不对，改成如下即可
```
\(.*?\)|--
```
