### ISSUE TITLE
自定义规则转换：多光标跳转-文本选中语法问题

### ISSUE THREAD

**Issue by 06211221** [Yaozhuwa/easy-typing-obsidian#242]
VERSION: [V5.5.0](https://github.com/Yaozhuwa/easy-typing-obsidian/releases/tag/5.5.0)

根据插件发布时所提供的功能描述，V5.5.0 在自定义规则转换中可以通过语法 `${n, 文本}` 来设置光标选中文本。

结合实际操作来看，实现光标选中文本的语法应该不是 `${n, 文本}`，而是 `${n: 文本}`。

**Comment by Yaozhuwa** [comment]
的确，我改一下~
