### ISSUE TITLE
代码块中，就算纯文本粘贴也会丢失空格

### ISSUE THREAD

**Issue by fantab01** [Yaozhuwa/easy-typing-obsidian#243]
如动图所示
![bug](https://github.com/user-attachments/assets/296eb2b2-1aad-4fad-b2b8-d2a27343c858)

**Comment by Yaozhuwa** [comment]
对于你给的动图，我看不出哪里有问题。最好更详细具体的描述你的问题。

其次，本插件的确对代码块粘贴的空格做了处理，如果不喜欢可以在插件设置中关闭 增强代码块编辑 的功能。

**Comment by fantab01** [comment]
> 对于你给的动图，我看不出哪里有问题。最好更详细具体的描述你的问题。
> 
> 其次，本插件的确对代码块粘贴的空格做了处理，如果不喜欢可以在插件设置中关闭 增强代码块编辑 的功能。

我可能少描述一句话，动图里每行最前面充当缩进功能的空格消失了一部分，但又没全部消失

**Comment by keartor** [comment]
> 对于你给的动图，我看不出哪里有问题。最好更详细具体的描述你的问题。
> 
> 其次，本插件的确对代码块粘贴的空格做了处理，如果不喜欢可以在插件设置中关闭 增强代码块编辑 的功能。

可以把下面粘贴到代码块中，开启"增强代码块编辑"后，services:和navidrome:就会处于同一个缩进级别
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 #用户id，详细解释见后文
    ports:
      - 4533:4533 #左侧端口如有冲突，可随意修改
    volumes:
      - ./data:/data #数据路径
      - /volume1/DockerMV/音乐:/music:ro #音乐路径
    environment:
      #程序默认语言
      - ND_DEFAULTLANGUAGE=zh-Hans
      #启用GRAVATAR头像
      - ND_ENABLEGRAVATAR=true
      #关闭转码，如需要转码请设置为true
      - ND_ENABLETRANSCODINGCONFIG=false
      #SPOTIFY相关
      # - ND_SPOTIFY_ID=
      # - ND_SPOTIFY_SECRET=
      #LAST.FM相关
      # - ND_LASTFM_LANGUAGE=zh
      # - ND_LASTFM_APIKEY=
      # - ND_LASTFM_SECRET=
      #PROXY相关
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
    restart: unless-stopped
    privileged: true

**Comment by Yaozhuwa** [comment]
OK，有空的话，我会优化下代码块粘贴的功能

**Comment by keartor** [comment]
> OK，有空的话，我会优化下代码块粘贴的功能

感谢大佬

**Comment by Yaozhuwa** [comment]
V5.5.2 版本应该解决了这个问题~

**Comment by keartor** [comment]
> V5.5.2 版本应该解决了这个问题~

试了下，OK，感谢
