### ISSUE TITLE
求助，设定的删除规则不生效（删除[卡片]）

### ISSUE THREAD

**Issue by momo-in-github** [Yaozhuwa/easy-typing-obsidian#244]
设定：删除前`[卡片]|`，删除后`|`
![2024 08 23_](https://github.com/user-attachments/assets/9e7ce015-1cf1-473e-ba22-caf270dfabd9)

**Comment by Yaozhuwa** [comment]
无法复现：


https://github.com/user-attachments/assets/9c384e4e-602d-4abe-9b7c-c049f61dfd07

**Comment by Yaozhuwa** [comment]
太久没回复，删掉了
