### ISSUE TITLE
输入网址格式化错误

### ISSUE THREAD

**Issue by hotoo** [Yaozhuwa/easy-typing-obsidian#245]
![image](https://github.com/user-attachments/assets/43e1fe13-aa5e-426e-a5f9-f8c0381001d4)

**Comment by Yaozhuwa** [comment]
用户在输入的过程中，插件无法判断是否为网址。

解决办法：遵循Markdown语法，纯网址要用`<>`包围，如 <www.baidu.com> ，在插件设置的自定义正则区域添加如下正则来忽略尖括号内的文本自动格式化：
```
<.*?>|==
```
