### ISSUE TITLE
vim mode use

### ISSUE THREAD

**Issue by Hope2KZ** [Yaozhuwa/easy-typing-obsidian#246]
小白需要的两个解决方案：
1. vim模式下，按键jk映射为ESC，在一段中文文本中编辑结束后退出到vim的可视模式（jk）,按键“J”触发会在文本中加入一个空格，每次都需要手动删除
2. 编辑一段文字，例如 ： "你好 世界 空格是需要的"  ，中间的空格是我打上去的，但如果我对其中某一部分进行编辑所有的空格就都被删除了

插件非常好用，望大家帮助

**Comment by Yaozhuwa** [comment]
> 1. vim模式下，按键jk映射为ESC，在一段中文文本中编辑结束后退出到vim的可视模式（jk）,按键“J”触发会在文本中加入一个空格，每次都需要手动删除

我不明白这个问题是本插件触发的吗？

> 2. 编辑一段文字，例如 ： "你好 世界 空格是需要的" ，中间的空格是我打上去的，但如果我对其中某一部分进行编辑所有的空格就都被删除了

插件设置中可以关闭中文间删除空格的选项

**Comment by Hope2KZ** [comment]
> > 1. vim模式下，按键jk映射为ESC，在一段中文文本中编辑结束后退出到vim的可视模式（jk）,按键“J”触发会在文本中加入一个空格，每次都需要手动删除
> 
> 我不明白这个问题是本插件触发的吗？
> 
> > 2. 编辑一段文字，例如 ： "你好 世界 空格是需要的" ，中间的空格是我打上去的，但如果我对其中某一部分进行编辑所有的空格就都被删除了
> 
> 插件设置中可以关闭中文间删除空格的选项

不是该插件的问题，我的意思是希望大家可以给我一个方案避开jk按键加空格，我比较笨
