### ISSUE TITLE
中英文字符间空格

### ISSUE THREAD

**Issue by fjy007** [Yaozhuwa/easy-typing-obsidian#249]
系统：macos monterey 12.7.5
输入法：搜狗输入法
obsidian版本：1.6.7

英文字符和前面的中文字符之间没有空格
![image](https://github.com/user-attachments/assets/dc81ca08-bf22-4922-8a40-d536c9edefc7)
然后我看之前的回答把实验开关的第二个打开后还是不行😂
![image](https://github.com/user-attachments/assets/2292d69b-9b1f-42c2-8107-76f5e3c655be)

**Comment by fjy007** [comment]
East Typing 插件的版本是 5.5.0

**Comment by Yaozhuwa** [comment]
可以打开插件设置中的 控制台输出调试信息 选项，然后 CMD+OPTION+I 打开 Obsidian 控制台，在 Ob 编辑区域中复现这个问题，录屏发上来我可能能找到问题。

**Comment by fjy007** [comment]
我刚又试了一下，好像又好了，😂。谢谢作者大大😁
