### ISSUE TITLE
符号配对

### ISSUE THREAD

**Issue by tangxibomb** [Yaozhuwa/easy-typing-obsidian#250]
按下《
将变成这样《|》
如果再按下》
就会变成《|》》

作者能否实现下面的效果（像大多数IDE那样）：
《|》再次按下》时，变成《》|

**Comment by Yaozhuwa** [comment]
目前就是你说的效果吧：

https://github.com/user-attachments/assets/41a9b387-c082-45e0-aeec-321fca71eb33

**Comment by Yaozhuwa** [comment]
如果在你那里的确存在这个问题，你可以可以打开插件设置中的 控制台输出调试信息 选项，然后 CMD+OPTION+I / Ctrl+Shift+I 打开 Obsidian 控制台，在 Ob 编辑区域中复现这个问题，录屏发上来我可能能找到问题。

**Comment by tangxibomb** [comment]
不好意思，是我的需求没表达清楚
先按下《，然后在括号中输入一些字符，然后再按》，效果如下

《|》
《xxx|》
《xxx》|

**Comment by Yaozhuwa** [comment]
很简单，自定义转换规则如下：
<img width="788" alt="image" src="https://github.com/user-attachments/assets/036b2b19-2c03-4466-8efd-69970ab8c5ab">

**Comment by tangxibomb** [comment]
懂了！忘了能自定义。谢谢作者啦，前几天没白打赏hh🤣

**Comment by Yaozhuwa** [comment]
感谢支持！😄
