### ISSUE TITLE
[BUG] 控制台出现大量冗余信息

### ISSUE THREAD

**Issue by Moyf** [Yaozhuwa/easy-typing-obsidian#253]
![image](https://github.com/user-attachments/assets/d79b1d22-e4da-4d12-8b57-cbdf723a7fc2)
如图，应该是在上次更新之后出现的（当前插件版本：5.5.4 ）

插件设置里没有启用 Print debug info，但是会时不时冒出来很多 `null`

基本都来自 247 行：
```js
// src/utils.ts
var DEBUG = true;
var print = (message, ...optionalParams) => {
  if (DEBUG) {
    console.log(message, ...optionalParams);
  }
};
```

> 这里是不是不应该 Debug = true 呀 🤔

**Comment by Yaozhuwa** [comment]
收到，周末修复

**Comment by Yaozhuwa** [comment]
V5.5.5 已修复
