### ISSUE TITLE
“严格换行模式下两个换行符”那个选项打开后，对quote(引用)这个md语法不起作用

### ISSUE THREAD

**Issue by loganoxo** [Yaozhuwa/easy-typing-obsidian#254]
如

```
> 第一行
> 第二行
```

效果：

> 第一行
>
> 第二行

**Comment by Yaozhuwa** [comment]
目前是这样，因为我自己习惯在 quote 中不用新行换行，quote 结尾用两个空格。不过这样的确有点不太统一。

后续会改的。

**Comment by loganoxo** [comment]
> 目前是这样，因为我自己习惯在 quote 中不用新行换行，quote 结尾用两个空格。不过这样的确有点不太统一。
> 
> 后续会改的。

好的，感谢
ps： 我用linter插件里的一个选项解决了这个问题
<img width="792" alt="SCR-20241102-qqcg" src="https://github.com/user-attachments/assets/ea5f8800-e62a-4b52-948f-30ad60bafeac">

**Comment by Yaozhuwa** [comment]
5.5.7 版本已经支持 Quote  块了
