### ISSUE TITLE
[FR] 对普通文本段落也支持 Ctrl+A 的二段操作逻辑

### ISSUE THREAD

**Issue by Moyf** [Yaozhuwa/easy-typing-obsidian#255]
Hi！ 很高兴看到最新更新里支持的「代码块编辑增强」：
![image](https://github.com/user-attachments/assets/adf16271-8c31-4714-94d4-91dbc91bb64d)

这让我想起了许久之前就念念不忘的一个想法：OB 里能否实现像 Notion 一样的全选操作：
1. 第一次按 `Ctrl+A` 时，选中当前段落
2. 第二次按 `Ctrl+A` 时，再全选全文

![94e404ae-31f6-46aa-aadc-8c2cb260253d](https://github.com/user-attachments/assets/0306a0d3-c4b4-4762-ba35-cf139849739b)

这次更新的代码块全选操作逻辑看起来很相似（**而且确实非常好用**），所以想问问能否拓展到对普通文本段落也支持这样的两段操作逻辑？

---

我之前曾经尝试过用其他插件配合实现类似功能，但是覆盖了 Ctrl+A 的快捷键导致在一些地方（比如搜索框）没法生效……
EasyTyping 的这种实现方式应该会更加易用！

**Comment by Yaozhuwa** [comment]
你说的普通文本段落，是指 Obsidian 中的一行文本吗？

**Comment by rayzer-hu** [comment]
> 你说的普通文本段落，是指 Obsidian 中的一行文本吗？

我想起来我之前写过一篇文章：
https://www.bilibili.com/read/cv22954345/

当时实现的效果：
![image](https://github.com/user-attachments/assets/ec6eeb2d-ab4c-41da-bd62-cb5de82af2e8)

(1) 第一次：选中当前行
(2) 第二次：拓展到当前行周围的 Block —— 使用的是 [Text Transporter](https://github.com/TfTHacker/obsidian42-text-transporter) 插件的 `Select current line/expand to block (SB)` 命令，相关功能大概在[这个代码](https://github.com/TfTHacker/obsidian42-text-transporter/blob/main/src/features/selectionFunctions.ts)里
(3) 第三次：全选全文

---

如果 (2) 实现起来麻烦的话，只有 (1) 和 (3) 其实也很够用了！

**Comment by Moyf** [comment]
> 你说的普通文本段落，是指 Obsidian 中的一行文本吗？

我想起来我之前写过一篇文章：
https://www.bilibili.com/read/cv22954345/

当时实现的效果：
![image](https://github.com/user-attachments/assets/a65b911a-915f-4dd1-a0b7-05252afa7de2)

(1) 第一次：选中当前行
(2) 第二次：拓展到当前行周围的 Block —— 使用的是 [Text Transporter](https://github.com/TfTHacker/obsidian42-text-transporter) 插件的 Select current line/expand to block (SB) 命令，相关功能大概在[这个代码](https://github.com/TfTHacker/obsidian42-text-transporter/blob/main/src/features/selectionFunctions.ts)里
(3) 第三次：全选全文

如果 (2) 实现起来麻烦的话，只有 (1) 和 (3) 其实也很够用了！

**Comment by Yaozhuwa** [comment]
OK，有空我会添加上这个功能。

**Comment by Moyf** [comment]
> OK，有空我会添加上这个功能。

太好了！感谢~~！

**Comment by Yaozhuwa** [comment]
5.5.6 版本支持了该功能，详情见更新日志。

**Comment by Moyf** [comment]
> 5.5.6 版本支持了该功能，详情见更新日志。

哇啊啊——终于有了！！盼着这个功能很久了一直实现不了，多亏了你！超级感谢！！！

---

当即更新试了一下！
![d2b8a322-6b5a-445d-b8ff-c939bdd25139](https://github.com/user-attachments/assets/f4fde694-7e42-4e81-9976-1e74a5d398cc)

第二段（选中全段）好像不生效，不知道是不是我对「文本块」的理解有误  0 0

**Comment by Yaozhuwa** [comment]
> > 5.5.6 版本支持了该功能，详情见更新日志。
> 
> 哇啊啊——终于有了！！盼着这个功能很久了一直实现不了，多亏了你！超级感谢！！！
> 
> 当即更新试了一下！ ![d2b8a322-6b5a-445d-b8ff-c939bdd25139](https://private-user-images.githubusercontent.com/4013062/386291414-f4fde694-7e42-4e81-9976-1e74a5d398cc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDUyODIsIm5iZiI6MTczMTYwNDk4MiwicGF0aCI6Ii80MDEzMDYyLzM4NjI5MTQxNC1mNGZkZTY5NC03ZTQyLTRlODEtOTk3Ni0xZTc0YTVkMzk4Y2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTcyMzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYwNjc0MGIwODk4YTIyYTM5NDZmMmU1ZmY0NGMyMGY3ZWNhNTdiMDhmNDE2ZTY5YzI2OGRhN2FjODVjMDRjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tjguq9FvEmwh4mUdp6_MkBW3lSPrNx8mG1YThLJ6eTA) [ ![d2b8a322-6b5a-445d-b8ff-c939bdd25139](https://private-user-images.githubusercontent.com/4013062/386291414-f4fde694-7e42-4e81-9976-1e74a5d398cc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDUyODIsIm5iZiI6MTczMTYwNDk4MiwicGF0aCI6Ii80MDEzMDYyLzM4NjI5MTQxNC1mNGZkZTY5NC03ZTQyLTRlODEtOTk3Ni0xZTc0YTVkMzk4Y2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTcyMzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYwNjc0MGIwODk4YTIyYTM5NDZmMmU1ZmY0NGMyMGY3ZWNhNTdiMDhmNDE2ZTY5YzI2OGRhN2FjODVjMDRjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tjguq9FvEmwh4mUdp6_MkBW3lSPrNx8mG1YThLJ6eTA) ](https://private-user-images.githubusercontent.com/4013062/386291414-f4fde694-7e42-4e81-9976-1e74a5d398cc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDUyODIsIm5iZiI6MTczMTYwNDk4MiwicGF0aCI6Ii80MDEzMDYyLzM4NjI5MTQxNC1mNGZkZTY5NC03ZTQyLTRlODEtOTk3Ni0xZTc0YTVkMzk4Y2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTcyMzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYwNjc0MGIwODk4YTIyYTM5NDZmMmU1ZmY0NGMyMGY3ZWNhNTdiMDhmNDE2ZTY5YzI2OGRhN2FjODVjMDRjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tjguq9FvEmwh4mUdp6_MkBW3lSPrNx8mG1YThLJ6eTA) [ ](https://private-user-images.githubusercontent.com/4013062/386291414-f4fde694-7e42-4e81-9976-1e74a5d398cc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDUyODIsIm5iZiI6MTczMTYwNDk4MiwicGF0aCI6Ii80MDEzMDYyLzM4NjI5MTQxNC1mNGZkZTY5NC03ZTQyLTRlODEtOTk3Ni0xZTc0YTVkMzk4Y2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTcyMzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYwNjc0MGIwODk4YTIyYTM5NDZmMmU1ZmY0NGMyMGY3ZWNhNTdiMDhmNDE2ZTY5YzI2OGRhN2FjODVjMDRjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tjguq9FvEmwh4mUdp6_MkBW3lSPrNx8mG1YThLJ6eTA)
> 
> 第二段（选中全段）好像不生效，不知道是不是我对「文本块」的理解有误 0 0

我的逻辑是，严格换行模式下相邻的文本行才算同一个文本块

**Comment by Moyf** [comment]
> 我的逻辑是，严格换行模式下相邻的文本行才算同一个文本块

原来如此，感谢解答！

---

如果提一个 PR ，添加一个「严格模式/普通模式」（后者可以在非严格模式下也选择相邻行）的设置，你觉得 OK 吗？
（不过我还没尝试过这么复杂的插件开发，只能试试看先x）

**Comment by Yaozhuwa** [comment]
> > 我的逻辑是，严格换行模式下相邻的文本行才算同一个文本块
> 
> 原来如此，感谢解答！
> 
> 如果提一个 PR ，添加一个「严格模式/普通模式」（后者可以在非严格模式下也选择相邻行）的设置，你觉得 OK 吗？ （不过我还没尝试过这么复杂的插件开发，只能试试看先x）

你把部分代码去掉，就支持普通模式了 https://github.com/Yaozhuwa/easy-typing-obsidian/blob/106c40ad4a297982cbf09f4aca6de5958ca3b820/src/main.ts#L984C1-L987C1

**Comment by Moyf** [comment]
> > > 我的逻辑是，严格换行模式下相邻的文本行才算同一个文本块
> > 
> > 
> > 原来如此，感谢解答！
> > 如果提一个 PR ，添加一个「严格模式/普通模式」（后者可以在非严格模式下也选择相邻行）的设置，你觉得 OK 吗？ （不过我还没尝试过这么复杂的插件开发，只能试试看先x）
> 
> 你把部分代码去掉，就支持普通模式了 https://github.com/Yaozhuwa/easy-typing-obsidian/blob/106c40ad4a297982cbf09f4aca6de5958ca3b820/src/main.ts#L984C1-L987C1

原来这么简单！
好的，那我就本地改改用啦~ 感谢！

**Comment by Yaozhuwa** [comment]
经过我的考虑，最终还是移除了严格换行模式的限制。现在，即使普通模式下，也支持两次Ctrl+A选中当前Block了

**Comment by Moyf** [comment]
> 经过我的考虑，最终还是移除了严格换行模式的限制。现在，即使普通模式下，也支持两次Ctrl+A选中当前Block了

太好了！不用每次更新插件都自己调整了哈哈哈~

对了，之前代码中看到对于「列表/任务」是特意不处理的，好奇一下这个是出于什么考虑呢？

**Comment by Yaozhuwa** [comment]
> 对了，之前代码中看到对于「列表/任务」是特意不处理的，好奇一下这个是出于什么考虑呢？

1. Outliner 插件已经对 Ctrl/Cmd+A 在列表时有处理了。
2. 列表的处理还没考虑好，后续可以再加，现在够用
3. Quote 部分的处理也没考虑好，后续再说

**Comment by Moyf** [comment]
原来是这样！明白了，感谢回复🙏
