### ISSUE TITLE
“引用符号 > 与文本之间自动空格”选项打开之后会影响callout的编辑转换功能

### ISSUE THREAD

**Issue by acrobatman** [Yaozhuwa/easy-typing-obsidian#257]
在我的自定义编辑转换规则中有一些callout的规则，例如：
">nol" auto convert to "> [note]+ |"

但是在开启“引用符号 > 与文本之间自动空格”选项之后，上述的规则就不生效了。
请问该如何解决这个问题？

**Comment by Yaozhuwa** [comment]
因为你的>后输入的时候自动加入空格了，你改下规则就好了，加个空格

**Comment by acrobatman** [comment]
谢谢，这个确实方便！
