### ISSUE TITLE
怎么实现输入回车后自动加上两个空格

### ISSUE THREAD

**Issue by shiyunxiao** [Yaozhuwa/easy-typing-obsidian#258]

**Comment by shiyunxiao** [comment]
![image](https://github.com/user-attachments/assets/ba836473-40e6-408a-803d-a9171fe3fd37)
尝试这么做没有成功

**Comment by Yaozhuwa** [comment]
你这规则我看不懂啊，加空格是在\n前加还是后加？

**Comment by Yaozhuwa** [comment]
V5.5.9 更新增强了 严格换行模式回车增强功能，添加了双空格模式，可能是你需要的效果
