### ISSUE TITLE
[BUG] 对 css 代码块的切换注释有误

### ISSUE THREAD

**Issue by Moyf** [Yaozhuwa/easy-typing-obsidian#259]
在 css 代码块中使用 `Easy Typing: toggle comment` 的时候，会输入 `//`，而 css 的注释应该是 `/**/` （光标放在中间）

![image](https://github.com/user-attachments/assets/98550add-0e65-48c7-a880-2dd8cc749bf9)

**Comment by Yaozhuwa** [comment]
OK，周末有空改

**Comment by Yaozhuwa** [comment]
新版本修复了~

**Comment by Moyf** [comment]
> 新版本修复了~

好耶！感谢~
