### ISSUE TITLE
#建议 对当前选中的文本格式化

### ISSUE THREAD

**Issue by Huang-Yujiong** [Yaozhuwa/easy-typing-obsidian#26]
作者，非常感谢你精心制作的插件。非常方便，特别感谢你。
然后是我自己的想法：有没有办法可以实现 **只对当前选中的文本格式化**。**类似于代码编辑器**那样的。我觉得会比格式化当前行利用率更高些。 非常感谢你的工作。
请开放捐赠通道。

**Comment by Yaozhuwa** [comment]
>然后是我自己的想法：有没有办法可以实现 只对当前选中的文本格式化。类似于代码编辑器那样的。

这个想法挺好的，我最近会加上

**Comment by Yaozhuwa** [comment]
v4.0.0 添加了对选中文本的格式化功能
