### ISSUE TITLE
[FR] 多行文本复制时能产生同级无序列表

### ISSUE THREAD

**Issue by xiaoxiang01a** [Yaozhuwa/easy-typing-obsidian#262]
### Feature Description
多行文本复制时能产生同级无序列表

### Example
![PixPin_2024-12-03_19-14-00](https://github.com/user-attachments/assets/6c78dfeb-2e27-464c-8042-642c360f405a)

**Comment by arieltutu** [comment]
虽然可以直接选择剩下的行，然后按`tab`键。

**Comment by xiaoxiang01a** [comment]
> 虽然可以直接选择剩下的行，然后按`tab`键。

@arieltutu ，你好，感谢回复，不过这样产生的好像不是列表格式，在上下移动和折叠方面与列表格式会有所不一样

**Comment by arieltutu** [comment]
> > 虽然可以直接选择剩下的行，然后按`tab`键。
> 
> @arieltutu ，你好，感谢回复，不过这样产生的好像不是列表格式，在上下移动和折叠方面与列表格式会有所不一样

不过要右键先选择变成bullet item 然后再tab
![{3351EC44-F074-468D-8D95-3AE93862BB7A}](https://github.com/user-attachments/assets/6f132314-182a-46ec-97d8-25cc763853a3)
这样确实有点麻烦

我也遇到没法在blockquote里面没法保持相同等级`>`黏贴的问题

**Comment by Yaozhuwa** [comment]
周末有空会我会实现一下~

**Comment by Yaozhuwa** [comment]
V5.5.11 已支持

![enhance-paste](https://github.com/user-attachments/assets/e7711e82-e24d-492e-b5ee-e46b2d9c76a3)

**Comment by xiaoxiang01a** [comment]
@Yaozhuwa ，感谢大佬，效率太快了🤩，完美的符合了我的需求，大佬辛苦了！
