### ISSUE TITLE
How to keep pasting multiple lines inside blockquotes or callouts in the same nested level? | 🇨🇳 在blockquote或者callout中黏贴多行文本，并保持其等级?

### ISSUE THREAD

**Issue by arieltutu** [Yaozhuwa/easy-typing-obsidian#263]
### Problem
Hello, I'm encountering an issue whenever tring to paste multiple lines content inside blockquotes or callouts. It seems that only the first line retains the correct `>` nested level, while the rest of lines do not.
- Nuance: I can still manually select all desirable text I want to be in `> `nested format and right-click to chose `Paragraph/Quote` in native obsidian menu. However, this process is a bit cumbersome, and **it doesn't still maintain the same nested level when more than one blockquote or callout(`> > `)**.
    - ![{A286F670-36A0-408C-BD1D-2FA496B5D01D}](https://github.com/user-attachments/assets/aa0364ae-4b77-468c-b7ec-5eb0afd85383)

### Example
- original example
  - ![{9CDB89E4-8CA5-4702-BA41-4C6F1D6B6BF4}](https://github.com/user-attachments/assets/dc5f4362-bfc7-4ecb-a245-9cb0eb6c6d81)

- what i get after pasting multiple lines
   - ![{CBE440D7-3032-4341-A635-1D1BB63F0107}](https://github.com/user-attachments/assets/3ee75517-3c6f-49c2-b0f4-f4e83aaa1507)

- what i want after pasting multiple lines **at once**
   - ![{A4A455C9-0FF9-4068-AF87-289B36150E18}](https://github.com/user-attachments/assets/a8cea6eb-0797-482e-b465-4e371ee6ba51)

---

大大好厉害，省了很多输入时间！买了杯咖啡小支持下☕

问题描述：
我在尝试黏贴多行内容时，发现无法保持多行内容在相同blockquote等级 `> ` 

- 想请教各位有什么办法可以设置？
- p.s. 可以通过选择多行然后右键选择`段落/quote`，**但是如果是高级别的blockquote或者多个嵌套的callout就不行了**(`> > `)。
    - ![{A286F670-36A0-408C-BD1D-2FA496B5D01D}](https://github.com/user-attachments/assets/aa0364ae-4b77-468c-b7ec-5eb0afd85383)

- 比如
  - ![{9CDB89E4-8CA5-4702-BA41-4C6F1D6B6BF4}](https://github.com/user-attachments/assets/dc5f4362-bfc7-4ecb-a245-9cb0eb6c6d81)

- 多行黏贴时，只能保持第一行在相同`> `等级
   - ![{CBE440D7-3032-4341-A635-1D1BB63F0107}](https://github.com/user-attachments/assets/3ee75517-3c6f-49c2-b0f4-f4e83aaa1507)

- 多行黏贴时想达到的效果，所有行都在相同`> `等级
   - ![{A4A455C9-0FF9-4068-AF87-289B36150E18}](https://github.com/user-attachments/assets/a8cea6eb-0797-482e-b465-4e371ee6ba51)

---
original text
```original
> [!note]
> 
```
multiple lines content to copy
```multiple lines content to cope and paste
- line 1
- line 2
- line 3
- line 4
```
paste at once to achieve
```
> [!note]
> - line 1
> - line 2
> - line 3
> - line 4
```

**Comment by Yaozhuwa** [comment]
这个需求和 #262 类似，周末有空会我会实现一下

**Comment by Yaozhuwa** [comment]
> 大大好厉害，省了很多输入时间！买了杯咖啡小支持下☕

@arieltutu 感谢支持！

**Comment by arieltutu** [comment]
> V5.5.11 已支持
> 
> ![enhance-paste](https://private-user-images.githubusercontent.com/28787183/397479620-e7711e82-e24d-492e-b5ee-e46b2d9c76a3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MzQyMTMsIm5iZiI6MTczNDYzMzkxMywicGF0aCI6Ii8yODc4NzE4My8zOTc0Nzk2MjAtZTc3MTFlODItZTI0ZC00OTJlLWI1ZWUtZTQ2YjJkOWM3NmEzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE4NDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYWI2ZjcxNDRhYzVkMTk1ZTY0N2ExMjY3N2JjN2U5YzA4Njg2ZTk5ZTE0ZTY2OWFjYzExODg0NTUwODJhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ff8tDtkRLm46qnjgp4QExP54CXXYaNB2Cdiro5iJv5E) [ ](https://private-user-images.githubusercontent.com/28787183/397479620-e7711e82-e24d-492e-b5ee-e46b2d9c76a3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MzQyMTMsIm5iZiI6MTczNDYzMzkxMywicGF0aCI6Ii8yODc4NzE4My8zOTc0Nzk2MjAtZTc3MTFlODItZTI0ZC00OTJlLWI1ZWUtZTQ2YjJkOWM3NmEzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE4NDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYWI2ZjcxNDRhYzVkMTk1ZTY0N2ExMjY3N2JjN2U5YzA4Njg2ZTk5ZTE0ZTY2OWFjYzExODg0NTUwODJhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ff8tDtkRLm46qnjgp4QExP54CXXYaNB2Cdiro5iJv5E) ![enhance-paste](https://private-user-images.githubusercontent.com/28787183/397479620-e7711e82-e24d-492e-b5ee-e46b2d9c76a3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MzQyMTMsIm5iZiI6MTczNDYzMzkxMywicGF0aCI6Ii8yODc4NzE4My8zOTc0Nzk2MjAtZTc3MTFlODItZTI0ZC00OTJlLWI1ZWUtZTQ2YjJkOWM3NmEzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE4NDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYWI2ZjcxNDRhYzVkMTk1ZTY0N2ExMjY3N2JjN2U5YzA4Njg2ZTk5ZTE0ZTY2OWFjYzExODg0NTUwODJhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ff8tDtkRLm46qnjgp4QExP54CXXYaNB2Cdiro5iJv5E) [ ](https://private-user-images.githubusercontent.com/28787183/397479620-e7711e82-e24d-492e-b5ee-e46b2d9c76a3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MzQyMTMsIm5iZiI6MTczNDYzMzkxMywicGF0aCI6Ii8yODc4NzE4My8zOTc0Nzk2MjAtZTc3MTFlODItZTI0ZC00OTJlLWI1ZWUtZTQ2YjJkOWM3NmEzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE4NDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYWI2ZjcxNDRhYzVkMTk1ZTY0N2ExMjY3N2JjN2U5YzA4Njg2ZTk5ZTE0ZTY2OWFjYzExODg0NTUwODJhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ff8tDtkRLm46qnjgp4QExP54CXXYaNB2Cdiro5iJv5E)

好快的升级！！！
🐄🍺

p.s.复制的多行文本如果不是`>`格式 还是有问题
![multiple lines in blockquote - Made with Clipchamp](https://github.com/user-attachments/assets/de60922f-ca93-48d9-8095-89ff2b8aeeee)

**Comment by arieltutu** [comment]
> V5.5.11 已支持
> 
> ![enhance-paste](https://private-user-images.githubusercontent.com/28787183/397479620-e7711e82-e24d-492e-b5ee-e46b2d9c76a3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MzczNjcsIm5iZiI6MTczNDYzNzA2NywicGF0aCI6Ii8yODc4NzE4My8zOTc0Nzk2MjAtZTc3MTFlODItZTI0ZC00OTJlLWI1ZWUtZTQ2YjJkOWM3NmEzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE5Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMzIwMDRhMzE2NzQ5MTBhNGQ3ZjM5MGFiNDExMmNhNWJhMjcyYjZlMzdkMDFmNjIxZjQ2Y2NmOGJhNzE2ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o1sZMKJjxFqrwk8gKaQOE6NWioxZiHqcm-GDXqVjs74) [ ](https://private-user-images.githubusercontent.com/28787183/397479620-e7711e82-e24d-492e-b5ee-e46b2d9c76a3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MzczNjcsIm5iZiI6MTczNDYzNzA2NywicGF0aCI6Ii8yODc4NzE4My8zOTc0Nzk2MjAtZTc3MTFlODItZTI0ZC00OTJlLWI1ZWUtZTQ2YjJkOWM3NmEzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE5Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMzIwMDRhMzE2NzQ5MTBhNGQ3ZjM5MGFiNDExMmNhNWJhMjcyYjZlMzdkMDFmNjIxZjQ2Y2NmOGJhNzE2ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o1sZMKJjxFqrwk8gKaQOE6NWioxZiHqcm-GDXqVjs74) 

好快的升级！🐄🍺
