### ISSUE TITLE
Add a CodeMirror 6 option for Live Preview mode

### ISSUE THREAD

**Issue by shaggyfeng** [Yaozhuwa/easy-typing-obsidian#28]
https://github.com/ArianaKhit/text-snippets-obsidian/issues/29#issuecomment-1011364585
Maybe this post can help.

**Comment by shaggyfeng** [comment]
https://codemirror.net/6/docs/migration/
This may help too

**Comment by Yaozhuwa** [comment]
Now you can update to v4.0.0 to support Live Preview mode
