### ISSUE TITLE
在使用windows 11 输入法的时候会出现没输入完就加空格的情况

### ISSUE THREAD

**Issue by Rao-Jupiter** [Yaozhuwa/easy-typing-obsidian#29]
如图

![图片](https://user-images.githubusercontent.com/70786042/153595331-ad3ea41e-62c9-4b58-8c6a-2662891d4250.png)

还没有输入完，有些字母就上屏了

**Comment by Yaozhuwa** [comment]
我在README中有说明，见：https://github.com/Yaozhuwa/easy-typing-obsidian#live-preview-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E8%BE%93%E5%85%A5%E6%B3%95%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by Kosette** [comment]
现在即便设置为source mode也不行了，能否将插件做成命令触发的方式，现在只有`format selected text`的指令可以用，希望添加格式化整篇笔记的命令，这样可以规避自动格式化的兼容问题。

**Comment by Yaozhuwa** [comment]
> 现在即便设置为source mode也不行了

现在是支持LivePreview模式的，Sourcemode也一样。只是需要用输入完成前不上屏的输入法就可以。你遇到的是这个问题吗？

> 希望添加格式化整篇笔记的命令

这个我周末就去加上，目前可以先用全选再`format selected text`暂时替代下

**Comment by Kosette** [comment]
> 如果输入法换不了，那只有在Legacy Mode的编辑器才不会有问题

嗯，没有办法更换输入法，所以寄希望于命令了

> 这个我周末就去加上，目前可以先用全选再`format selected text`暂时替代下

thanks，选中文本在安装了一些插件之后会变成选取单行或者单个段落，重复操作比较多，不然直接选取整篇也没太大问题

**Comment by Yaozhuwa** [comment]
> 嗯，没有办法更换输入法，所以寄希望于命令了

https://github.com/Yaozhuwa/easy-typing-obsidian/issues/32#issuecomment-1073927751

之后计划实现行级的排版格式化方案，应该也能解决一些问题，希望能对输入法问题解决不了的用户有一些帮助。

**Comment by Yaozhuwa** [comment]
行级排版格式化已添加，见新版本
![image](https://user-images.githubusercontent.com/28787183/160274035-6949e41e-f189-4ad1-925c-6c0efbe3a060.png)
