### ISSUE TITLE
为什么打中文的时候前面会自动出现一个英文首字母

### ISSUE THREAD

**Issue by 1205129045x** [Yaozhuwa/easy-typing-obsidian#30]
就像这样

https://user-images.githubusercontent.com/50540240/153693827-fe399f0b-8975-427d-9791-30a48c081dc2.mov

**Comment by 1205129045x** [comment]
我是最新版本的插件，开的实时预览模式，macos系统

**Comment by 11-check-it-out** [comment]
同样遇到了这个问题。win11，ob版本 v0.13.23

**Comment by Yaozhuwa** [comment]
https://github.com/Yaozhuwa/easy-typing-obsidian#live-preview-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E8%BE%93%E5%85%A5%E6%B3%95%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by 1205129045x** [comment]
> 我在README中有说明，见：https://github.com/Yaozhuwa/easy-typing-obsidian#live-preview-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E8%BE%93%E5%85%A5%E6%B3%95%E7%9A%84%E9%97%AE%E9%A2%98

看到了，谢谢
