### ISSUE TITLE
如何避免输入MAC地址或IPv6地址时候中间出现空格

### ISSUE THREAD

**Issue by clotong** [Yaozhuwa/easy-typing-obsidian#31]
像FF:FF:FF:FF:FF:FF或者IPv6格式xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx的时候避免中间产生空格

**Comment by xieyanknockout** [comment]
这类地址可以考虑用行内代码的格式吧？用撇号``括住。

**Comment by Yaozhuwa** [comment]
是的，这种还是直接用行内代码括住比较简单
