### ISSUE TITLE
Mac 系统求修复键入双拼时提前格式化排版问题

### ISSUE THREAD

**Issue by stormbuf** [Yaozhuwa/easy-typing-obsidian#32]
当我键入 `re'li` 时，会变成输出`r re'li`，当键入速度快时，会变成 ` re 热力 `。
<img width="1257" alt="iShot2022-03-19 22 11 07" src="https://user-images.githubusercontent.com/37621593/159124782-2b64753b-0368-4909-bdaf-98b3a853849a.png">
<img width="1261" alt="iShot2022-03-19 22 16 51" src="https://user-images.githubusercontent.com/37621593/159124787-73e85666-3f27-49f3-b25c-7c2d4180ae73.png">

可能有用的信息：
操作系统：macos Monterey  v12.3
Obsidian 版本：v0.13.33
插件版本：v4.0.1
输入法：搜狗输入法 + 小鹤双拼方案

**Comment by Yaozhuwa** [comment]
这个问题在readme中有说明：见 https://github.com/Yaozhuwa/easy-typing-obsidian#live-preview-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E8%BE%93%E5%85%A5%E6%B3%95%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by Yaozhuwa** [comment]
再说明下，我目前无法判断输入法的开始和结束，所以会导致在新版本编辑器下会有这个问题。在旧版本编辑器下就不会没有这个问题。

另外推荐使用输入完成前不上屏的输入法避免这个问题，windows下搜狗输入法是输入完才上屏的。

看你的截图是输入法在输入过程中字符就上屏了，所以会有这个问题。

下图是输入完成后再上屏的样子，供参考：
![image](https://user-images.githubusercontent.com/28787183/159176016-18b07d92-7240-4379-8c74-ed37ab2fa22e.png)

**Comment by stormbuf** [comment]
体验了几款输入法，Mac 系统可能限制了未输入完成就会上屏。

以 Obsidian 提供的 api 有没有办法以行为单位检测变动，并完成行级文本的排版格式化呢🤣

**Comment by stormbuf** [comment]
> 再说明下，我目前无法判断输入法的开始和结束，所以会导致在新版本编辑器下会有这个问题。在旧版本编辑器下就不会没有这个问题。
> 
> 另外推荐使用输入完成前不上屏的输入法避免这个问题，windows下搜狗输入法是输入完才上屏的。
> 
> 看你的截图是输入法在输入过程中字符就上屏了，所以会有这个问题。
> 
> 下图是输入完成后再上屏的样子，供参考： ![image](https://user-images.githubusercontent.com/28787183/159176016-18b07d92-7240-4379-8c74-ed37ab2fa22e.png)

体验了几款输入法，Mac 系统可能限制了未输入完成就会上屏。

以 Obsidian 提供的 api 有没有办法以行为单位检测变动，并完成行级文本的排版格式化呢🤣

**Comment by Yaozhuwa** [comment]
> 以 Obsidian 提供的 api 有没有办法以行为单位检测变动，并完成行级文本的排版格式化呢

感谢您的建议，这个想法非常好，是可以实现的。我之后会添加这个行级排版格式化的功能。

**Comment by Yaozhuwa** [comment]
行级排版格式化功能已添加，见新版本
![image](https://user-images.githubusercontent.com/28787183/160274012-867d158e-29ff-4e6e-b254-8f1adf08eec7.png)
