### ISSUE TITLE
Format selected 在没有选中文本的时候自动选择光标所在行

### ISSUE THREAD

**Issue by Benature** [Yaozhuwa/easy-typing-obsidian#33]
没有选中的时候手动format是没有任何变化了，建议在没有选中情况下像老版本那样format光标所在行。

**Comment by Yaozhuwa** [comment]
新版本中已经实现 v4.0.2
![image](https://user-images.githubusercontent.com/28787183/160273979-4958d6a7-53d3-435a-927f-ecddc4ab5bf2.png)

**Comment by Benature** [comment]
我发现 line mode 要成功启用的话，需要也启用 auto formating when typing，否则回车不会格式化（LP下）。
我直观以为auto formating是任意输入时候都在格式化，line mode是回车才格式化。按这种理解的话，应该只启用line mode也可以吧？

**Comment by Yaozhuwa** [comment]
我自己的想法是，Autoformating 是打开自动格式化的总开关，LineMode/CharMode 两种都是自动格式化的模式，默认CharMode，打开LineMode就是行模式，关闭就是CharMode。

**Comment by Benature** [comment]
OK，所以lineMode和charMode都不共存的喽（只是担心LP下启用charMode会浪费资源

**Comment by Yaozhuwa** [comment]
> 所以lineMode和charMode都不共存的喽

对啊，LineMode是每行输入结束后回车创建新行的时候进行一次格式化。CharMode是每次按键事件都会进行格式化。

> 只是担心LP下启用charMode会浪费资源

CharMode 的确计算资源消耗大一点，但是日常使用还是没问题的，我还没有碰到过因此卡顿的情况。

**Comment by Benature** [comment]
OK明白啦👌
