### ISSUE TITLE
Mac 在升级插件时报错：Plugin ID mismatch

### ISSUE THREAD

**Issue by 615lyw** [Yaozhuwa/easy-typing-obsidian#34]
![image](https://user-images.githubusercontent.com/28798938/160284730-19de33da-628e-4c76-8c6c-3f098995381e.png)

**Comment by Yaozhuwa** [comment]
现在还有问题吗，之前是我删除了一个release。

现在我这边windows和ubuntu系统更新都没问题。

你重新更新下试试，不行的话，卸载了重新安装应该可以了。
