### ISSUE TITLE
关于｜、注释和%的建议

### ISSUE THREAD

**Issue by Gnblink0** [Yaozhuwa/easy-typing-obsidian#35]
首先感谢开发者！您的easy typing和蚕大的ZH编辑增强 是对我ob中文输入改善最有效的插件

有两个小建议
1. 每次别名和图片大小都要切换成英文输入法输入`|`太麻烦了
希望可以增加一个功能，左或右为英文括号`[` / `]`时（即wiki链接），输入中文`｜`自动转化为英文`|`。
2. 以及ob中的注释是`%%`，请问是否可以效仿代码块和公式块的模式，输入四个5的时候自动转化成四个%，并且将光标置于中间？

再次感谢！

**Comment by Yaozhuwa** [comment]
> 1. 每次别名和图片大小都要切换成英文输入法输入`|`太麻烦了
>    希望可以增加一个功能，左或右为英文括号`[` / `]`时（即wiki链接），输入中文`｜`自动转化为英文`|`。
> 2. 以及ob中的注释是`%%`，请问是否可以效仿代码块和公式块的模式，输入四个5的时候自动转化成四个%，并且将光标置于中间？

1. 目前插件全角输入增强功能会对连续键入两个中文的`|`的情况变成一个英文的`|`。
2. obsidian的注释是有快捷键的，`Ctrl+/`就可以达到你要的效果
