### ISSUE TITLE
[#Enhancement] 设置中正则表达式的多行文本框支持拉伸

### ISSUE THREAD

**Issue by Benature** [Yaozhuwa/easy-typing-obsidian#36]
比如隔壁插件 https://github.com/hans/obsidian-citation-plugin 的设置中多行文本框是可以拉长的，这样子如果设置的正则表达式比较多的话，拉长文本框可以更一目了然一点，不用滑来滑去。

**Comment by Yaozhuwa** [comment]
感谢反馈，目前这样的确不方便，我周末改一下
