### ISSUE TITLE
[#Enhancement] 中文符号自动补齐

### ISSUE THREAD

**Issue by moryxsw** [Yaozhuwa/easy-typing-obsidian#38]
在使用英文字符时，类似[，"等字符可以自动补齐右侧符号，并且光标移至符号中间，不知道作者是否有计划添加中文字符的自动补齐。谢谢

**Comment by Yaozhuwa** [comment]
这个功能可以有，之前由于我自己没有这方面的需求，所以没有做这个功能。

清明假期我会加上这部分功能到插件的全角符号增强中。拟添加的符号有`《`, `“`，貌似就这两个符号。

**Comment by Yaozhuwa** [comment]
新版本已添加该功能 v4.0.5
