### ISSUE TITLE
选中文本后按下`{`会造成文本重复

### ISSUE THREAD

**Issue by Gnblink0** [Yaozhuwa/easy-typing-obsidian#40]
![image](https://user-images.githubusercontent.com/90372670/162553419-63682716-345f-4e83-8957-9420dc28d05d.png)
如图，选中一段字符后按下`{`键会造成文本被重复一遍，应该是和系统自带的补全英文标点（⬇️）重复了，有办法可以检测以避免冲突，或者考虑增加开启关闭选项吗？
![image](https://user-images.githubusercontent.com/90372670/162558184-15e9ff1e-19ee-479d-a580-3885d91a13ba.png)

**Comment by Yaozhuwa** [comment]
感谢反馈，我下周把这个功能去掉。
