### ISSUE TITLE
是否可以避免在波浪号和链接之间加空格？

### ISSUE THREAD

**Issue by twio142** [Yaozhuwa/easy-typing-obsidian#41]
使用过程中发现了一个相当偏门的 bug…

如果给一个链接加删除线，比如：
```markdown
~~[A link](https://link.com) Strike this line through~~
```

格式化后会在开头的波浪号和链接之间加空格。而加了空格之后不知为何 Obsidian 就不渲染删除线了…

![](https://i.imgur.com/ShipF70.png)

是否可以避免在链接和 Markdown 标记符号（如 `~`、`*`、`_`）之间加空格呢？

谢谢。

**Comment by Yaozhuwa** [comment]
感谢反馈，我下周修复下这个问题

**Comment by Yaozhuwa** [comment]
5.0.2 版本已修复这个 Bug， 现在 * ~ 都会被认为是软空格
