### ISSUE TITLE
LineMode没有效果

### ISSUE THREAD

**Issue by Lemon-cc-hang** [Yaozhuwa/easy-typing-obsidian#42]
就是打了一串文字和英文混合 回车之后 没有进行格式化

**Comment by Yaozhuwa** [comment]
我用windows 和 ubuntu 都没有问题诶。

你看下你设置对不对?
![image](https://user-images.githubusercontent.com/28787183/163676801-6d1d69e8-5689-4566-acbb-2c12194cbcba.png)

或者说你在什么情况下失效了，能稳定复现吗？

**Comment by Lemon-cc-hang** [comment]
> 我用windows 和 ubuntu 都没有问题诶。
> 
> 你看下你设置对不对? ![image](https://user-images.githubusercontent.com/28787183/163676801-6d1d69e8-5689-4566-acbb-2c12194cbcba.png)
> 
> 或者说你在什么情况下失效了，能稳定复现吗？

抱歉, 是我的问题, 我没有同时打开, 我就打开了下面那个开关

**Comment by jiapeng123456** [comment]
@Yaozhuwa 如果可以的话，把“两个开头都要打开”的说明，写到文档或插件设置里吧。我也遇到了同样的问题，看 issue 才知道这么使用的。

**Comment by Yaozhuwa** [comment]
> @Yaozhuwa 如果可以的话，把“两个开头都要打开”的说明，写到文档或插件设置里吧。我也遇到了同样的问题，看 issue 才知道这么使用的。

已添加，感谢您的建议！
