### ISSUE TITLE
是否可以避免在数字和:之间空格

### ISSUE THREAD

**Issue by kickTiger** [Yaozhuwa/easy-typing-obsidian#43]
类似于这种格式 22:58  ，会在冒号后增加空格，让格式全部混乱了。

是否含有数字的空格单独做个选项，自己可以控制开关？

**Comment by Yaozhuwa** [comment]
对于时间格式，可以在插件设置面板设置正则表达式
![image](https://user-images.githubusercontent.com/28787183/165690044-9395df46-7587-43c1-a5ac-1392d0f666a5.png)

**Comment by kickTiger** [comment]
谢谢！亲测有效，对于 22:58这种。
不过我的时间有时候是 **2022/04/28 19:50:29** 这种。在这个基础我新增了一个规则。给后来人借鉴。
```js
\d{2}:\d{1,2}
[0-9]{2}:[0-9]{2}:[0-9]{2}
```
