### ISSUE TITLE
全角符号输入增强无效，无法转换为英文符号

### ISSUE THREAD

**Issue by SDaoer** [Yaozhuwa/easy-typing-obsidian#45]
![GIF](https://user-images.githubusercontent.com/52645258/167296301-7707273c-b3a2-49f3-ab20-ab89ec287674.gif)

**Comment by Yaozhuwa** [comment]
我这边windows和ubuntu系统上都没有问题诶。

首先看下是否打开了自动格式化总开关。
![image](https://user-images.githubusercontent.com/28787183/167417403-a47b7996-0a75-4fd6-95b1-19348ee4c9e5.png)

如果还是不行的话，你可以提供下 Obsidian版本，插件版本以及系统信息，苹果电脑还是windows？
然后打开插件设置中的Debug按钮，Ctrl+Shift+I调出Obsidian控制台，然后复现你的问题，比如输入个多`》`,然后把控制台输出 的截图发我一下。

**Comment by Yaozhuwa** [comment]
即使是LineMode也要打开第一个总开关的。我可能在文档中没有说清楚。

**Comment by SDaoer** [comment]
你好，打开之后还是不奏效，这是打开之后我测试连续输入符号《的console输出：
![image](https://user-images.githubusercontent.com/52645258/167424642-41d06fe5-9831-49c0-9ac9-cd508b370fa7.png)

**Comment by SDaoer** [comment]
你好，打开之后还是不奏效，这是打开之后我测试连续输入符号《的console输出：
![image](https://user-images.githubusercontent.com/52645258/167424642-41d06fe5-9831-49c0-9ac9-cd508b370fa7.png)

**Comment by Yaozhuwa** [comment]
应该是输入法的问题

**Comment by SDaoer** [comment]
我的输入法是Windows自带的微软输入法，请问你使用的是什么输入法，我想去尝试一下看看能不能解决这个问题

**Comment by Yaozhuwa** [comment]
我是搜狗输入法
