### ISSUE TITLE
Mac平台，obsidian 0.14.6，live preivew mode， 中文输入有问题

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [Yaozhuwa/easy-typing-obsidian#46]
只要拼音输入时前边不是空格，就会触发easy-typing功能，但是会把拼音的前一两个字母当成正式文本，拼音也能正确输入。
![iShot_2022-05-19_21 13 31](https://user-images.githubusercontent.com/2133400/169302226-42b08bfd-4a62-467b-bb63-dce29befd79e.gif)

**Comment by Yaozhuwa** [comment]
这个问题在readme中有说明。
