### ISSUE TITLE
支持配置过滤markdown标题的格式化

### ISSUE THREAD

**Issue by CoolLiuzw** [Yaozhuwa/easy-typing-obsidian#47]
包括  H1 - H6 标题的格式化过滤，目前插件是有支持正则表达式过滤，能否支持配置？如果不能配置，能否支持？

如以下笔记
```
第 1 章 这是一章内容
```
因为格式化功能，会移除中文之间的空格，导致：
```
第 1 章这是一章内容
```

**Comment by Yaozhuwa** [comment]
一般情况下，可以在设置中关闭中文间自动移除空格的选项。
