### ISSUE TITLE
一些特殊的缩写能否避免大写

### ISSUE THREAD

**Issue by Jerrybaoyilei** [Yaozhuwa/easy-typing-obsidian#48]
抱歉，并不是很熟悉regular expression，请问是否可以做到一些常用的缩写，比如说:i.e., 和 e.g., 这种，可以避免e和g被大写？谢谢！

**Comment by Yaozhuwa** [comment]
目前本插件还做不到这种功能。因为书写的时候，i后面加的点号会认为是行的结束标点。

目前临时的解决办法是，在输入这些缩写前用快捷键 Ctrl+Tab 临时关闭插件的自动格式化功能，输入完后再使用快捷键打开自动格式化。（在行模式中不适用）。但是比较麻烦。

**Comment by Jerrybaoyilei** [comment]
明白！谢谢您的回答，辛苦了！

**Comment by Yaozhuwa** [comment]
可以用自定义正则表达式来解决这个问题，见： https://github.com/Yaozhuwa/easy-typing-obsidian/issues/5#issuecomment-1264682367

**Comment by Yaozhuwa** [comment]
5.0.3 插件支持了缩写的识别，不会对缩写格式化。缩写指的是符合正则表达式 `/([a-zA-Z]\.)+/` 的文本，如 i.e.
