### ISSUE TITLE
句号和冒号适配性问题——对时间文本/缩写的支持

### ISSUE THREAD

**Issue by lethefrost** [Yaozhuwa/easy-typing-obsidian#5]
比如，如果我想输入，
`3:00 p.m.`
在自动格式化开启的情况下会被强制改为
`3: 00 p. M.`，

如果想输入带大量日期的句子，就更加灾难，
`The meeting will be held from 11 a. M. To 3 p. M. On Thurs. The 15th.`

可以总结主要有两个问题导致了时间文本的不适配，
1. 缩写后的句号会导致之后的英文字母强行空格并且大写。除了a.m./p.m./星期/月份等缩写，还有其他常用拉丁文缩写比如etc./et al./vs./i.e./e.g./c.和各种专业术语的缩写后都带句号，但许多缩写出现在句子中间，其后不应该大写。
2. 冒号后的数字会被插入空格

鉴于各种缩写种类繁多，我觉得一一纳入数据库做特殊判断是否不太现实，能否在插件错误判断大小写和空格的时候，支持手动修改？比方说，在用户退格删除了刚被插件修改、产生变化的字之后，插件可以判断用户希望手动更改，于是将不介入强制修改用户下次输入的字？而且现在是我只要在这行输入一个字，就会对整行格式化，能否做到仅仅格式化当前光标所在/当前刚刚输入的这个字，这样的话哪怕输入后续内容、进行更改也不怕这一行之前输入过的文本全都一夜回到解放前了？而且让插件每次键入只查当前最新键入字，应该对性能也有所提升，不用去遍历整行了？如果用户想整行或者全文格式化的话就直接调用命令也不是很麻烦。

谢谢！迄今已经是很优秀的插件了，确实让大部分时候的码字更舒服轻松了，真的很棒！

**Comment by Yaozhuwa** [comment]
我的确没考虑好这种情况，你的想法很棒，我之后会做一下尝试。
对你现在遇到的问题，有一个临时的解决方案：当你想要输入这种缩写的时候，你可以使用快捷键 Ctrl+Tab 关闭插件的自动格式化功能，然后在下一行输入的时候再快捷键重新打开插件的自动格式化功能，由于自动格式化只会影响当前行，所以对上一行不会有影响。
![image](https://user-images.githubusercontent.com/28787183/120885288-b8fd7600-c61a-11eb-9f29-d2498ecfe11f.png)

**Comment by lethefrost** [comment]
> 我的确没考虑好这种情况，你的想法很棒，我之后会做一下尝试。
> 对你现在遇到的问题，有一个临时的解决方案：当你想要输入这种缩写的时候，你可以使用快捷键 Ctrl+Tab 关闭插件的自动格式化功能，然后在下一行输入的时候再快捷键重新打开插件的自动格式化功能，由于自动格式化只会影响当前行，所以对上一行不会有影响。
> ![image](https://user-images.githubusercontent.com/28787183/120885288-b8fd7600-c61a-11eb-9f29-d2498ecfe11f.png)

谢谢，期待新版本的改进！有什么可以帮忙的地方请告诉我:D

**Comment by edentsai** [comment]
在輸入 Emoji 也遇到了相同的問題，提供參考：

```diff
- :memo:
+ : memo :
```

**Comment by Yaozhuwa** [comment]
1. 我目前的想法是增加一个用户自定义正则表达式的功能，对正则表达式匹配的文本，不进行格式化（自动空格啥的）。
    - 比如对emoji的支持：可以使用 `:\w*:` 
    - 对于时间，可以用 `\d{2}:\d{1,2}`

2. 对于缩写或者特定文本，我目前的想法是，用户自己维护一个特定表达的文件。
如需增加缩写内容，则在文件中加一行，如`i.e.`。程序实现方面的话，内部可以尝试用正则还有树的数据结构来实现快速检索。
类似于 lethefrost 提的一一纳入数据库做特殊判断的方式。在这个特殊表达数据库不特别大的时候，应该是没有问题的。

正则表达式：https://javascript.ruanyifeng.com/stdlib/regexp.html#toc15

**Comment by Yaozhuwa** [comment]
> 在輸入 Emoji 也遇到了相同的問題，提供參考：
> 
> ```diff
> - :memo:
> + : memo :
> ```

v3.2.0 版本已经支持自定义正则表达式，你可以在设置面板添加正则表达式 `:\w*:`即可识别emoji，在输入的时候，你需要先输入两个冒号，然后在中间键入emoji名称。

**Comment by lethefrost** [comment]
> > 在輸入 Emoji 也遇到了相同的問題，提供參考：
> > ```diff
> > - :memo:
> > + : memo :
> > ```
> 
> v3.2.0 版本已经支持自定义正则表达式，你可以在设置面板添加正则表达式 `:\w*:`即可识别emoji，在输入的时候，你需要先输入两个冒号，然后在中间键入emoji名称。
> 
> v3.2.1 现在我测试了下，自定义正则表达式的功能还有点问题，先不要使用。我这两天会修复。

😂 谢谢你如此快速的开发和响应！！感动
我觉得正则表达式是不是稍微还麻烦了点儿？毕竟我觉得很难提前穷尽所有可能性，而如果要每个用户手动配置每一项的话也增加了一些使用成本，变得略繁琐了一些。

说起来，这几天又发现了一些bug（可能不算）或者使用场景，再提几个小建议～
- 最近发现输入email地址会变成这样`Firstname. Lastname@address. Com`，是不是这个不太适合用正则黑名单来排除呀，毕竟邮箱名和域名中`.`的数量是不定的，不知道会不会误伤前后的句子？
- 如果遇到单独一个的`i`要不要考虑让它自动大写？好像word，google doc和mac自带的拼写纠正都会这么干。这个好像还挺方便的。

唔唔……我在想，我之前提到的

> 鉴于各种缩写种类繁多，我觉得一一纳入数据库做特殊判断是否不太现实，能否在插件错误判断大小写和空格的时候，支持手动修改？比方说，在用户退格删除了刚被插件修改、产生变化的字之后，插件可以判断用户希望手动更改，于是将不介入强制修改用户下次输入的字？而且现在是我只要在这行输入一个字，就会对整行格式化，能否做到仅仅格式化当前光标所在/当前刚刚输入的这个字，这样的话哪怕输入后续内容、进行更改也不怕这一行之前输入过的文本全都一夜回到解放前了？而且让插件每次键入只查当前最新键入字，应该对性能也有所提升，不用去遍历整行了？如果用户想整行或者全文格式化的话就直接调用命令也不是很麻烦。

这个是不是实现起来比较麻烦或者不太可行呀？如果用退格判断不太现实的话，用户撤销（cmd/ctrl+z）了刚刚插件的自动更改可以作为判断插件自动修改错了的依据吗？
或者我有个新想法，像是\`\`里代码的内容是不会被插件修正的，如果可以实现每次仅仅格式化当前光标所在单词而不是遍历整行，用户有特殊的句子元素比方说缩写，时间，emoji或者邮箱，可以先在代码段里打好，然后再取消代码环境？
甚至也许可以定义一种新的语法，某些字符之间的部分不会被格式化，这些语法字符不会在preview里被渲染出来，再加个快捷键可以快速插入一组字符，或者把某些text surround起来？这个是不是实现起来稍微简单些，原本的思路就都不用改变了。

**Comment by lethefrost** [comment]
说起来，这里有另一个插件（作者人也很好！）
https://github.com/renmu123/obsidian-auto-pair-chinese-symbol
@renmu123 感觉你们的一部分业务有重叠，要不要考虑merge一下一起干？

**Comment by Yaozhuwa** [comment]
>最近发现输入email地址会变成这样Firstname. Lastname@address. Com，是不是这个不太适合用正则黑名单来排除呀，毕竟邮箱名和域名中.的数量是不定的，不知道会不会误伤前后的句子？

现在v3.2.2的正则表达式的一些bug已经修复，可以正常使用了，这个邮箱可以用正则来忽略：`[a-zA-Z0-9_\-.]+@[a-zA-Z0-9_\-.]+`。

![image](https://user-images.githubusercontent.com/28787183/122109822-614bdf80-ce50-11eb-83e4-7f727ad1edfc.png)
>甚至也许可以定义一种新的语法，某些字符之间的部分不会被格式化，这些语法字符不会在preview里被渲染出来，再加个快捷键可以快速插入一组字符，或者把某些text surround起来？这个是不是实现起来稍微简单些，原本的思路就都不用改变了。

这个也可以用正则表达式来实现：你可以添加 `{{.*?}}`这个正则，插件就会忽略双花括号内部的内容，就不会被格式化。

>鉴于各种缩写种类繁多，我觉得一一纳入数据库做特殊判断是否不太现实，能否在插件错误判断大小写和空格的时候，支持手动修改？比方说，在用户退格删除了刚被插件修改、产生变化的字之后，插件可以判断用户希望手动更改，于是将不介入强制修改用户下次输入的字？而且现在是我只要在这行输入一个字，就会对整行格式化，能否做到仅仅格式化当前光标所在/当前刚刚输入的这个字，这样的话哪怕输入后续内容、进行更改也不怕这一行之前输入过的文本全都一夜回到解放前了？而且让插件每次键入只查当前最新键入字，应该对性能也有所提升，不用去遍历整行了？如果用户想整行或者全文格式化的话就直接调用命令也不是很麻烦。

大小写撤销的功能可以去 #6 讨论，我目前有实现的思路了。没有意外的话之后会更新这个功能。

**Comment by Yaozhuwa** [comment]
> 说起来，这里有另一个插件（作者人也很好！）
> https://github.com/renmu123/obsidian-auto-pair-chinese-symbol
> @renmu123 感觉你们的一部分业务有重叠，要不要考虑merge一下一起干？

目前不考虑，感觉多人协作写代码太麻烦了。。

**Comment by Benature** [comment]
> 说起来，这里有另一个插件（作者人也很好！）
> https://github.com/renmu123/obsidian-auto-pair-chinese-symbol

哈哈，我之前看到有另外一个插件也是有功能重叠的 https://github.com/Natumsol/obsidian-pangu

**Comment by sylph520** [comment]
挺好的扩展👍。最近我也发现了这个问题，其实有些英文常用的缩写都会触发这个问题，比如i.e., e.g., w.r.t, 这些常用的缩写希望以后可以内置这些规则，或者做成toggle的选项也行吧。🤣w发现了这个问题，其实有些英文常用的缩写都会触发这个问题，比如i.e., e.g., 这些常用的缩写希望以后可以内置这些规则，或者做成toggle的选项也行吧。🤣

**Comment by Yaozhuwa** [comment]
缩写的支持很难，目前没有想到好的办法。

**Comment by sylph520** [comment]
> 缩写的支持很难，目前没有想到好的办法。 如果经常需要打缩写的，建议关闭英文文本和标点间自动空格的功能。

好的 🤣

**Comment by Yaozhuwa** [comment]
> 挺好的扩展👍。最近我也发现了这个问题，其实有些英文常用的缩写都会触发这个问题，比如i.e., e.g., w.r.t, （这三个的正则表达式是什么额，菜鸟试了一会没试出来，不知道是不是和标点文本空格的选项有关😥）这些常用的缩写希望以后可以内置这些规则，或者做成toggle的选项也行吧。🤣w发现了这个问题，其实有些英文常用的缩写都会触发这个问题，比如i.e., e.g., 这些常用的缩写希望以后可以内置这些规则，或者做成toggle的选项也行吧。🤣

5.0 版本后，在正则表达式区域加上以下两个正则应该能解决大部分关于缩写和时间的错误格式化情况：
```
\d{1,2}:\d{2}|+-
 ([a-zA-Z]\.)+|--
```

**Comment by Yaozhuwa** [comment]
5.0.3 插件支持了缩写的识别，不会对缩写格式化。缩写指的是符合正则表达式 `/([a-zA-Z]\.)+/` 的文本，如 i.e.
