### ISSUE TITLE
希望能增加中文引号自动转换为直角引号的功能

### ISSUE THREAD

**Issue by ribber** [Yaozhuwa/easy-typing-obsidian#50]
例如，输入 `’` 自动转换为 `「`，输入`”` 自动转换为 `『`

**Comment by Yaozhuwa** [comment]
目前全角字符增强已经有别的功能占用了，比如两个`‘`变成 `''`。你说的这种功能有别的插件可以实现。

**Comment by Yaozhuwa** [comment]
EasyTyping 5.0 版本后，可以通过添加自定义转换规则实现。有多种实现方法，下面描述一种，

在打开符号自动配对的设置选项后，在自定义转换规则处添加一条
<img width="777" alt="image" src="https://user-images.githubusercontent.com/28787183/193465532-c0488bf5-2d2b-4fb2-b437-ae9f639e39f9.png">
然后，在输入过程中，输入“，由于符号自动配对，会直接得到`“|”`，然后按一个空格键，转换规则生效，即可得到`「|」`，效果如下：
![issue50](https://user-images.githubusercontent.com/28787183/193465686-24b94b2a-fda5-4828-8fae-7a48624a954c.gif)
