### ISSUE TITLE
一个正则问题

### ISSUE THREAD

**Issue by zhl111** [Yaozhuwa/easy-typing-obsidian#53]
我发现在输入“.git”这类文字时，这个插件会自动空格，所以我在正则里加入这个词
![image](https://user-images.githubusercontent.com/29135984/177228213-8c76f3de-7aca-4f51-840c-e0adbc7e3ccd.png)
但是我发现，在我回车后会多出来一个git，譬如回车前是：“http://xxxx/upgit”，回车后就变成：“http://xxxx/upgit git”
这个如何解？

第二个请求：网址也会自动发生改变。这能否做成默认的不应更改的部分？

**Comment by Yaozhuwa** [comment]
> 我发现在输入“.git”这类文字时，这个插件会自动空格

建议把 .git 这类文字放到代码块或者行内代码的语法中，如 `.git` 文件，本插件对代码块和行内代码内部的文字不会格式化。

> 第二个请求：网址也会自动发生改变。这能否做成默认的不应更改的部分？

由于目前本插件自定义正则的优先级会比网址识别的优先级高，所以会出现你的情况。一般不建议直接在自定义正则部分添加单词。

**Comment by Yaozhuwa** [comment]
> 第二个请求：网址也会自动发生改变。这能否做成默认的不应更改的部分？

EasyTyping 5.0 后网址的识别由自定义表达式实现，现在默认的正则识别网址应该效果比较好了，如果对某些网址不适用可以自己定义正则表达式识别。
