### ISSUE TITLE
[BUG] 行内代码块与中文拼音输入的问题

### ISSUE THREAD

**Issue by Xrtero** [Yaozhuwa/easy-typing-obsidian#55]
# 环境
OS : macOS 12.4
输入法： 系统自带
仅打开：
- 全角符号输入增强
- 行内代码块和文本间空格
- 行内公式和文本间空格

# 问题描述
在紧挨着行内代码块输入时会出现重复第一个字符，例如如下输入：
`some code`z在这里
zai 变成了 zzai

**Comment by Xrtero** [comment]
当关闭`行内代码块和文本间空格`时能够正常输入

**Comment by Yaozhuwa** [comment]
建议使用行模式。这种在光标前加空格的情况都会触发这种输入问题。

**Comment by Yaozhuwa** [comment]
重复的 issue， 见 #29
