### ISSUE TITLE
对于双反引号的行内代码的支持

### ISSUE THREAD

**Issue by jiapeng123456** [Yaozhuwa/easy-typing-obsidian#57]
感谢做出这么好的插件。

在使用时“在行内代码和文本之间加空格”功能时，对于下面的 case，插件可能会出现误操作。
（因为反引号多了，显示不是很正常，所以下面我使用单引号来代替反引号）

需求：
我这里的想输入的是 `. （一个反引号和一个点），所以用了4个反引号进行包围它。

输入：'' '.''
（上面是：两个反引号，一个空格，一个反引号，一个点，两个反引号）
格式化后：'' '.' '
（上面是：两个反引号，一个空格，一个反引号，一个点，一个反引号，**一个空格**，一个反引号）

问题：格式化后，在最后一个反引号前，加了一个空格。

**Comment by Yaozhuwa** [comment]
对于代码块的解析，这里只做了三反引号(代码块)和单反引号（行内代码）的语法解析。所以双反引号的情况会有错误。

**Comment by Yaozhuwa** [comment]
重复的 issue， 见 #29

**Comment by Yaozhuwa** [comment]
的确是个问题，主要是加上双反引号的行内代码块解析后情况会变得特别复杂。如果只是为了显示 \`. 的话，可以用反斜杠，如下
```
\`.
```

**Comment by Yaozhuwa** [comment]
5.0.7 能正确解析双反引号的行内代码了
