### ISSUE TITLE
Can the automatic capitalization of English initials be revoked? 英文首字母自动大写可否撤销？

### ISSUE THREAD

**Issue by zzdcgg** [Yaozhuwa/easy-typing-obsidian#6]
如题。英文首字母自动大写在大多数情况下都很有用，有的时候想保持首字母小写，能否保留撤销大写的选项？比如Word里也会首字母自动大写，但是可以撤销。感谢！

**Comment by Yaozhuwa** [comment]
现在还不支持，以后会支持这个功能。你可以先关掉这个功能。
此外，v3.2.1 版本的正则表达式功能有bug，不要使用。。
我这几天先修复自定义正则表达式的bug，然后会做一个智能标点的功能，到时候也会支持撤销大写。

**Comment by zzdcgg** [comment]
好的，谢谢！

**Comment by Yaozhuwa** [comment]
v3.3.0版本已支持该首字母大写的撤销功能。只需要ctrl z即可。

**Comment by zzdcgg** [comment]
棒！
