### ISSUE TITLE
[BUG] “链接与文本智能空格”不智能，不能根据显示文本来添加空格

### ISSUE THREAD

**Issue by user30535** [Yaozhuwa/easy-typing-obsidian#60]
复制

```
啦[[test|啦]]啦

啦[[啦|test]]啦
```

两个链接的显示文本分别为`啦`和`test`，所以前者左右不应有空格，后者左右应有空格。但是得到的结果是

![image](https://user-images.githubusercontent.com/108653772/185987445-6fa843a1-65ae-4224-ac48-ed21ff9b05d7.png)

**Comment by Yaozhuwa** [comment]
哈哈哈，感谢帮忙找 bug，之前做这个功能的时候没考虑别名的情况😅

**Comment by user30535** [comment]
hhh 这个功能对我还挺重要的因为我经常要用display text。

感谢你做的插件！

**Comment by Yaozhuwa** [comment]
已更新，你看看是否解决了你的问题

**Comment by user30535** [comment]
解决了！真的非常感谢！
