### ISSUE TITLE
[Feature Request] Linter 工具

### ISSUE THREAD

**Issue by user30535** [Yaozhuwa/easy-typing-obsidian#61]
Easy-typing 提供的文本格式化功能只在编辑的时候起作用。不知道可否考虑做一个 linter 工具，对当前 note 或者 vault 里所有的 note 整个进行格式化呢？

插件市场已经有一些其他的 linter 工具，但是针对在中文与英文之间添加空格这个需求还是 Easy-typing 做的最好，比如 easy-typing 可以根据链接的显示文本来插入空格。

另外考虑到现在 Easy-typing 不支持移动端，在移动端上编辑的文本同步到电脑端以后也需要用 Easy-typing 的 linter 工具进行格式化。

请问作者是否可以添加一个 linter 工具，为文本格式化这个需求提供一个完整的解决方案呢？

超级感谢！

**Comment by Yaozhuwa** [comment]
对当前 note 进行全文格式化的功能已经有了。
<img width="945" alt="image" src="https://user-images.githubusercontent.com/28787183/186556615-7b0d2e3f-e9fc-494f-ad15-c5144af908cb.png">
