### ISSUE TITLE
[BUG?] 引号和代码之间不需要空格吧

### ISSUE THREAD

**Issue by user30535** [Yaozhuwa/easy-typing-obsidian#63]
Easy-typing 会自动在 ``"`abc`"``  的代码两侧加空格变成 ``" `abc` "``（同理``“`abc`”``会变成``“ `abc` ”``），但不会改变``(`abc`)``。请问这个行为符合预期吗？

我觉得引号和代码之前不需要加空格，您觉得呢？而且既然括号和代码之间没有空格，那么引号和代码之间也没有必要加空格吧。

感谢！

**Comment by Yaozhuwa** [comment]
感谢反馈，下次更新会修复这个问题
