### ISSUE TITLE
请求把“全角符号自动补全”功能分离出来 #Enhancement

### ISSUE THREAD

**Issue by zhangweijian97** [Yaozhuwa/easy-typing-obsidian#64]
#38 

这个功能造成很大困扰，比如输入一个前引号“，自动补全了，”。但是我过了几行又需要引号的时候，第一个打出来的就是后引号。但我想要的是前引号。

希望能把这个功能从“全角符号输入增强”中分离出来。这个增强功能的其他功能都很好用。就这个自动补全整得头秃。

**Comment by zhangweijian97** [comment]
好耶！👍🏻

**Comment by Yaozhuwa** [comment]
4.0.8 版本已修复~
