### ISSUE TITLE
请问如何避免将 \<div 格式化为 \ <div ?

### ISSUE THREAD

**Issue by tanzhou2002** [Yaozhuwa/easy-typing-obsidian#67]

**Comment by tanzhou2002** [comment]
在obsidian中会影响后面的代码块

**Comment by Yaozhuwa** [comment]
这是自定义正则规则生效
<img width="618" alt="image" src="https://user-images.githubusercontent.com/28787183/189580423-9d28f0d7-d083-4e76-9b77-41f46b93ad89.png">

**Comment by tanzhou2002** [comment]
非常感谢，之前在写html标签的时候使用 \<div> 的不良写法，现在已经改为了 `<div>`
