### ISSUE TITLE
「全角符号输入增强」可否考虑增加对中文括号 「」的支持

### ISSUE THREAD

**Issue by aaazz47** [Yaozhuwa/easy-typing-obsidian#69]
您好，非常感谢您开发了这么一个方便中文用户的插件。尤其是「全角符号输入增强」能够极大的简化 markdown 语法在中文环境中来回切换输入状态的烦恼。
不过和我一样把输入法中文方括号 `【】` 改为 `「」` 的用户来说，在使用类似 `「「」」` 这类用法的时候就不会自动格式化为 `[[]]` 了。因此作为白嫖怪，斗胆发了这篇反馈，期望后续版本更新的时候能够实现对这种括号的支持。
非常感谢！

**Comment by Yaozhuwa** [comment]
可以的，下个版本会支持。

**Comment by Yaozhuwa** [comment]
新版本可以通过设置自定义选中文本情况下的转换规则来实现~

**Comment by aaazz47** [comment]
> 

多谢提醒，我已经更新最新版了。再次感谢

**Comment by aaazz47** [comment]
> EasyTyping 5.0 新版本可以通过设置自定义选中文本情况下的转换规则来实现~

多谢提醒，我已经更新最新版本了。感谢大神
