### ISSUE TITLE
无法更新至最新版且卸载后无法重新安装

### ISSUE THREAD

**Issue by 615lyw** [Yaozhuwa/easy-typing-obsidian#71]
<img width="993" alt="image" src="https://user-images.githubusercontent.com/28798938/192073675-6a1f3956-4ce0-4f2d-82a7-d4ab4749ed14.png">

<img width="942" alt="image" src="https://user-images.githubusercontent.com/28798938/192073727-6158a440-8dbe-4c9e-bc99-2150d233d00e.png">

**Comment by Yaozhuwa** [comment]
的确有一个5.0.0版本的大更新，但是我还没有一些小地方要修改。预计周一前发布~

**Comment by llity** [comment]
测试无法安装

**Comment by Yaozhuwa** [comment]
额，再等等，晚上就出了。。

**Comment by Yaozhuwa** [comment]
EasyTyping 5.0 已上传，现在可以正常更新了~

**Comment by 615lyw** [comment]
已解决（发现作者也开始用 Mac 了😁）
