### ISSUE TITLE
开启正则表达式检查后，每次输入右上角都会弹出内容不匹配正则的提示

### ISSUE THREAD

**Issue by tanzhou2002** [Yaozhuwa/easy-typing-obsidian#72]

**Comment by Yaozhuwa** [comment]
你可以把你设置中的自定义正则截图一下看看吗，应该是你自定义的正则有问题

**Comment by Yaozhuwa** [comment]
如果你是更新后出现问题的，那是因为 5.0 版本的配置文件和旧版本不兼容，请先卸载旧版本，再重新安装~

**Comment by tanzhou2002** [comment]
我自己没有写自定义正则，原本自带的没有删除出现这种情况
现在我直接把自定义正则关闭了，就没啥问题了

**Comment by tanzhou2002** [comment]
我是直接升级的，现在我重新安装了，使用默认配置也没啥问题了
