### ISSUE TITLE
在kanban插件内无法使用。

### ISSUE THREAD

**Issue by qqhxx** [Yaozhuwa/easy-typing-obsidian#73]
RT.

**Comment by Yaozhuwa** [comment]
目前只能在markdown视图中使用。本插件目前是监控 CodeMirror6 的编辑器的状态改变，而在这些非 markdown 的视图下这个接口检测不到，我目前也不知道如何实现:cry:

**Comment by qqhxx** [comment]
好的，谢谢。^_^
