### ISSUE TITLE
自定义转换规则支持正则符号，比如换行符\n等

### ISSUE THREAD

**Issue by calmwaves111** [Yaozhuwa/easy-typing-obsidian#74]

**Comment by Yaozhuwa** [comment]
插件设计上是支持的，写代码的时候大意了，是个小bug，这两天就修复。

**Comment by Yaozhuwa** [comment]
5.0.1 版本自定义转换规则支持换行。

这个自定义转换规则之后也可以做成使用正则匹配的形式，但是具体形式我还没有想清楚。比如稍复杂点的正则替换规则应该以怎样的形式设置。。

**Comment by irrealizable** [comment]
> 

![image](https://user-images.githubusercontent.com/56907077/197330026-926a95cd-2f8c-4314-8642-1c77ff37b9ba.png)

这个要怎么用呢，我写成这样没有效果，还是显示为\n

**Comment by Yaozhuwa** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/56907077/197330026-926a95cd-2f8c-4314-8642-1c77ff37b9ba.png)
> 
> 这个要怎么用呢，我写成这样没有效果，还是显示为\n

直接按回车就行。

**Comment by irrealizable** [comment]
> 

好的明白了，很方便
