### ISSUE TITLE
增强删除功能无效

### ISSUE THREAD

**Issue by allworldg** [Yaozhuwa/easy-typing-obsidian#75]
Problem: 直接用backspace删除尾部符号时无法同时删除对应的配对符号。
Version: obsidian: v0.14.15 . plugin: 5.0.2

![image](https://user-images.githubusercontent.com/48782874/193975505-05f473bd-cf2d-4317-9eae-bda6087da63a.png)

**Comment by Yaozhuwa** [comment]
配对删除指在配对符号内无内容，并且光标在配对符号之间的时候，退格键删除会将配对符号一起删除。如 ”|“ （ | 代表光标位置），退格键会删除双引号。

对于 ”“| （光标在配对符号之后的情况），可以设置自定义删除规则来实现一键删除。

**Comment by allworldg** [comment]
@Yaozhuwa 谢谢，我以为是指里面有内容也能删除。不好意思。
