### ISSUE TITLE
使用Latex Suite插件时遇到冲突

### ISSUE THREAD

**Issue by cangming99** [Yaozhuwa/easy-typing-obsidian#77]
当我使用Latex Suite插件时，输入/，末尾会多出一个/
![image](https://user-images.githubusercontent.com/85931842/194190120-f9c30a37-0dae-4b45-a155-61fe1013d50a.png)
如果我把Easy Typing插件关闭后，就不会发生这种情况
![image](https://user-images.githubusercontent.com/85931842/194190164-0b62236c-5511-472b-a92a-57e7f17788b6.png)
我排查不出是Easy Typing的哪个功能导致的，请问有什么解决办法吗

**Comment by Yaozhuwa** [comment]
我修复了一下，5.0.4 版本应该不会冲突了。

**Comment by cangming99** [comment]
> 我修复了一下，5.0.4 版本应该不会冲突了。

目前使用起来没问题，感谢！
