### ISSUE TITLE
文件路径会自动增加空格，这能否像网址一样排除在外？

### ISSUE THREAD

**Issue by zhl111** [Yaozhuwa/easy-typing-obsidian#78]
举例：(file:///D:%5C005-Calibre_书库%5CPeng%20Wen%20Sheng%5CJian%20Xing%20Jian%20Yuan%20De%20Hong%20Li%20_Xun%20(830)%5CJian%20Xing%20Jian%20Yuan%20De%20Hong%20Li%20-%20Peng%20Wen%20Sheng.epub)

**Comment by Yaozhuwa** [comment]
```
(https?:\/\/|ftp:\/\/|obsidian:\/\/|zotero:\/\/|www.)[^\s（）《》。,，！？;；：“”‘’\)\(\[\]\{\}']+|++
```
将自定义正则区块以上行修改如下：
```
(file:///|https?:\/\/|ftp:\/\/|obsidian:\/\/|zotero:\/\/|www.)[^\s。,，！？;；：“”‘’\[\]\{\}']+|--
```

**Comment by Yaozhuwa** [comment]
是的，修改一下就行。正则表达式就是一种用来匹配指定模式的文本的一种语法，稍微学一下就知道了。之后我会在Readme中添加一个部分，列举一些常用的正则设置，方便非程序员用户使用~
