### ISSUE TITLE
有没可能增加一个批量删空行的功能？

### ISSUE THREAD

**Issue by YakshaChien** [Yaozhuwa/easy-typing-obsidian#79]
想请教作者，有没可能加一个**批量清理全文空行**的功能，这样就可以删掉一个同类的插件了...

**Comment by Yaozhuwa** [comment]
这个可以加，我想的是以怎样的形式加入比较符合本插件的主题

批量全文空格清理，是否是在粘贴网页内容或者PDF里复制的文本的情况下需要。如果这样的话，就可以搞得更方便一点，在粘贴时，直接对粘贴的文本格式化(目前本插件对粘贴的内容没有做格式化处理)，然后有删除空行的可选项，这样就整合成一个**粘贴内容时自动格式化**的设置选项。

不知道我理解的场景对不对。

**Comment by YakshaChien** [comment]
是这样的，从别处拷贝文本进OB的时候，常常会出现多个空行，就会需要在文本编辑器里面用正则表达式 `/n/n` 替换 `/n` 这样多一步操作，目前是用的“增强编辑”这个插件里面自带的一个“批量去除空行”功能，固然“增强编辑”是一个很优秀的插件，但是它的其它功能我使用到的不多，相反是您这个插件我用到的功能更多一些，在想可不可以增加上这个功能，这样可以做到插件的精简。

**Comment by Yaozhuwa** [comment]
5.0.5 增加了删除多余空白行的命令（选中文本情况下只删除选中区域的空白行，未选中文本情况下对全文删除空白行）

**Comment by YakshaChien** [comment]
已使用，非常感谢！“选中文本情况下只删除选中区域的空白行”这个很实用！
