### ISSUE TITLE
中英之间加空格考虑双链符号[[]]情况

### ISSUE THREAD

**Issue by Benature** [Yaozhuwa/easy-typing-obsidian#8]
因为有些双链名字是中文，所以我关闭了[[双链]]和文本间的空格功能，但是在双链名字是英文的时候，又希望可以自动加上空格。

举例：
```
[[工作]]与[[生活]]
[[Work]] 与 [[Life]]
```

**Comment by Yaozhuwa** [comment]
这个不冲突的，你直接把[[双链]]和文本间的空格功能打开就行

**Comment by Benature** [comment]
我的意思是希望多一个配置选项，加个中英判断，中文之间不要有空格
```diff
- 不想 [[中文]] 之间有空格
+ 不想[[中文]]之间有空格 
```

![Kapture 2021-06-11 at 23 20 13](https://user-images.githubusercontent.com/35028647/121709911-9f24cd00-cb0b-11eb-8f74-01a32bb72298.gif)

**Comment by Yaozhuwa** [comment]
我明白了。很棒的想法，我之后会添加这个功能。

**Comment by Yaozhuwa** [comment]
v3.3.0已支持该功能，只要去设置面板打开 Smart Space between link and text 开关即可。
v3.3.0 supports this feature now, just go to the settings panel and turn on the Smart Space between link and text switch.
