### ISSUE TITLE
使用templater插件 <%-* -%>代码块里编辑代码会自动给代码添加空格

### ISSUE THREAD

**Issue by cumany** [Yaozhuwa/easy-typing-obsidian#80]
比如我的模板代码块里的内容是这样的：
注：下面的代码都在 <%-*   -%> 包裹中。这个是templater插件的执行代码语法。
```
let birthday =tp.system.prompt_date("请选择ta的生日？",tp.date.now("YYYY-MM-DD"))
```
如果我把 birthday 编辑为meetday  代码块就会变成这样, “.”后面自动都加上了空格，这对代码运行来说是致命的，造成不必要的代码错误。

```
let meetday =tp. system. prompt_date ("请选择 ta 的生日？", tp. date. now ("YYYY-MM-DD"))
```
下面是动画演示这个过程：
![bug](https://user-images.githubusercontent.com/42957010/194734800-99b545c8-116c-45c6-8345-b5a6d72e1b33.gif)

**Comment by Yaozhuwa** [comment]
> 注：下面的代码都在 <%-* -%> 包裹中。这个是templater插件的执行代码语法。

本插件会自动识别多行代码块、多行公式块，但是对于这个 Templater 的代码块没有识别，所以认为是普通文本区域，就造成了错误的自动格式化。下次更新会加上这个 Templater 代码块的识别，对其内容不格式化。

本插件的自定义正则支持单行文本内匹配正则区域不自动进行格式化，如果是在单行内的 <%-* -%> 语法快，可以在本插件设置中设置正则表达式使其内部内容进行不自动格式化，如下：
```
<%.*?%>|--
```
在插件设置的自定义正则区域添加如上行即可。

在更新前，临时的解决办法可以通过命令 switch autoformat 来切换自动格式化的开关。在编辑模板文件时先关闭自动格式化，编辑完之后再打开。大佬你基于 cmenu 魔改的 Editing Toolbar 非常好用:smile:，也可以把上述命令添加到 toobar 里面方便切换。

**Comment by cumany** [comment]
> > 注：下面的代码都在 <%-* -%> 包裹中。这个是templater插件的执行代码语法。
> 
> 本插件会自动识别多行代码块、多行公式块，但是对于这个 Templater 的代码块没有识别，所以认为是普通文本区域，就造成了错误的自动格式化。下次更新会加上这个 Templater 代码块的识别，对其内容不格式化。
> 
> 本插件的自定义正则支持单行文本内匹配正则区域不自动进行格式化，如果是在单行内的 <%-* -%> 语法快，可以在本插件设置中设置正则表达式使其内部内容进行不自动格式化，如下：
> 
> ```
> <%.*?%>|--
> ```
> 
> 在插件设置的自定义正则区域添加如上行即可。
> 
> 在更新前，临时的解决办法可以通过命令 switch autoformat 来切换自动格式化的开关。在编辑模板文件时先关闭自动格式化，编辑完之后再打开。大佬你基于 cmenu 魔改的 Editing Toolbar 非常好用😄，也可以把上述命令添加到 toobar 里面方便切换。

---
很荣幸你能喜欢editing toolbar插件。
另外我建议可以增加一个排除文件夹设置。 这样就可以把模板文件夹排除，就不用担心被格式化了。

**Comment by Yaozhuwa** [comment]
5.0.5 版本增加了忽略文件/文件夹的设置选项。
