### ISSUE TITLE
数字后面输入的字（词）会被重复两次

### ISSUE THREAD

**Issue by lanx214** [Yaozhuwa/easy-typing-obsidian#82]
系统：win10
主程序版本：v0.15.9
插件版本：5.0.4
使用输入法：微软输入法

问题如题。如输入“2018年”，年字上屏后会自动变成：
![image](https://user-images.githubusercontent.com/52954312/195014103-4d35fb30-871d-487f-b0df-4da3a04db89a.png)

关闭插件后问题消失。重启主程序，重新加载插件均无效。回退到5.0.0版本问题依然存在。

**Comment by Yaozhuwa** [comment]
我在 windows10
主程序版本 v1.0，
插件 5.0.4 版本
，微软输入法下没有这个问题，要不你尝试更新下 obsidian 试试，最好能下载安装包重新安装~

**Comment by lanx214** [comment]
已经从官网重新下载安装包更新到v1.0版本主程序了，插件也更新到5.0.5了，还是有问题orz。
控制台输出：
![tmp65C7](https://user-images.githubusercontent.com/52954312/195964481-f4ad083f-03ba-43c3-9de1-731641354610.png)

**Comment by Yaozhuwa** [comment]
> 已经从官网重新下载安装包更新到v1.0版本主程序了，插件也更新到5.0.5了，还是有问题orz。 控制台输出： ![tmp65C7](https://user-images.githubusercontent.com/52954312/195964481-f4ad083f-03ba-43c3-9de1-731641354610.png)

解读一下控制台输出， input.type.compose 指的是输入法在Obsidian中的输入，EasyTyping.change 指的是插件做的改动

从控制台输出可以看到，倒数第三行为输入法中文输入 `年` 结束的状态，这时候行内容为 `2018年`，倒数第二行表示本插件将 `2018年` 替换成了 `2018 年`，直到此处都没问题。控制台输出最后一行表明是输入法又在最后添加了一个 `年` 字，结果文本就变成了 `2018 年年`。

所以这是输入法的问题，但是在我自己的 windows 10 电脑上用微软输入法没有这个问题。所以**可能**是微软输入法的设置问题，比如设置中有自动中英文添加空格或者其他自动改变编辑内容的设置？

如果还是不行的话，可以尝试下换一个输入法，比如 搜狗输入法~

**Comment by lanx214** [comment]
把输入法里里外外检查了一遍，最后通过关闭“使用以前版本的微软输入法”解决了这个问题。

插件超级好用，谢谢作者~
