### ISSUE TITLE
对{Time}这样的日期会自动格式化，导致Memos插件无法工作

### ISSUE THREAD

**Issue by heyzoeys** [Yaozhuwa/easy-typing-obsidian#83]
Memos会在记录的内容前面打上一个{TIME}的前缀标签
如果文档被格式化后，如图所示会在时间中增加一个空格，Memos插件便无法索引到这条记录的IDEA
请问如何才可以让时间不被格式化呢》？
![image](https://user-images.githubusercontent.com/93904235/195580524-525cc795-50b7-4426-ac88-ab0d1a48f320.png)

**Comment by Yaozhuwa** [comment]
请使用软件的自定义表达式功能：添加如下规则行
```
\d{2}:\d{1,2}|--
```
#5 已经讨论过

**Comment by heyzoeys** [comment]
@Yaozhuwa 非常感谢回复 已经自己解决了。  也是用的正则匹配，跟你给的方法一样！
