### ISSUE TITLE
目前“、、|”自动转换为“/|”，或许应为“\|”？

### ISSUE THREAD

**Issue by ouatis** [Yaozhuwa/easy-typing-obsidian#86]
这条规则可能写岔了。

“/”在中文全角输入模式下一键就可以输入，不需要转半角。

希望改成转换为“\”，非常感谢。

**Comment by Yaozhuwa** [comment]
这可能是因为每个输入法特性不一样，我之后**可能**会考虑将这条规则从内置规则中去掉，让用户自定义来决定其最终效果。

**Comment by Yaozhuwa** [comment]
> 这可能是因为每个输入法特性不一样，我之后可能会考虑将这条规则从内置规则中去掉，让用户自定义来决定其最终效果。

短期内我还是不考虑这么做，因为 `|` 符号目前被我用来作为转换规则的光标位置了，如果修改的话会让现有的规则都失效，这样比较麻烦。
