### ISSUE TITLE
URL被错误分隔

### ISSUE THREAD

**Issue by bohr777** [Yaozhuwa/easy-typing-obsidian#88]
输入形如 `http://www.com/#/api?a=b` 格式的URL，会被错误格式化为如下形式

![image](https://user-images.githubusercontent.com/56676965/198240393-a97933ca-2676-4842-8f8d-65ecfb9eb400.png)

是需要修改什么设置吗

**Comment by Yaozhuwa** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/28787183/198559105-82bb30e5-f3de-40c9-a7fc-b517d1f737bd.png">
是匹配标签的正则和匹配链接的正则之间先生效了标签的，正则表达式的顺序即他们的生效优先级，所以，你只要把标签这行这则放到链接正则的后面就好了~

**Comment by bohr777** [comment]
已解决，感谢
