### ISSUE TITLE
Feature request: Make this plugin work everywhere in Obsidian, not just in editor

### ISSUE THREAD

**Issue by Lulullia** [Yaozhuwa/easy-typing-obsidian#89]
Hi! Thanks for this plugin, it's really useful for typing special unicode characters easily.

It would be nice if auto-replace could work everywhere in Obsidian, for example modals, note filename input, search etc.

Right now I use auto-replace to add certain emojis I use for categorizing notes, but if I need to rename a note or search for it in the sidebar, I need to copy-paste the character because my auto-replace shorthand doesn't work in those places.

I hope this is possible! Thank you.

**Comment by Yaozhuwa** [comment]
Sorry, I don't kown how to do that yet. But I recommend you  another tool: [espanso](https://espanso.org/)

**Comment by Lulullia** [comment]
Thanks for the suggestion! It's really useful. I'll continue using EasyTyping for everything else.

**Comment by Yaozhuwa** [comment]
Just keep this issue open. Maybe oneday I can find a solution to it.
