### ISSUE TITLE
请问这个正则怎么配置啊？

### ISSUE THREAD

**Issue by zhl111** [Yaozhuwa/easy-typing-obsidian#9]
上下是一个链接，但是它……
![image](https://user-images.githubusercontent.com/29135984/121781883-67845680-cbd9-11eb-9ead-5dd53fffc70a.png)
这个经常变动，导致无法链接

**Comment by Yaozhuwa** [comment]
你好，目前正则功能还有点问题，先不要用。
目前识别md链接的是正则`let regMdLink = /\!?\[[^\[\]]*?\]\([^\s\)\(\[\]\{\}']*\)/g;` 就是说md链接的小括号里面不能有`()`英文的左右括号还有方括号。还有空格。
输入链接的时候，你要先打好 `[]()`，然后再输入就不会被格式化了。我自己的话主要是不常用md链接。一般直接按两个`[`变成`[[]]`,然后输入内容就行。

**Comment by zhl111** [comment]
哦，我是下载的网页文件，直接拖拽进入ob，按ctrl生成的链接。可能这个网页生成的文件名太过复杂😭
