### ISSUE TITLE
"：|**" 转换为 "**：|" 时没反应

### ISSUE THREAD

**Issue by romantic-black** [Yaozhuwa/easy-typing-obsidian#90]
`：|**` 转为 `**：|` 时没反应，测试了一下，似乎将 `：`换为其他全角符号也没有反应，半角可以，汉字可以

**Comment by Yaozhuwa** [comment]
我这边是可以的
<img width="568" alt="image" src="https://user-images.githubusercontent.com/28787183/198558488-fcac5abc-94d4-4f99-bc22-1b2f05011452.png">

![issue90](https://user-images.githubusercontent.com/28787183/198558163-ab9673b1-4b0e-4636-9619-653cc5753ebe.gif)

**Comment by Yaozhuwa** [comment]
你可以检查下自己的设置是否正确，如果设置是对的，但还是无法成功，请提供OB版本，插件版本，windows还是Mac等信息，然后打开插件设置中的Debug开关，打开控制台，复现自己的bug情况，然后截图控制台输出，这样我可能能找到不生效的原因~

**Comment by romantic-black** [comment]
Ob版本：v1.0.3
插件版本：5.0.7
插件的设置（data.json）:
```
{
  "SelectionEnhance": false,
  "IntrinsicSymbolPairs": false,
  "BaseObEditEnhance": false,
  "FW2HWEnhance": true,
  "AutoFormat": true,
  "ExcludeFiles": "",
  "ChineseEnglishSpace": true,
  "ChineseNoSpace": true,
  "PunctuationSpace": false,
  "AutoCapital": false,
  "AutoCapitalMode": "typing",
  "PunctuationSpaceMode": "global",
  "InlineCodeSpaceMode": 1,
  "InlineFormulaSpaceMode": 1,
  "InlineLinkSpaceMode": 1,
  "InlineLinkSmartSpace": true,
  "UserDefinedRegSwitch": true,
  "UserDefinedRegExp": "{{.*?}}|++\n#[\\u4e00-\\u9fa5\\w\\/]-|++\n\\[\\!.*?\\][-+]{0,1}|-+\n(https?:\\/\\/|ftp:\\/\\/|obsidian:\\/\\/|zotero:\\/\\/|www.)[^\\s（）《》。,，！？;；：“”‘’\\)\\(\\[\\]\\{\\}']+|++",
  "debug": true,
  "userSelRepRuleTrigger": [],
  "userSelRepRuleValue": [],
  "userDeleteRulesStrList": [
    [
      "demo|",
      "|"
    ]
  ],
  "userConvertRulesStrList": [
    [
      ":)|",
      "😀|"
    ],
    [
      "：|**",
      "**：|"
    ]
  ],
  "userSelRuleSettingsOpen": true,
  "userDelRuleSettingsOpen": true,
  "userCvtRuleSettingsOpen": true
}
```
我今天又尝试了一下，还是不行：
![动画](https://user-images.githubusercontent.com/63280964/198588811-d934b8d0-2821-45b0-a113-dc369c612422.gif)

我使用的其他插件包括Zh增强编辑，但关闭后还是有这个问题，其他插件和文字输入关系不大

**Comment by Yaozhuwa** [comment]
是因为输入法对`：`输入判断是中文输入状态，和我这边的输入法特性不一样，导致我没考虑到这种情况~

**Comment by Yaozhuwa** [comment]
我尝试修复下，由于我和你这边的输入法特性差异，我不确定我的修复是否生效，可以的话麻烦你下载链接中的main.js 替换插件文件中的main.js 看看是否能成功修复 https://wormhole.app/Zqro6#IvDxE1DZFiOV3ucsT93kwg，链接24小时内有效，失效的话我再发一个~

**Comment by Yaozhuwa** [comment]
Easy Typing 5.0.8 我尝试修复了这个问题，由于我这边输入法和你的不同，我无法测试实际的效果，如果可以请反馈下是否成功解决问题~

**Comment by romantic-black** [comment]
> Easy Typing 5.0.8 我尝试修复了这个问题，由于我这边输入法和你的不同，我无法测试实际的效果，如果可以请反馈下是否成功解决问题~

ok，我这边也成功执行了，十分感谢，这个插件对我帮助很大
