### ISSUE TITLE
更新后自定义规则无效

### ISSUE THREAD

**Issue by ribber** [Yaozhuwa/easy-typing-obsidian#91]
Basic symbol imput enhance for obsidian 选项关了，自定义了 "··|" auto convert to "`|" 不生效，之前是好了，更新了插件之后就不生效了。同样不生效的还有 "￥￥|" auto convert to "$|"

**Comment by Yaozhuwa** [comment]
MacOS Obsidian 1.0.3 EasyTyping 5.0.7。我这边是可以正常生效的。你可以提供更多信息吗，比如，从那个版本到那个版本更新后就失效了，还有就是，打开插件设置的 Debug 开关，然后 Ctrl+shift+I(CMD+Option+I)打开控制台，在Ob中复现Bug场景，将控制台截图发我看下，可能能找到问题所在~

**Comment by ribber** [comment]
Windows 系统，Obsidian 1.0.3，EasyTyping 5.0.7

之前的版本应该是 Obsidian 1.0.0 ，EasyTyping 5.0.6

配置规则 "・・|" auto convert to "`|"

输入两个 ・・后没有转换，控制台打印了如下信息

ViewUpdate Catch Change-> Type: input.type.compose,  554 554  554 555 ·
ViewUpdate Catch Change-> Type: input.type.compose,  555 555  555 556 ·

**Comment by Yaozhuwa** [comment]
感谢反馈，我大概知道问题所在了，我尝试修复了下，由于我和你这边的输入法特性差异，我不确定我的修复是否生效，可以的话麻烦你下载链接中的main.js 替换插件文件中的main.js 看看是否能成功修复 https://wormhole.app/Zqro6#IvDxE1DZFiOV3ucsT93kwg ，链接24小时内有效，失效的话我再发一个~

**Comment by Yaozhuwa** [comment]
Easy Typing 5.0.8 我尝试修复了这个问题，由于我这边输入法和你的不同，我无法测试实际的效果，如果可以请反馈下是否成功解决问题~

**Comment by ribber** [comment]
Easy Typing 5.0.8 没有问题了。只是有点小插曲，直接在 ob 里更新结果没有更新 main.js，将插件卸载再重装就可以了
