### ISSUE TITLE
关闭了自动格式化的总开关，但是发现粘贴到编辑器依然被自动格式化了

### ISSUE THREAD

**Issue by ribber** [Yaozhuwa/easy-typing-obsidian#92]
有些情况需要保留中文间的空格，比如 

第 2 章 历史上的密码

**Comment by Yaozhuwa** [comment]
好的，这是个 Bug :cry:，下个版本会修复~

**Comment by ribber** [comment]
非常感谢！

**Comment by Yaozhuwa** [comment]
> 有些情况需要保留中文间的空格，比如
> 
> 第 2 章 历史上的密码

其实如果想要这个效果，可以打开插件的正则表达式功能，并添加如下正则规则行，中文自动去空格就不会对这种情况进行去空格，也就不用每次都开关插件的自动格式化功能了~
```
章 |--
```
<img width="465" alt="image" src="https://user-images.githubusercontent.com/28787183/198836834-cd05295d-40bd-4f04-afee-03bdf57e8ed3.png">

**Comment by Yaozhuwa** [comment]
Easy Typing 5.0.8 应该修复了这个问题~

**Comment by ribber** [comment]
经测试，Easy Typing 5.0.8 没有问题了
