### ISSUE TITLE
转换失败

### ISSUE THREAD

**Issue by wanguano** [Yaozhuwa/easy-typing-obsidian#96]
- 转换规则
- > 中文状态下——，转换英文状态_
![](https://mingcloudpic.oss-cn-beijing.aliyuncs.com/img/20221103203352.png)

- 测试结果
![](https://mingcloudpic.oss-cn-beijing.aliyuncs.com/img/%E5%8A%A8%E7%94%BB.gif)

> 在没更新之前插件之前，转换成功

**Comment by Yaozhuwa** [comment]
OK，我下个版本修复

**Comment by Yaozhuwa** [comment]
v5.0.10 应该修复了这个问题~
