### ISSUE TITLE
auto capitalization after curly quotes (“”)

### ISSUE THREAD

**Issue by GamerGirlandCo** [Yaozhuwa/easy-typing-obsidian#97]
when i pick "format this article" from the command palette, lines that start with a curly quote (`“`) remain untouched.

am i missing something?

**Comment by Yaozhuwa** [comment]
> when i pick "format this article" from the command palette, lines that start with a curly quote (“) remain untouched.

My fault, I didn't take that situation into account~ I'll fix it in next release.

**Comment by Yaozhuwa** [comment]
v5.0.10, autocapitalize works for lines that start with a curly quote (“).
