### ISSUE TITLE
手动录入标题时会导致出错

### ISSUE THREAD

**Issue by Thinkbond** [Yaozhuwa/easy-typing-obsidian#98]
在编辑器中手动输入二级或多级“##标题”时会自动在“#”后面添加空格，导致标题设置失败。

------
附现有的正则设置项：
```
{{.*?}}|++
#[\u4e00-\u9fa5\w\/]+|++
\[\!.*?\][-+]{0,1}|-+
(https?:\/\/|ftp:\/\/|obsidian:\/\/|zotero:\/\/|www.)[^\s（）《》。,，！？;；：“”‘’\)\(\[\]\{\}']+|++
\d{2}:\d{1,2}|++
\[\!.*?\][-+]{0,1}|-+
```

**Comment by Yaozhuwa** [comment]
> 在编辑器中手动输入二级或多级“##标题”时会自动在“#”后面添加空格，导致标题设置失败。

1. Obsidian 的 Markdown 语法本身在 `##标题` 这样的内容不会识别为标题，需要在最后一个 # 后添加一个空格。
2. 如果的确需要输入 `##一些文字` 这样的内容，可以删除正则设置的第二行。

**Comment by Thinkbond** [comment]
没有遇到过在原本不是标题的文本前通过添加#来实现将此文本设置为标题或修改标题层级的情况吗？

**Comment by Thinkbond** [comment]
![tb0t4-wcgrv](https://user-images.githubusercontent.com/9856020/202092052-30612066-a644-4146-8b57-8c8d42c0526c.gif)
附加操作录屏

**Comment by Thinkbond** [comment]
已解决。
